src/dailyai/services/ollama_ai_services.py
src/dailyai/services/open_ai_services.py

This PR adds support for ollama LLM accessed via its new OpenAI compatability. I was pleasantly surprised that the `AsyncOpenAI` interface is supported so we even get streaming access and this fits well with our general model of using asyncio in the SDK.
(while I was at it I removed some unused imports from the openai_ai_services.py module)

Ollama LLM service

---

src/dailyai/queue_aggregators.py
src/dailyai/queue_frame.py
src/dailyai/services/base_transport_service.py
src/dailyai/services/daily_transport_service.py
src/dailyai/services/fal_ai_services.py
src/dailyai/services/local_transport_service.py
src/examples/foundational/01-say-one-thing.py
src/examples/foundational/02-llm-say-one-thing.py
src/examples/foundational/03-still-frame.py
src/examples/foundational/04-utterance-and-speech.py
src/examples/foundational/05-sync-speech-and-image.py
src/examples/foundational/06-listen-and-respond.py
src/examples/foundational/06a-image-sync.py
src/examples/foundational/07-interruptible.py
src/examples/foundational/08-bots-arguing.py
src/examples/foundational/10-wake-word.py
src/examples/foundational/11-sound-effects.py
src/examples/foundational/13-whisper-transcription.py
src/examples/foundational/13a-whisper-local.py
src/examples/foundational/support/runner.py
src/examples/internal/11a-dial-out.py

Another pass of autopep8 just to keep things standard.
For posterity here's the command I used:
```
find . -type f -name '*.py' ! -path '*/env/*' ! -path "*/build/*" |xargs autopep8 --in-place --max-line-length 100 --aggressive --aggressive
```
At some point would be nice to automate this!
Ran tests and a handful of examples (1 - 6) to make sure nothing broke.

Another autopep8 formatting pass

---

src/dailyai/services/base_transport_service.py
src/dailyai/services/daily_transport_service.py

Add a signal handler and a `finally` block to call `client.leave` when the user presses CTRL-C or when the transport otherwise shuts down.

Call client.leave on keyboard interrupt

---

src/dailyai/pipeline/aggregators.py
src/dailyai/pipeline/frame_processor.py
src/dailyai/pipeline/frames.py
src/dailyai/pipeline/pipeline.py
src/dailyai/services/ai_services.py
src/dailyai/services/base_transport_service.py
src/dailyai/services/local_stt_service.py
src/dailyai/tests/test_aggregators.py
src/dailyai/tests/test_ai_services.py
src/dailyai/tests/test_daily_transport_service.py
src/dailyai/tests/test_pipeline.py
src/examples/foundational/01-say-one-thing.py
src/examples/foundational/03-still-frame.py
src/examples/foundational/03a-image-local.py
src/examples/foundational/04-utterance-and-speech.py
src/examples/foundational/05-sync-speech-and-image.py
src/examples/foundational/05a-local-sync-speech-and-text.py
src/examples/foundational/06-listen-and-respond.py
src/examples/foundational/06a-image-sync.py
src/examples/foundational/08-bots-arguing.py
src/examples/foundational/10-wake-word.py
src/examples/foundational/11-sound-effects.py
src/examples/foundational/13a-whisper-local.py
src/examples/image-gen.py
src/examples/internal/11a-dial-out.py

The `.*QueueFrame` naming was feeling increasingly clunky to me, so I removed the `Queue` part.

Remove Queue in frame names

---

src/dailyai/pipeline/aggregators.py
src/dailyai/services/ai_services.py
src/dailyai/services/azure_ai_services.py
src/dailyai/services/base_transport_service.py
src/dailyai/services/open_ai_services.py
src/examples/foundational/07-interruptible.py

This fixes up how the interruptible pipeline works. The biggest thing is that I created an "LLMContextAggregator" that listens for TextFrames and accumulates them. When it gets an `LLMResponseEndFrame` it updates its (mutable) message array. This also changes the TTS service to emit the aggregated text that it has converted to audio _after_ it's enqueued the AudioFrames.

Fix interruptible pipeline runner and aggregator.

---

src/dailyai/pipeline/pipeline.py
src/dailyai/services/ai_services.py
src/dailyai/tests/test_pipeline.py
src/examples/foundational/04-utterance-and-speech.py
src/examples/foundational/05-sync-speech-and-image.py
src/examples/foundational/06-listen-and-respond.py

I realized that my new pipeline implementation had a problem. It effectively did this:
```
frames = []
async for frame in frame_processor_1.process_frame(source.get()):
frames.append(frame)y
next_frames = []
async for frame in frame_processor_2.process_frame(frames.pop(0)):
next_frames.append(frame)
...etc
```
That is, it was waiting for each `frame_processor` iterator to complete before sending those frames to the next processor in the pipeline. This was wrong!
I changed it so it's recursive and each individual frame from a processor will be passed to the next processor in the pipeline. This mirrors how it worked when we nested generators initially.
I could change this to not be recursive and to instead use a queue, but the depth of recursion is limited by the number of processors in the …

Optimize pipeline processing

---

src/dailyai/services/fal_ai_services.py
src/examples/foundational/01-say-one-thing.py
src/examples/foundational/02-llm-say-one-thing.py
src/examples/foundational/03-still-frame.py
src/examples/foundational/04-utterance-and-speech.py
src/examples/foundational/05-sync-speech-and-image.py
src/examples/foundational/06-listen-and-respond.py

Anything we do in an event handler blocks other event handlers from being called. So, for many of the samples, it's much better to have an asynchronous function waiting on an event that gets triggered by the `on_other_participant_joined` event.

Don't do time-consuming processing in `on_other_joined_event`

---

src/dailyai/pipeline/aggregators.py
src/dailyai/pipeline/frames.py
src/dailyai/pipeline/opeanai_llm_aggregator.py
src/dailyai/services/ai_services.py
src/dailyai/services/azure_ai_services.py
src/dailyai/services/base_transport_service.py
src/dailyai/services/fal_ai_services.py
src/dailyai/services/ollama_ai_services.py
src/dailyai/services/open_ai_services.py
src/dailyai/services/openai_api_llm_service.py
src/dailyai/services/openai_llm_context.py
src/dailyai/tests/integration/integration_azure_llm.py
src/dailyai/tests/integration/integration_ollama_llm.py
src/dailyai/tests/integration/integration_openai_llm.py
src/dailyai/tests/test_daily_transport_service.py
src/examples/foundational/08-bots-arguing.py
src/examples/starter-apps/patient-intake.py

This PR adds a generic "OpenAI API" LLM class. It also defines an "LLM Context" object that can be used to maintain state for the LLM like the message history, available functions (via the `tools` property), and the `tool_choice` property. Since these change for every chat completion it feels like it makes sense to store them in the same place as the messages.
There's also a new `OpenAILLMContextFrame` frame type that passes a reference to an LLMContext object.
I'll create OpenAI specific pair of LLMAggregator classes to use this context, probably tonight or early tomorrow morning.
I'm still noodling on if and how we should have a generic LLM, or if it's reasonable (at least to start) to expect the pipeline to have some knowledge of the kind of LLM that's being used, simply because …

Base OpenAI LLM service

---

src/dailyai/requirements.txt

This file isn't used and I think was mistakenly merged. Dependabot was complaining about the version of Pillow, but would rather just remove the file entirely.

Remove unused requirements file

---

pyproject.toml
src/dailyai/pipeline/merge_pipeline.py
src/dailyai/pipeline/pipeline.py
src/dailyai/services/ai_services.py
src/dailyai/services/azure_ai_services.py
src/dailyai/services/base_transport_service.py
src/dailyai/services/daily_transport_service.py
src/dailyai/services/openai_api_llm_service.py
src/dailyai/tests/test_ai_services.py
src/examples/foundational/01-say-one-thing.py
src/examples/foundational/02-llm-say-one-thing.py
src/examples/foundational/03-still-frame.py
src/examples/foundational/04-utterance-and-speech.py
src/examples/foundational/05-sync-speech-and-image.py
src/examples/foundational/06-listen-and-respond.py
src/examples/foundational/07-interruptible.py
src/examples/starter-apps/chatbot.py
src/examples/starter-apps/storybot.py

I wanted to clean up what it means to be a FrameProcessor vs what it means to be a pipeline. Here's my thesis:
* a FrameProcessor consumes a single frame and emits 0 or more frames
* a pipeline sends Frames to FrameProcessors
The AIService class muddied this a little bit (because originally it was both a frame processor *and* a one-step pipeline).
This PR does a few things:
* removes the `run` and `run_to_queue` methods from the AIService class.
* updates the `queue_frames` method on the Pipeline to consume an iterable rather than a Frame or a List
* adds a `pipeline` parameter to the `transport.run` method. If a pipeline is provided, the `run` method will set its queues to point to the transport, run it until it ends, then exit.
* adds a `say` convenience method to the _transport_, …

Remove run_to_queue and run from AIService class

---

src/dailyai/pipeline/frames.py
src/dailyai/services/base_transport_service.py
src/dailyai/services/daily_transport_service.py

Added support for app messages. A few notes:
* I separated out a "received app message" from a "send app message" so we don't get into feedback loops where incoming app messages are ignored and passed through to the transport, to be sent again, etc
* I went back and forth on adding support for this to the base transport and settled on "it's less confusing if it's there, but unsupported." Could probably be convinced otherwise
* this feels pretty straightforward. One thing to note: To test this I changed the 06- sample and added a frame processor that listened for LLM output and yielded an app message on the LLMResponseEndFrame. This worked, *but* the output wasn't sent until the audio was done speaking, because we process the audio synchronously and don't get to the frame until the audio's …

Support for app messages

---

examples/foundational/01-say-one-thing.py
examples/foundational/02-llm-say-one-thing.py
examples/foundational/03-still-frame.py
examples/foundational/04-utterance-and-speech.py
examples/foundational/05-sync-speech-and-image.py
examples/foundational/06-listen-and-respond.py
examples/foundational/06a-image-sync.py
examples/foundational/07-interruptible.py
examples/foundational/08-bots-arguing.py
examples/foundational/10-wake-word.py
examples/foundational/11-sound-effects.py
examples/foundational/13-whisper-transcription.py
examples/internal/11a-dial-out.py
examples/server/daily-bot-manager.py
examples/starter-apps/chatbot.py
examples/starter-apps/patient-intake.py
examples/starter-apps/storybot.py
examples/starter-apps/translator.py

By default load_dotenv [does not override existing environment variables.](https://pypi.org/project/python-dotenv/#:~:text=By%20default%2C%20load_dotenv%20doesn%27t%20override%20existing%20environment%20variables.) This has confused some users who are newer to Python, as this is not the same behavior as other programming languages like Node Js. This reverses the default behavior.

fix: force overriding environment variables from .env files

---

examples/foundational/04-utterance-and-speech.py
src/dailyai/pipeline/frame_processor.py
src/dailyai/pipeline/pipeline.py
tests/test_pipeline.py

This PR adds some visual logging to watch frames go through pipelines.
Here's an example from sample 04. This sample uses two Pipelines with a SequentialMergePipeline, so the hardcoded one runs first. I *think* this makes it easy to see which frames are being passed along.
Note that I drop Audio frames. I might change this to show the first and then an ellipse or something until there's something that's *not* an audio frame.
```
10 2024-03-27 18:46:04,228   source -> TextFrame: "My friend the LLM is going to tell a joke about llamas" -> AzureTTSService
10 2024-03-27 18:46:04,229     AzureTTSService -> TextFrame: "My friend the LLM is going to tell a joke about llamas" -> AzureTTSService
10 2024-03-27 18:46:04,229   source -> EndPipeFrame -> AzureTTSService
10 2024-03-27 18:46:04,229 …
```

Add logging for pipeline

---

src/dailyai/pipeline/merge_pipeline.py

I checked in this `print` statement by mistake and it's _very_ noisy in the 04- sample.

Remove mistakenly-added print statement

---

.dockerignore
.gitignore
Dockerfile
examples/server/daily-bot-manager.py
examples/starter-apps/translator.py
pyproject.toml
src/dailyai/transports/local_transport.py
src/dailyai/transports/threaded_transport.py

This PR removes the forced dependencies on `torch`, `torchaudio`, and `pyaudio`. If you try to use VAD by setting `vad_enabled=True` on a DailyTransport, you'll get an error indicating you need to pip install `torch` and `torchaudio` yourself. Likewise, if you try to use the local transport, you'll need to `pip install pyaudio` and deal with any platform-specific dependencies there too.
Note: The local examples are actually broken right now; I'll have to fix that later.

Modularize tricky dependencies

---

src/dailyai/transports/threaded_transport.py

If you use the DailyTransport and set the `duration_minutes` property, the bot will leave the room after that many minutes have elapsed, but the pipeline itself will still be running. This change allows the pipeline to stop running, so the python process can exit cleanly.

Allow transport exit to end a running pipeline

---

CHANGELOG.md
src/pipecat/processors/aggregators/llm_response.py
src/pipecat/processors/aggregators/user_response.py
src/pipecat/services/openai.py

We were pushing interruption frames in the audio task. This was caussing the LLMUserResponseAggregator to push the accumulated text and then casuing the LLM to respond.

processors: only interrupt asssisstant

---

CHANGELOG.md
examples/foundational/12a-describe-video-gemini-flash.py
examples/foundational/12b-describe-video-gpt-4o.py
examples/foundational/12c-describe-video-anthropic.py
src/pipecat/services/anthropic.py
src/pipecat/services/azure.py
src/pipecat/services/fireworks.py
src/pipecat/services/google.py
src/pipecat/services/ollama.py
src/pipecat/services/openai.py

services(azure): fix AzureLLMService

---

src/pipecat/transports/services/helpers/daily_rest.py

Most Pipecat projects that use Daily as a transport will require the provisioning of rooms and tokens. Indeed, this will likely be the case for most transports where pre-configuration is required in order to join a session.
I propose a `helpers` directory that includes transport specific utilities that are helpful for running bots and deployment.
Right now, this file has manually been created to wrap room creation, retrieval and token issuance. 
It may be better that these are autogenerated in the future.

Created REST helpers for Daily covering commonly used methods for running / deployment

---

examples/foundational/07-interruptible.py
examples/foundational/07c-interruptible-deepgram.py
examples/foundational/16-gpu-container-local-bot.py
src/pipecat/services/deepgram.py

1. Add the `base_url` as an optional argument to the Deepgram TTS service constructor.
2. Don't emit an error to the PipelineTask when Deepgram TTS returns an "unutterable" response.
3. New foundational example for the GPU bot demo project.

Deepgram TTS service improvements

---

src/pipecat/services/ai_services.py

To cover cases when the LLM response does not end in punctuation.

Flush output from TTSService on LLMFullResponseEndFrame

---

examples/deployment/flyio-example/Dockerfile
examples/deployment/flyio-example/README.md
examples/deployment/flyio-example/bot.py
examples/deployment/flyio-example/bot_runner.py
examples/deployment/flyio-example/env.example
examples/deployment/flyio-example/example-fly.toml
examples/deployment/flyio-example/install_deps.py
examples/deployment/flyio-example/requirements.txt

This PR adds a barebones `bot_runner.py`, `bot.py` and `Dockerfile` for deploying Pipecat bots on https://fly.io
Unlike other examples which run bots as shell processes, this example shows how to launch a new VM for each user session, supporting better productization and scalability. 
Further information about the pattern are available in the Pipecat documentation.

Example deployment pattern for fly.io

---

README.md

Fix for the error in the README.md example 
Running the code as is gives a `SyntaxError: positional argument follows keyword argument` due to `bot_name` and `params` keywords not being provided in the DailyTransport object instantiation call 
Thanks!

Fix error with readme example - SyntaxError: positional argument follows keyword argument

---

examples/foundational/02-llm-say-one-thing.py
examples/foundational/07d-interruptible-cartesia.py
pyproject.toml
src/pipecat/services/ai_services.py
src/pipecat/services/cartesia.py

This PR changes the Cartesia service over to use the new bidirectional streaming. This allows for better tone consistency between sentences.
We also change the logic for sending TextFrames down the pipeline. TextFrames are used to manage the LLM context. With word-level timestamps, we can send individual TextFrames at the same time as we expect the raw audio to be sent over the transport layer. This allows us to get very close to matching up what a human participant hears with the LLM context.
The logic here is a little bit messy, because of how our pipelines work and what the base TTSService class is doing. Feedback is welcome.
Note that it's helpful to move the context aggregation in front of the transport, if we're able to use word-level timestamps to manage the context. The transport …

Cartesia streaming (WebSocket) and word-level timestamps support

---

CHANGELOG.md
src/pipecat/frames/frames.py
src/pipecat/processors/aggregators/llm_response.py
src/pipecat/processors/frameworks/langchain.py
src/pipecat/services/anthropic.py
src/pipecat/services/google.py
src/pipecat/services/openai.py
tests/integration/integration_openai_llm.py

This was added in the past to properly handle interruptions for the LLMAssistantContextAggregator. But this is not necessary anymore since we can handle interruptions by just processing the StartInterruptionFrame, so there's no need for these extra frames.

remove LLMResponseStartFrame and LLMResponseEndFrame

---

src/pipecat/processors/text_transformer.py

fix: push_frame use TextFrame from str
```
self.push_frame(TextFrame(text=result))
```

fix: push_frame use TextFrame

---

pyproject.toml

This will allow the module build to succeed outside of a git repository.

chore: Enable build without git

---

examples/foundational/19b-tools-video-anthropic.py
pyproject.toml
src/pipecat/services/anthropic.py

Implements prompt caching.
Missing: wiring up two new usage counts
- cache_creation_input_tokens
- cache_read_input_tokens
Anthropic docs are here: https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching

Support for Anthropic prompt caching beta

---

src/pipecat/services/azure.py

In the AzureSTTService, the timestamp parameter for constructing TranscriptionFrame is incorrectly typed. Expected type is str, but an int is being provided instead.
When I try to using AzureSTT instead of Daily Transcription in the RTVI use case, this issue causes the construction of RTVITranscriptionMessageData to fail in the RTVI processors.

services(azure): fix TranscriptionFrame parameter type

---

src/pipecat/transports/network/websocket_server.py

`BaseOutputTransport` declares an `_audio_buffer` instance variable. `WebsocketServerOutputTransport` accidentally reuses that variable internally assuming it's class-local and not inherited.
This PR renames the variable in `WebsocketServerOutputTransport` to avoid the name collision.

transports(websocket): fix `_audio_buffer` being accidentally overwritten

---

src/pipecat/services/anthropic.py

when tool has zero arguments, anthropic doesn't return a JSON, but an empty string. setting default value to empty dictionary

handle empty parameters for anthropic function calling

---

src/pipecat/serializers/livekit.py

Implement the conversion between pipecat's AudioRawFrame and LiveKit's AudioFrame.
It can help to bridge LiveKit Agents via WebSocket.

Add livekit audio serializers

---

src/pipecat/processors/frameworks/rtvi.py
src/pipecat/services/together.py

Fix two issues that were preventing Together/Llama 3.1 function calling with RTVI:
1. `RTVILLMFunctionCallMessageData` expects `tool_call_id` to be a `str`, but together.py was passing a `UUID`.
2. `RTVILLMFunctionCallResultData` expected the `result` field to be a `dict`, but Together's library requires that message content for the `"tool"` role be a `str`.
For (2) I loosened the type of `RTVILLMFunctionCallResultData::result` to `dict | str`, and also forced the `"content"` into a `str` in together.py.

fixup type mismatches between rtvi data structures and together.py

---

src/pipecat/utils/utils.py

Avoids the critical section with threading.Lock in favor of itertools.count.
`count` objects are threadsafe, and their critical section is implemented in C and provide better performance that Python level locking.
This update also provides some speedup, I will make no claims on the factor as the benchmarks are not rigorous. 
Setup: Just ran these on my M2 macos with Python 3.12.5, better benching methodology can be done if requested.
**After**
```bash
$ python -m timeit -s "from pipecat.utils.utils import obj_count, obj_id" "obj_id()"
10000000 loops, best of 5: 31.7 nsec per loop
$ python -m timeit -s "from pipecat.utils.utils import obj_count, obj_id" "obj_count(object)"
5000000 loops, best of 5: 93.8 nsec per loop
```
**Before**
```bash
$ python -m timeit -s "from pipecat.utils.utils …
```

Generate ids with itertools.count

---

src/pipecat/processors/aggregators/llm_response.py

I have been meaning to fix this one forever!

fix for leading space in context aggregator strings

---

src/pipecat/services/cartesia.py
src/pipecat/transports/network/fastapi_websocket.py

Implements a `flush_audio` for `CartesiaTTSService` when LLM response end frames are processed.
Additionally, there is a bug with the FastAPIWebsocket where the audio buffer holds on up to 200 ms of audio in the buffer at the frame size boundaries. We should still flush out the entire audio for the partial final frames to deliver the full set of audio frames back to the user.

[Cartesia] Fix streaming truncation bug with Twilio Fast API WS

---

src/pipecat/services/ai_services.py
src/pipecat/services/openai.py

Two small issues that showed up while I was testing webhook function calls.

fix small issues that crept into main

---

CHANGELOG.md
examples/foundational/07l-interruptible-together.py
src/pipecat/services/anthropic.py
src/pipecat/services/openai.py
src/pipecat/services/together.py

I've opted to keep the inputs to the most common options. With this structure in place, it'll be easy to expand as needed.
Also, I added a Together AI example to make testing with Together AI easier.

Add input params for OpenAI, Anthropic, Together AI LLMs

---

examples/foundational/07l-interruptible-together.py
src/pipecat/services/anthropic.py
src/pipecat/services/openai.py
src/pipecat/services/together.py

Popular configuration params are already supported. This adds an `extra` property which allows you to pass through any LLM property.

Add extra input param to LLMs

---

src/pipecat/services/elevenlabs.py

Optional support for `language_code`, which helps enforce a language for the model.

Add language_code support for ElevenLabs TTS

---

src/pipecat/services/ai_services.py

Call `flush_audio()` after direct calls to TTS `say()` and when processing `TTSSpeakFrame`s.

add calls to flush_audio for say() and rtvi action

---

examples/foundational/07c-interruptible-deepgram.py
src/pipecat/services/deepgram.py

Refactoring to use the Deepgram client. Goal is to make this easier to use in pipecat apps.

Improve usability of Deepgram TTS: use Deepgram client, remove aiohttp

---

CHANGELOG.md
src/pipecat/frames/frames.py
src/pipecat/services/ai_services.py
src/pipecat/services/anthropic.py
src/pipecat/services/azure.py
src/pipecat/services/elevenlabs.py
src/pipecat/services/google.py
src/pipecat/services/openai.py
src/pipecat/services/together.py

TTSUpdateSettingsFrame, STTUpdateSettingsFrame, and LLMUpdateSettingsFrame replace the corresponding settings frames for TTS, STT, and LLM.
@aconchillo this is to simplify the updates into a single frame, as you requested. This feels much cleaner!
Also, related to updates, I noticed that there was mixed use of `language_code` and `language` for TTS services, so I'm aligning to `language` for all services.

Consolidate update frames classes into a single UpdateSettingsFrame class

---

src/pipecat/services/google.py

Language is required; there is no default value.

Set Google TTS default language to en-US

---

examples/foundational/07l-interruptible-together.py
src/pipecat/processors/aggregators/llm_response.py
src/pipecat/services/anthropic.py
src/pipecat/services/openai.py
src/pipecat/services/together.py

1. Add the pushing of `OpenAILLMContextFrame`s from assistant context aggregator class descendants. Note that for historical reasons, we don't call `super()._push_aggregation()`. That would require some refactoring. (Which would be nice to do at some point.)
2. Add an argument to the assistant context aggregators that governs whether to add whitespace between aggregated `TextFrame` content or not. When we send text to be aggregated from TTS services based on word-level output timestamp information, we need to add spaces between the words. On the other hand, when we send text directly from LLM inference, we want to concatenate exactly as we receive the LLM's chunks.
Another approach would have been to put a processor in between the TTS and the aggregator that adds spaces between words. …

pushing context frames from assistant aggregators

---

examples/foundational/07a-interruptible-anthropic.py
src/pipecat/services/ai_services.py
src/pipecat/utils/string.py

How do we feel about changing a utility function's return type from `bool` to `int`? This should not be a breaking change for any actual code, modulo type annotations complaining, perhaps?
This PR fixes the fact that we were looking for end-of-sentence patterns anywhere in a string, but not splitting the string. This worked well for GPT-4 models, which seem to always send chunks that break cleanly on sentence boundaries. But other models don't necessarily do that. So we were sending The first word or even first word fragment through to the TTS service, playing havoc with prosody.
I also changed the `_push_tts_frames()` code so that we are not stripping whitespace from the beginning and end of each chunk we send to the TTS. That was fine when all TTS models were non-stateful invocations …

TTS sentence aggregation fix

---

examples/foundational/14-function-calling.py
src/pipecat/frames/frames.py
src/pipecat/processors/aggregators/openai_llm_context.py
src/pipecat/services/ai_services.py
src/pipecat/services/openai.py

The hard work was done here by @jeevan057
https://github.com/pipecat-ai/pipecat/pull/346#pullrequestreview-2336186908
I rebased, fixed one small bug, and modified the code from the original PR to use the newer context aggregator frames approach. I've tested this heavily.
There's one question in the comments of the `14-function-calling.py` example, but I don't think that should block a merge.

Handle parallel function calls for OpenAI LLMs

---

CHANGELOG.md
examples/foundational/07c-interruptible-deepgram.py
examples/foundational/07e-interruptible-playht.py
examples/foundational/07g-interruptible-openai-tts.py
examples/foundational/16-gpu-container-local-bot.py
src/pipecat/frames/frames.py
src/pipecat/services/ai_services.py
src/pipecat/services/anthropic.py
src/pipecat/services/aws.py
src/pipecat/services/azure.py
src/pipecat/services/cartesia.py
src/pipecat/services/deepgram.py
src/pipecat/services/elevenlabs.py
src/pipecat/services/gladia.py
src/pipecat/services/google.py
src/pipecat/services/lmnt.py
src/pipecat/services/openai.py
src/pipecat/services/playht.py
src/pipecat/services/together.py
src/pipecat/services/xtts.py

Hijacked this PR to make the change to simplify the service update settings. There's not a base class for service updates called `ServiceUpdateSettingsFrame`. There are subclasses for different service types: `LLMUpdateSettingsFrame`, `TTSUpdateSettingsFrame`, `STTUpdateSettingsFrame`.
When these frames are processed, there's an `_update_settings` handler in ai_services.py that is responsible for facilitating the update. For most values, this is a key lookup. There is special case handling for `model` and `voice` needed to ensure keys are mapped correctly.
For each service that has InputParams, those params are part of a `_settings` object which is updated by the `_update_settings` handlers.
This change simplifies maintaining settings updates for services. Going forward, the keys are to: …

Further consolidate service update settings into a single ServiceUpdateSettingsFrame class

---

CHANGELOG.md
src/pipecat/services/ai_services.py
src/pipecat/services/deepgram.py

This got lost in the settings update. Deepgram requires a disconnect/reconnect to change the language.

Deepgram: disconnect and reconnect on language change

---

CHANGELOG.md
pyproject.toml
src/pipecat/processors/text/markdown_remover.py

This one was a bit painful as there were a ton of edge cases to handle. Here's the gist:
This is a new processor intending to reside between the LLM and TTS services. It handles a TextFrame, modifies the text in the frame and then pushes the processed text into a TextFrame.
The goal was to make the spoke text work well both for the bot-llm-text and bot-tts-text methods. This logic accounts for both cases.
The processing involves:
- Stripping newlines and replacing with spaces, which can happen when Anthropic generates lists.
- Before markdown processing, preserve spacing and numbered lists, as converting to HTML will remove those.
- Processing the text with the `markdown` pages to convert the text to HTML. This standardizes the text into an easy to parse format. It also serves the purpose …

Add a new processor which removes markdown and special chars from TTS text

---

src/pipecat/transports/services/livekit.py

Updated to match Daily transport behavior:
- Use InputAudioRawFrame and OutputAudioRawFrame. This should make the transport compatible with #541 
- Makes sure that if the participant joins before the bot, it will still trigger `on_first_participant_joined`.

Update LiveKit audio transport for changes introduced in v0.0.42

---

src/pipecat/processors/aggregators/openai_llm_context.py

I am currently debugging workflows in Arabic. When I try to view LLM context it is difficult because:
* the unicode characters do not render properly
* the json is not prettified.
* We could pass in a custom formatter, but I figure because this is just debug logs for a relatively simple approach this would be sufficient.
There are other places in the codebase where we could do this but I wanted to start small as I am very very new to the codebase and contributing and want to get a lay of the land before I go any further.

Format and Support Unicode for LLM Message Debug Logs

---

src/pipecat/services/openai.py

This PR fixes a bug that caused garbled and/or repeated output when using parallel function calling with RTVI. Instead of requesting LLM inference when the final item of the function call list completes, we're now actually waiting for all of the function calls to complete (so they can be processed in parallel by the client).

Fixed parallel async function calls bug

---

examples/foundational/13b-deepgram-transcription.py
src/pipecat/services/deepgram.py

This code fixes the Deepgram service implementation so that this code works.
```
stt = DeepgramSTTService(
api_key=os.getenv("DEEPGRAM_API_KEY"),
live_options=LiveOptions(language=Language.FR),
)
```
Previously, this code resulted on transcription not working, because the Deepgram settings were overwritten with only the provided LiveOption values. Critical settings like `sample_rate` were overwritten as `None` rather than using appropriate default values for Pipecat.

fix for Deepgram settings not merging properly

---

CHANGELOG.md
src/pipecat/services/ai_services.py
src/pipecat/services/cartesia.py
src/pipecat/services/openai.py
src/pipecat/utils/text/base_text_filter.py
src/pipecat/utils/text/markdown_text_filter.py

Adds two new optional input parameters called `filter_code` and `filter_tables` to `MarkdownTextFilter`.
- When set to True, the code or tables text is passed through
- When set to False, any fenced code (delimited by ```) or tables will be filtered
The goal of this feature is to make it so that a bot can print out the entire text via bot-llm-text and omit speaking the entire code block or table.
Cartesia and OpenAI throw an error with empty text to speak. To satisfy their requirements, I've updated the services to output `text or " "`. I checked the other TTS services and none require it.
Also, in terms of timeliness, the removed text results in no delayed speech by the TTS. The text is read fluidly.

Add code and table filtering option to MarkdownTextFilter

---

README.md

We no longer download the model during first run - it's part of the repo.

Minor README update about Silero VAD.

---

CHANGELOG.md
src/pipecat/transports/services/daily.py

We queue transport messages and send them in a task to avoid potential hangs by sending urgent transport messages from a transport event handler.

transports(daily): send transport messages in a task

---

src/pipecat/utils/text/markdown_text_filter.py

More edge cases. When removing newlines, we need to replace with spaces so that text has spaces between sentences. This is required for Anthropic support.
But, this breaks table filtering, so we look for a specific pattern and remove it before HTML conversion so that table filtering works.

More edge case handling for text filtering

---

src/pipecat/transports/services/daily.py

This is a breaking change. RTVI 0.1.x will no longer get metrics data.

Comply with RTVI format for sending metrics data via Daily transport

---

src/pipecat/services/deepgram.py

`nova-2-convresationalai` model is designed for IVR bot transcription (legacy naming)
```
conversationalai: Optimized for use cases in which a human is talking to an automated bot, such as IVR, a voice assistant, or an automated kiosk.
```
See: [Docs](https://developers.deepgram.com/docs/model#nova-2)
`nova-2-general` is the best default model for high quality voice (> 8Khz)
`nova-2-phonecall` is the best default model for phonecall audio (eg Mulaw 8Khz or Linear16)

Update default Deepgram model

---

examples/canonical-metrics/README.md
examples/canonical-metrics/server.py
examples/chatbot-audio-recording/README.md
examples/chatbot-audio-recording/server.py
examples/deployment/flyio-example/README.md
examples/deployment/flyio-example/bot_runner.py
examples/moondream-chatbot/README.md
examples/moondream-chatbot/server.py
examples/patient-intake/README.md
examples/patient-intake/server.py
examples/simple-chatbot/README.md
examples/simple-chatbot/server.py
examples/storytelling-chatbot/frontend/components/App.tsx
examples/storytelling-chatbot/src/bot_runner.py
examples/translation-chatbot/README.md
examples/translation-chatbot/server.py
examples/twilio-chatbot/README.md
examples/twilio-chatbot/server.py

Before you had to read in the docs to go to /start, or /start_call or /start_bot. 
That isn't mentioned in the console output, isn't obvious, is inconsistent, and adds friction to learning the codebase.

Start agent/call/bot at localhost root

---

CHANGELOG.md
README.md
examples/foundational/07o-interruptible-assemblyai.py
examples/foundational/13c-gladia-transcription.py
examples/foundational/13d-assemblyai-transcription.py
pyproject.toml
src/pipecat/services/assemblyai.py

Adds a new `AssemblyAISTTService`, which is a websocket based implementation using the assemblyai client to transcribe audio.
Adds foundational examples for:
- `07o-interruptible-assemblyai.py`
- `13d-assemblyai-transcription.py`
Also, there was a transcription example missing for Gladia, so I added it: `13c-gladia-transcription.py`.

Add support for AssemblyAI STT

---

CHANGELOG.md
examples/foundational/07j-interruptible-gladia.py
src/pipecat/services/gladia.py

Gladia updated their API to v2. From their docs:
> The Real-time V2 STT API offers more features and improves significantly latencies over the V1.
Here's the migration guide: https://docs.gladia.io/chapters/live-stt/migration-from-v1#v2.
This PR applies changes from the migration guide.
It also adds a transcription example for testing: `13c-gladia-transcription.py`.

Update GladiaSTTService to use the Gladia V2 API

---

src/pipecat/vad/silero.py

SileroVAD is at processors.audio.vad, not just audio.vad, so making that fix.

Fix Silero VAD import issue

---

src/pipecat/services/openai.py

Grok is looking for `content: string` in the message for function calling. Without it, there's a fatal error. This PR adds a content param with an empty string. I've tested OpenAI, Together, Grok and all work well with this change.

Support function calling for Grok

---

src/pipecat/services/openai.py

Adding support for:
- `max_tokens`, which is deprecated by OpenAI but is used by many other OpenAI spec LLM providers
- `max_completion_tokens`, which is used by OpenAI

Add max_tokens and max_completion_tokens inputs for OpenAI

---

src/pipecat/services/assemblyai.py

AssemblyAI streaming only supports English. Also, there's no requirement to disconnect/reconnect on settings changes.

AssemblyAI: don't disconnect on language change

---

src/pipecat/services/cartesia.py
src/pipecat/services/elevenlabs.py

This is a pass that ensures that relevant initialization parameters are in the constructor. Specifically, the goal was to ensure the following values are available for initialization:
- voice (id, url, etc)
- model (if available)
- sample rate (and corresponding parameters related to the output format)
All services aligned expect for Cartesia and ElevenLabs.

Align TTSService constructors

---

src/pipecat/services/elevenlabs.py

Adding an output_format type, called ElevenLabsOutputFormat, to make the input more type safe.

Add ElevenLabs output format type

---

src/pipecat/services/openai.py

In the response handling code, `chunk.choices[0].delta` can be `None` for the last chunk in certain responses. Currently, the code attempts to access `chunk.choices[0].delta.tool_calls` directly without checking if `delta` is `None`. This results in an uncaught exception when `chunk.choices[0].delta` is `None`, causing an error:
> `'NoneType' object has no attribute 'tool_calls'`
This the solution to the issue raise by me #669

Fix uncaught exception when accessing 'tool_calls' in NoneType delta in response handling

---

src/pipecat/services/openai_realtime_beta/openai.py

This is mostly just for completeness, though it also could be useful for pipelines that want to switch on the fly between multiple LLM services.
To test, set `turn_detection` to `False` in the `openai_realtime_beta.SessionProperties`.
https://github.com/pipecat-ai/pipecat/blob/main/examples/foundational/19-openai-realtime-beta.py#L99

Support using Pipecat turn detection instead of OpenAI Realtime API turn detection

---

examples/foundational/23-bot-background-sound.py
src/pipecat/audio/mixers/soundfile_mixer.py

This allows a user to toggle looping audio when creating the mixer or dynamically with a control frame like this:
```
await task.queue_frame(MixerUpdateSettingsFrame({"sound": "ding", "loop": False}))
```
This allows users to trigger sound effects that aren't meant to be looped, e.g. a "ding" when a participant joins a call.
<div>
<a href="https://www.loom.com/share/2c921603bb72490cb5db1cf447501f61">
<p>Music and Sound Effects Demo 🎵 - Watch Video</p>
</a>
<a href="https://www.loom.com/share/2c921603bb72490cb5db1cf447501f61">
</a>
</div>

feat: toggle looping with soundfile mixer

---

examples/foundational/14b-function-calling-anthropic-video.py
examples/foundational/20c-persistent-context-anthropic.py
src/pipecat/services/anthropic.py

Anthropic function calling seems to have been partially broken by changes in frame ordering/timing. That's bad, in that it showed up some fragility in the function calling and context implementation. On the other hand, these changes make the Anthropic context management much closer to the OpenAI context management (I think).
We probably should merge this, but it does create more frequent overlapping audio. I will test this rebased on @aconchillo 's frame input queues branch. I'm hopeful that will fix the overlapping audio issue.
[edit]
Rebasing `aleix/input-queues-block-frames` on this one fixes the overlapping audio issues in the Anthropic function calling foundational examples.

fixes for anthropic function calling

---

CHANGELOG.md
src/pipecat/services/azure.py

- `AzureTTSService` now uses Azure websockets instead of HTTP requests.
- The previous `AzureTTSService` HTTP implementation is now
`AzureHttpTTSService`.
- Also, added an `AzureBaseTTSService` to avoid duplication.

Add an Azure TTS websocket service

---

src/pipecat/services/cartesia.py

The TTSStoppedFrame should be generated when the TTS services stoped generating audio not when the bot stops speaking.

services(cartesia): generated TTSStoppedFrame after no more audio

---

CHANGELOG.md
examples/foundational/07q-interruptible-rime.py
src/pipecat/services/rime.py

Adding Rime, a new TTS service. They only support HTTP interaction at the moment.

Add RimeHttpTTSService

---

CHANGELOG.md
src/pipecat/processors/frameworks/rtvi.py

This handles a new RTVIMessage of type `disconnect-bot`. This allows bot-to-human hand-over scenarios, while re-using the existing transport session. The RTVI Client counterpart can be found at https://github.com/pipecat-ai/rtvi-client-web/pull/76

add handler for disconnect-bot message

---

src/pipecat/transports/network/fastapi_websocket.py

The websocket is passed from outside (in the transport constructor) so we should not be trying to close it. FastAPI does actually close it later. We didn't see any issue because these functions were not implemented properly. The value to check was `application_state` instead of `client_state`. But in any case, Pipecat should not be responsible for closing things passed from outside.

transports(fastapi): don't try to close socket

---

CHANGELOG.md
src/pipecat/services/aws.py
src/pipecat/services/azure.py
src/pipecat/services/cartesia.py
src/pipecat/services/elevenlabs.py
src/pipecat/services/gladia.py
src/pipecat/services/google.py
src/pipecat/services/lmnt.py
src/pipecat/services/xtts.py
src/pipecat/transcriptions/language.py

Languages are typed as enum from the `Language` type. This results in being able to use supported languages for certain providers (e.g. Arabic for Azure) since the enum isn't support. This change:
- Expands the Language type to become a superset of all language codes
- Each service that sets a language specifies languages that the service supports
- For cases where a service takes only a 2 letter language code, we attempt to match the provided code to the two letter code. For example, if `Language.es_MX` is provided, then we'll attempt to match to `es` (not `es-MX`).

Make language support more robust

---

examples/foundational/07p-interruptible-google-audio-in.py
examples/foundational/14e-function-calling-gemini.py
src/pipecat/services/google.py

When pushing function call context we need to make sure not to add text content items that are empty.
I'm not sure if this is a regression that snuck into Pipecat code, or whether this is new model behavior we haven't seen before. But either way, this is a small but important check. (If we push an empty text content message, all inference requests subsequently fail.)
Also started testing with `gemini-exp-1114`. Text, audio, image, and function calling inference all work with no changes to the `GoogleLLMService`.

Empty text content bug fix for Gemini

---

CHANGELOG.md
src/pipecat/services/google.py

For Gemini, we're already using `_restructure_from_openai_messages` for initial messages and setting the context (`LLMMessagesUpdateFrame`). This PR also restructures the message when adding to the context (`LLMMessagesAppendFrame`).

Use Google Gemini message format when adding message to the LLM context

---

CHANGELOG.md
src/pipecat/transports/services/daily.py

This will allow capturing `screenVideo` or `camera`. This supersedes https://github.com/pipecat-ai/pipecat/pull/726.

transports(daily): subscribe to the desired video source

---

CHANGELOG.md
src/pipecat/transports/network/fastapi_websocket.py
src/pipecat/transports/network/websocket_server.py

This uses the frame serializer when interruptions happen which allows sending Twilio a `clear` message when using the `TwilioSerializer`. This already worked when using the FastAPI websocket transport but not this one.

transports(websockets): use frame serializers during interruptions

---

CHANGELOG.md
src/pipecat/transports/services/daily.py

This commit fixes an issue where we were not waiting for `asyncio.run_coroutine_threadsafe` to complete which can cause a series of undesired issues (e.g. not actually executing the coroutine).

transports(daily): use a task to execute callbacks

---

CHANGELOG.md
src/pipecat/transports/services/daily.py
src/pipecat/transports/services/livekit.py

Fixed a `DailyTransport` and `LiveKitTransport` issue where connections were being closed in the input transport prematurely. This was causing frames queued inside the pipeline being discarded.

transports: fix premature input transport closing

---

CHANGELOG.md
src/pipecat/audio/mixers/soundfile_mixer.py
src/pipecat/transports/network/fastapi_websocket.py
src/pipecat/transports/network/websocket_server.py

- `SoundfileMixer` doesn't resample input files anymore to avoid startup
delays. The sample rate of the provided sound files now need to match the
sample rate of the output transport.
- Fixed an issue in `WebsocketServerTransport` and `FastAPIWebsocketTransport`
that would cause a busy loop when using audio mixer.
Fixes #740

websocket transports mixer fixes

---

src/pipecat/processors/user_idle_processor.py

In response to issue https://github.com/pipecat-ai/pipecat/issues/741

Only run the UserIdleProcessor while pipeline is running

---

CHANGELOG.md
src/pipecat/transports/base_output.py

transports(base_output): wait for output tasks on EndFrame

---

examples/foundational/25-google-audio-in.py
src/pipecat/services/google.py

Two fixes to Google LLM service
1. We should be using `generate_content_async()` instead of `generate_content()`. This didn't matter very much for most pipelines, because services downstream from the LLM are waiting on output from the LLM. Only the initial inference request operation was not async. We were waiting on the streamed chunks asynchronously. But this does matter if we are trying to do things in a ParallelPipeline, for example.
2. We were overwriting any system instructions provided as constructor arguments with `None` if no system instructions were extracted from the context messages list.
This also includes a complete, commented example showing how to use Gemini Flash as a (quite reliable) transcriber.

Async Google LLM + Gemini Flash transcription example

---

src/pipecat/services/cartesia.py

Aligning with what Cartesia supports: https://docs.cartesia.ai/api-reference/tts/tts#send.Generation%20Request.language.
It seems they've added timestamp support for additional languages, too.
I think they may have an issue with non-[Latin script](https://en.wikipedia.org/wiki/Latin_script) characters.

Add additional languages for Cartesia

---

src/pipecat/services/cartesia.py

Currently, `cartesia.py` continues to receive messages even after an interruption has occurred. Although the following code:
```
async for message in self._get_websocket():
msg = json.loads(message)
if not msg or msg["context_id"] != self._context_id:
continue
```
prevents `TTSAudioRawFrame` from being pushed, Cartesia's server still generates audio messages. [This PR introduces a cancellation message](https://docs.cartesia.ai/api-reference/tts/working-with-web-sockets/contexts#cancelling-requests) to stop outgoing requests. However, there are two limitations:
> 1. It will only halt requests that have not begun generating a response yet.
> 2. Any currently generating request will continue sending responses until completion.

fix: Send interruption to cartesia

---

CHANGELOG.md
examples/websocket-server/index.html
src/pipecat/serializers/base_serializer.py
src/pipecat/serializers/livekit.py
src/pipecat/serializers/protobuf.py
src/pipecat/serializers/twilio.py
src/pipecat/transports/network/fastapi_websocket.py
src/pipecat/transports/network/websocket_server.py

Various websocket related improvements:
- Distinguish between Input and Output audio raw frames. We can't use AudioRawFrame anyremo (that's just a mixin).
- Allow FastAPIWebsocketTransport to work with binary data which allows using the protobuf serializer.
- Fixed examples/websocket-server to start sending audio only if connection is established
- Some minor cleanups.
Fixes #296

FastAPIWebsocketTransport: fix to work with text and binary

---

CHANGELOG.md
src/pipecat/pipeline/parallel_pipeline.py
src/pipecat/transports/services/daily.py

System frames need to be processed in the same task that they were generated. This makes them fast, immediate and frames that depend on this deterministic. This fixes an issue that was queuing system frames in ParallelPipeline making them run in a separate task.

 fix system frames parallel pipeline

---

src/pipecat/pipeline/parallel_pipeline.py

The other fix was not correct after all. We now do the following:
- Once ParallelPipeline receives a system frame it will create one task per internal pipeline. The internal pipeline will process the system frame in a single task (which is the newly created one).
- Once all the internal pipelines have processed the system frame we now push it downstream from the original task.

parallel_pipeline: fix system frames again

---

CHANGELOG.md
src/pipecat/frames/frames.py

Putting back transcriptions as text frames as before. We have a few examples that assume transcriptions are text frames.

frames: transcriptions should be TextFrames as before

---

examples/simple-chatbot/server/requirements.txt

The gemini example doesn't actually work from a fresh install, because the requirements.txt file doesn't include google :)

Update requirements.txt for simple-chatbot

---

CHANGELOG.md
src/pipecat/transports/base_output.py

Fixes a `BaseOutputTransport` issue that was causing non-audio frames being processed before the previous audio frames were played. This will allow, for example, sending a frame `A` (control or data) after a `TTSSpeakFrame` and the frame `A` will only be pushed downstream after the audio generated from `TTSSpeakFrame` has been spoken.
This finally fixes back `examples/foundational/05-sync-speech-and-image.py` even when using websocket-based TTS.

transport(output): fix non-audio frames sync after audio frames

---

src/pipecat/services/riva.py

riva: make sure we don't block on fastpitch

---

CHANGELOG.md
src/pipecat/transports/services/helpers/daily_rest.py

Someone in Discord mentioned being puzzled by the 5 min room expiration time. This exp time does seem to get in the way and is unexpected.
For now, I've removed the exp default, setting exp to `Optional` and a default of `None`. Alternatively, we could raise the value to a higher time, like 1 hr. That way rooms would be automatically deleted.
Also, added docstrings.

Remove default 5 min exp time for created rooms, add docstrings

---

dev-requirements.txt

I was testing a clean venv install of Pipecat and used dev-requirements.txt to set up my local env. I had to manually install python-dotenv. I'm adding it to dev-requirements.txt to avoid that manual step.

Add python-dotenv to dev-requirements.txt

---

CHANGELOG.md
pyproject.toml
src/pipecat/services/cartesia.py
src/pipecat/services/elevenlabs.py
src/pipecat/services/lmnt.py
src/pipecat/services/playht.py

This fix uses tenacity to implement limited retries with an exponential backoff for websocket-based TTS services.
Fixes #871

services: fix infinite websocket-bases TTS services retries

---

src/pipecat/transports/network/websocket_server.py
src/pipecat/transports/services/daily.py
src/pipecat/transports/services/livekit.py

This rollbacks a previous change https://github.com/pipecat-ai/pipecat/pull/855 which was trying to fix an issue in the wrong way.
The reasoning behind this fix is that the parent class might be sending audio or messages (through the subclass) and if we disconnect before all the data is sent we will run into incomplete audio or even errors. Therefore, we first make sure the parent tasks stop and then it will be safe to disconnect.

transports: call parent stop() before disconnecting

---

src/pipecat/processors/filters/frame_filter.py
src/pipecat/processors/filters/function_filter.py
src/pipecat/processors/filters/null_filter.py

`EndFrame`s are a special control frames that should always be handled to let the pipelines finish properly.

processors(filters): allow passing EndFrame

---

src/pipecat/services/elevenlabs.py

Set ElevenLabs TTS WebSocket endpoint to True for improved latency
- Enables the WebSocket endpoint to handle shorter audio chunks efficiently.
- Improves responsiveness by reducing latency for incoming agent messages.

feat: set auto_mode=true - ElevenLabs tts WSS

---

src/pipecat/transports/base_output.py

This avoid pushing `EndFrame` sooner than when it should be pushed. We have a `push_frame` in this function, previously we were checking for `EndFrame` after that `push_frame` but we should do it before.

transport(base output): avoid pushing EndFrame twice

---

CHANGELOG.md
src/pipecat/pipeline/parallel_pipeline.py

If we are sending an EndFrame and a ParallelPipeline has multiple pipelines we want to wait before pushing the EndFrame downstream until the slowest pipeline is finished. Otherwise, we could be disconnecting from the transport too early.

pipeline(parallel): wait for slowest endframe

---

CHANGELOG.md
src/pipecat/services/playht.py

Updating to support the latest Websocket API from PlayHT: https://docs.play.ht/reference/playht-tts-websocket-api. This new endpoint also appears to solve the missing audio issue where sentences wouldn't be spoken.
Service changes impacting this PR:
1. Websocket URL:
```
When you make a POST request to /api/v4/websocket-auth, you get back a response like this:
jsonCopy{
"websocket_urls": {
"Play3.0-mini": "wss://ws.fal.run/playht-fal/playht-tts/ws?fal_jwt_token=<token1>",
"PlayDialog": "wss://ws.fal.run/playht-fal/playht-tts-ldm/ws?fal_jwt_token=<token2>",
"PlayDialogMultilingual": "wss://ws.fal.run/playht-fal/playht-tts-multilingual-ldm/ws?fal_jwt_token=<token3>"
},
"expires_at": "2024-12-11T22:17:37.429Z"
}
```
We need to get the wss URL from the response.
2. Also, they now include …

Update PlayHT to use the latest Websocket connection endpoint

---

src/pipecat/transports/base_output.py

transports(base_output): fix duplicate push_frame()

---

examples/foundational/07d-interruptible-elevenlabs.py
examples/foundational/22d-natural-conversation-gemini-audio.py
src/pipecat/services/gemini_multimodal_live/gemini.py
src/pipecat/services/google.py

* Added direct setting of tools and tool_config to Gemini unary API.
* Fixed token usage counting for Gemini unary API
* Reworked Gemini native audio in natural conversation (smart turn detection) demo

Gemini unary API fixes and natural conversation demo

---

CHANGELOG.md

update CHANGELOG for 0.0.52

---

CHANGELOG.md
src/pipecat/services/openai_realtime_beta/openai.py

Previously, the code attempted to truncate audio responses based on wall clock time, which could exceed the actual audio duration and cause an error. Now, the code calculates actual audio duration from PCM parameters and uses the shorter of wall clock time or audio duration when truncating, preventing "invalid_request_error" responses from the API.

Fix truncation timing of OpenAIRealtimeBetaLLMService

---

CHANGELOG.md
src/pipecat/transports/services/helpers/daily_rest.py

This PR introduces the following updates to the `DailyRoomProperties` model:
1. **New Parameters Added**:
- `enable_prejoin_ui`: Enables or disables the pre-join UI for the room.
- `max_participants`: Specifies the maximum number of participants allowed in the room.
- `start_video_off`: Configures whether video is off by default when participants join.
2. **Default Values Updated**:
- `enable_prejoin_ui` is set to `True` by default.
- `start_video_off` is set to `False` by default.
3. **Documentation**:
- Updated the docstring to reflect the new parameters and their functionalities.
These changes provide enhanced configuration options for room properties, improving the flexibility of room management and participant behavior settings.
---
These updates are intended to:
- Improve usability …

adding more daily room params

---

CHANGELOG.md
src/pipecat/services/aws.py

Changed the Polly authentication params to be optional rather than required. Boto3 has a bunch of different methods of obtaining auth. Locally, it picks up my auth from AWS CLI and in production an IAM role is used. Obviously you can still use access keys, but this stops lint and IDE errors.

Changed Polly authentication params to be optional

---

CHANGELOG.md
examples/foundational/26d-gemini-multimodal-live-text.py
src/pipecat/services/gemini_multimodal_live/events.py
src/pipecat/services/gemini_multimodal_live/gemini.py

This pull request includes several changes to the `src/pipecat/services/gemini_multimodal_live` module, focusing on enhancing the configuration and handling of model responses, as well as improving the handling of events.
- Introduce text attribute in Part class for handling string data.
- Incorporate text processing in GeminiMultimodalLiveLLMService to push TextFrame if text is present.
Enhancements to model configuration and response handling:
* [`src/pipecat/services/gemini_multimodal_live/gemini.py`](diffhunk://#diff-89bd4e6ad85825b7d7a49eac0474c44dea1fc524a54fcd4ffba6a2542fa4b2f8R202-R223): Added a new `config` attribute in the `__init__` method to initialize model configuration with parameters such as frequency penalty, max tokens, presence penalty, temperature, top_k, top_p, …

feat(gemini): add text handling to GeminiMultimodalLive

---

CHANGELOG.md
src/pipecat/services/rime.py

The `set_voice` and `set_model_name` functions were missing, so `TTSUpdateSettingsFrame` weren't having an impact for Rime. This fixes that issue.

Add setters for model and voice to RimeHttpTTSService

---

src/pipecat/services/gemini_multimodal_live/gemini.py

Fixing GeminiMultimodalLiveLLMService function calling when using with pipecat-flows.

Fixing GeminiMultimodalLiveLLMService function calling to work with pipecat-flows

---

examples/foundational/21-tavus-layer.py
src/pipecat/services/tavus.py

We've received reports of the Tavus voice coming in in place of the TTS voice. The confusion was that people thought that a persona_id was required. It turns out that `pipecat0` should be used as the persona_id, which means a persona_id shouldn't be set by developers. This PR updates the example and adds a comment to clarify that. I'll also update the docs to clarify.

Update the Tavus example and comment about using the PERSONA_ID

---

src/pipecat/transports/services/livekit.py

Resolves https://github.com/pipecat-ai/pipecat/issues/958.
In LiveKit transport, when handling audio input, push audio frames only with `push_audio_frame()` and remove the additional call to `push_frame()`.
I noticed it was handled this way in other transports:
- in `DailyInputTransport` (only one call to `push_audio_frame()`) 
- in `FastApiWebsocketInputTransport`(push audio frames with `push_audio_frame()`, others with `push_frame()`)
- etc.

fix: push input audio frame only via push_audio_frame()

---

src/pipecat/services/ai_services.py

Exclude TranscriptionFrame from text frame processing in TTSService by updating the type check condition. This resolves unintended processing behavior when handling different frame types.
Discussion: https://discord.com/channels/1239284677165056021/1326894066775887963

fix(services): handle TranscriptionFrame separately in TTSService

---

examples/foundational/26d-gemini-multimodal-live-text.py

Just some minor changes to bring this in line with other examples.

Align 26d example with foundation norms

---

CHANGELOG.md
src/pipecat/frames/frames.py
src/pipecat/processors/aggregators/openai_llm_context.py
src/pipecat/services/anthropic.py
src/pipecat/services/google.py
src/pipecat/services/grok.py
src/pipecat/services/openai.py

This was motivated by the following Flows issue: https://github.com/pipecat-ai/pipecat-flows/issues/67
The issue is that two consecutive completions occurs in Flows: one for the function call completing and one for the subsequent node's message. This change adds the flexibility to defer the completion for a function call. For the Flows case, this will allow a completion to occur after both the function call and the node's message are added to the context.
This maintains backwards compatibility and attempts to avoid complexity. I'm open to suggestions of different ways to accomplish this. In my testing, this works for Flows and maintains backwards compatibility.

Add a means to optionally defer function call completion

---

examples/foundational/26e-gemini-multimodal-google-search.py

Example with Gemini using google search to retrieve news.

Example with Gemini using google search to retrieve news.

---

CHANGELOG.md
src/pipecat/services/cartesia.py
src/pipecat/services/elevenlabs.py
src/pipecat/services/lmnt.py
src/pipecat/services/playht.py
src/pipecat/services/websocket_service.py

The reconnection logic used by the websocket based TTS services had an issue—the retry countered wouldn't reset after a successful connection. That was pointed out in the following issue: https://github.com/pipecat-ai/pipecat/issues/471#issuecomment-2578931080. This is most likely to impact Cartesia, as it attempts to disconnect the websocket after 5 minutes of reactivity.
This change adds a new `WebsocketServer` base class used by TTS services. The logic contains retry logic used by all of the services.
In addition, the `LMNTTTSService` was refactored to use a websocket connection. This allows the `LMNTTTSService` to use the retry logic in the base class.
For the retry logic, I moved away from `tenacity` as it was reluctant to reset the counters. The state persisted across connections. …

Improve websocket based TTS service reconnection logic

---

CHANGELOG.md
src/pipecat/services/deepgram.py

This PR improves transcription speed and buffer management in `DeepgramSTTService` by triggering a `finalize` event when the Voice Activity Detection (VAD) identifies a `UserStoppedSpeakingFrame`. This ensures faster transcriptions and efficient clearing of the Deepgram audio buffer.
- Added logic to send the `finalize` event upon detecting a `UserStoppedSpeakingFrame`.
The `finalize` event signals the end of an audio stream, enabling immediate processing of audio data. This reduces latency and optimizes real-time transcription performance, as recommended in the [Deepgram documentation](https://developers.deepgram.com/docs/finalize).

finalize on DeepgramSTTService on VAD

---

dev-requirements.txt
examples/foundational/06-listen-and-respond.py
pyproject.toml
src/pipecat/services/cartesia.py
src/pipecat/services/lmnt.py
src/pipecat/services/playht.py

update dependencies (go back to numpy1)

---

examples/canonical-metrics/bot.py
src/pipecat/services/canonical.py

Updated the Canonical Metrics service to accept an `OpenAILLMContext` instance on the constructor. The metrics service uses this object to extract the messages to send them to Canonical along with the audio recording.
Updated the Canonical Metrics example to use stereo audio and pass in an instance of `OpenAILLMContext`.

Add transcript to Canonical Metrics Service

---

src/pipecat/services/ai_services.py

In testing, I've seen that both `TranscriptionFrames` and `InterimTranscription` frames will result in the TTS service generating speech. Instead, we only want the `LLMTextFrame` to generate speech. Updating the `TTSService` to reflect this.

TTSService should only process LLMTextFrames

---

src/pipecat/transports/base_input.py
src/pipecat/transports/local/audio.py
src/pipecat/transports/local/tk.py
src/pipecat/transports/services/daily.py

Explanation in comments. But basically, we don't need `max_workers` set to anything different than 1 since there's only a single task sending data to the thread, so only 1 thread needed.

transports: streamline max_workers for ThreadPoolExecutors

---

src/pipecat/services/ai_services.py

These were marked as `@abstractmethod`, but none of the subclasses implemented the methods. This causes an IDE error, which I'm resolving.

Remove @abstractmethod from set_model and set_model in TTSService class

---

CHANGELOG.md
src/pipecat/processors/idle_frame_processor.py
src/pipecat/processors/user_idle_processor.py

Fixed an issue where `IdleFrameProcessor` and `UserIdleProcessor` were getting initialized before the start of the pipeline, causing pre-mature events before time

fixing IdleFrameProcessor and UserIdleProcessor init logic

---

CHANGELOG.md
examples/foundational/31-heartbeats.py
src/pipecat/frames/frames.py
src/pipecat/pipeline/task.py
src/pipecat/processors/frame_processor.py

Introducing heartbeat frames. The pipeline task can now push periodic heartbeats down the pipeline when `enable_heartbeats=True`. Heartbeats are system frames that are supposed to make it all the way to the end of the pipeline. When a heartbeat frame is received the traversing time (i.e. the time it took to go through the whole pipeline) will be displayed (with TRACE logging) otherwise a warning will be shown.

introduce heartbeat frames

---

src/pipecat/pipeline/task.py
src/pipecat/pipeline/task_observer.py

Observers now process frames in separate tasks. This avoids blocking the pipeline while the observer is processing the frame.

task: add TaskObserver and avoid pipeline blocking

---

CHANGELOG.md
src/pipecat/services/deepgram.py

This PR updates the `DeepgramSTTService` to generate metrics using the pipeline Voice Activity Detection (VAD). This change enhances the service's ability to track and analyze speech activity more effectively.
- Modified `DeepgramSTTService` to utilize pipeline VAD for generating metrics.
I still feel metric definition of Services is off since they are not 100% accurate and SileroVAD generates better TTFB + Processing metric than `_on_speech_started`, there have been instances where `_on_speech_started` was triggered even when there was pin drop silence, leading to inaccurate data.

adding metric generation without deepgram VAD

---

src/pipecat/frames/frames.py
src/pipecat/serializers/twilio.py

Following the discord discussion on DTMF input, here is small feature PR that extends the Twilio serializer to read dtmf websocket messages sent by Twilio and generate InputDTMFFrame containing the corresponding value of KeypadEntry. I was not sure were to define KeypadEntry so I included it in frames.py for now.

Twilio serializer reading dtmf websocket messages

---

src/pipecat/transports/services/daily.py

This PR went stale: https://github.com/pipecat-ai/pipecat/pull/568. I'm doing clean up, so took a quick crack at it. @aconchillo is this along the lines of what you were thinking for the TODO?

Register the on_error handler

---

src/pipecat/services/gemini_multimodal_live/gemini.py

Add an early return in the _handle_transcribe_model_audio method to prevent unnecessary processing when the modalities setting is not set to audio. This change ensures that audio transcription only occurs when appropriate.
Also this was causing a problem on text modality since we don't have audio on buffer!

fix(gemini): prevent non-audio modality processing

---

CHANGELOG.md
examples/foundational/28a-transcription-processor-openai.py
examples/foundational/28b-transcript-processor-anthropic.py
examples/foundational/28c-transcription-processor-gemini.py
src/pipecat/processors/transcript_processor.py

The motivation for this change is that on sessions ending, if the bot was interrupted, the bot's output would not be captured. `TTSTextFrame`s provide more frequent updates reflecting what the bot said—either word-level or sentence-level. This ensures that the transcript captures more of the bot's output.
This results in more accurate transcripts that better reflect what was actually spoken, especially in cases of interruption or early session termination.
This is a breaking change as it requires different placement of the processor:
```
pipeline = Pipeline(
[
transport.input(),
stt,
transcript.user(),              # User transcripts
context_aggregator.user(),
llm,
tts,
transport.output(),
transcript.assistant_tts(),     # Assistant transcripts
context_aggregator.assistant(),
]
)
``` …

Modified `TranscriptProcessor` to use `TTSTextFrame`s

---

examples/foundational/31-gemini-grounding-metadata.py
src/pipecat/services/google/__init__.py
src/pipecat/services/google/frames.py
src/pipecat/services/google/google.py

Introduce support for extracting and processing grounding metadata from Google LLM responses.
Created an example using Google Search using GoogleLLMService.

Introduce support for extracting and processing grounding metadata from GoogleLLMService.

---

src/pipecat/transports/services/helpers/daily_rest.py

Two small things related to the Daily REST API helper:
- Fix type validation error by converting timestamp to integer before Pydantic validation
- Improve token parameter construction by using proper Pydantic model constructors instead of dict unpacking
This is clean up from a PR that was merged earlier today.

Small fixes to the Daily REST API helper

---

src/pipecat/utils/string.py
tests/test_utils_string.py

Enhance sentence splitting for Hindi TTS by recognizing ‘Danda’ (Unicode: ।) as the end-of-sentence marker.
Note: ‘Danda’ is distinct from the pipe symbol (|) and is a unique Unicode character. This update ensures efficient processing and splitting of Hindi text during TTS.
(venv) (base) vengadanathansrinivasan@vengadanathans-MacBook-Pro-2 pipecat-hi-fix % pytest tests/test_utils_string.py                                                
========================================================================= test session starts ==========================================================================
platform darwin -- Python 3.12.4, pytest-8.3.4, pluggy-1.5.0 -- /Users/vengadanathansrinivasan/miniconda3/bin/python
cachedir: .pytest_cache
rootdir: …

Adding hindi danda symbol as end of sentence marker

---

src/pipecat/services/elevenlabs.py

The docs aren't clear on this, but `eleven_multilinguagal_v2` doesn't support a language code. It detects the language on its own.

Remove eleven_multilinguagal_v2 from language code list

---

CHANGELOG.md
src/pipecat/services/openai_realtime_beta/openai.py

This came up in a Discord thread. I can't repro it, but I've added more try/except to attempt to more gracefully handle these issues.

Add better error handling for OpenAIRealtimeBetaLLMService truncate errors

---

CHANGELOG.md
src/pipecat/transports/services/daily.py

Currently, we can get events as soon as we join the signalling server but before `on_joined` is triggered. We now delay events after `on_joined` gets triggered to be more predictable.
Supersedes #1098 .

transports(daily): queue events until join completes

---

CHANGELOG.md
src/pipecat/services/elevenlabs.py

A potential cause of issues between pipecat and elevenlabs is having the default websocket max message size of 1mb, bumping up to match the maximum used on our end of 16mb

fix: elevenlabs tts increase websocket max message size limit to 16MB

---

CHANGELOG.md
src/pipecat/frames/frames.py

Added a `metadata` field to `Frame` which makes it possible to pass custom data to all frames.

frames: added metadata field to Frame class

---

CHANGELOG.md
src/pipecat/services/elevenlabs.py

I learned that the "v2" series of models are English only and don't accept language parameter. This change is updating to align to that fact. Also, I'm changing the default language to `None` so that ElevenLabs' defaults are used.

Improve ElevenLabs language checking logic

---

CHANGELOG.md
src/pipecat/pipeline/task_observer.py
src/pipecat/transports/network/websocket_client.py
src/pipecat/transports/network/websocket_server.py
src/pipecat/transports/services/daily.py

Just a new websocket transport client.

added new websocket client transport

---

CHANGELOG.md
src/pipecat/serializers/twilio.py

`TwilioSerializer` now supports transport message frames. With this we can create Twilio emulators.

serializers(twilio): handle transport message frames

---

CHANGELOG.md
examples/foundational/06-listen-and-respond.py
examples/foundational/22b-natural-conversation-proposal.py
examples/foundational/22c-natural-conversation-mixed-llms.py
examples/foundational/22d-natural-conversation-gemini-audio.py
examples/foundational/25-google-audio-in.py
src/pipecat/frames/frames.py
src/pipecat/pipeline/base_task.py
src/pipecat/pipeline/runner.py
src/pipecat/pipeline/sync_parallel_pipeline.py
src/pipecat/pipeline/task.py
src/pipecat/pipeline/task_observer.py
src/pipecat/processors/filters/stt_mute_filter.py
src/pipecat/processors/frame_processor.py
src/pipecat/processors/frameworks/rtvi.py
src/pipecat/processors/logger.py
src/pipecat/services/ai_services.py
src/pipecat/services/gladia.py
src/pipecat/tests/utils.py
src/pipecat/transports/base_output.py
src/pipecat/transports/base_transport.py
src/pipecat/transports/network/fastapi_websocket.py
src/pipecat/transports/network/websocket_client.py
src/pipecat/transports/network/websocket_server.py
src/pipecat/transports/services/daily.py
src/pipecat/transports/services/livekit.py
src/pipecat/utils/asyncio.py
src/pipecat/utils/utils.py
tests/test_pipeline.py

This replaces the current global task manager by a `TaskManager` per `PipelineTask`. This avoids having warnings about dangling tasks that have been created by a different `PipelineTask` that is still running.
Also, the `TaskManager` is passed through the `StartFrame`, so two things need to happen:
- Frame processors need to call `super().process_frame()`, otherwise things won't be initialized properly.
- If you want to use the `TaskManager` to create tasks you need to create tasks after `StartFrame` is processed.
It is now possible to specify the event loop a `PipelineTask` should run in. This allows complex applications where `PipelineTask`s can run in multiple threads.
Because we now support multiple threads, the global `obj_id()` and `obj_count()` functions now require a lock.

introduce TaskManager

---

CHANGELOG.md
src/pipecat/frames/frames.py

Added a DTMF frame along with an output frame. Output frames could be useful if we wanted to send DTMF. An example for this would be building a chat bot tester where they may have to go through a DTMF auto attendant.

Added: Additional DTMF frames

---

CHANGELOG.md
dev-requirements.txt
src/pipecat/frames/frames.py
src/pipecat/pipeline/task.py
src/pipecat/tests/utils.py
tests/test_aggregators.py
tests/test_filters.py
tests/test_pipeline.py

- Added a new `start_metadata` field to `PipelineParams`. The provided metadata will be set to the initial `StartFrame` being pushed form the `PipelineTask`.
- Improved Unit Test `run_test()` to use `PipelineTask` and `PipelineRunner`. There's now also some control around `StartFrame` and `EndFrame`. The `EndTaskFrame` has been removed since it doesn't seem necessary with this new approach.

pipeline task start metadata and unit test improvements

---

CHANGELOG.md
examples/canonical-metrics/bot.py
examples/chatbot-audio-recording/bot.py
examples/foundational/04-utterance-and-speech.py
examples/foundational/08-bots-arguing.py
examples/phone-chatbot/bot_daily.py
src/pipecat/serializers/telnyx.py
src/pipecat/serializers/twilio.py

We don't want to propagate the pipeline input/output sample rates into the serializers, instead we need to do that explicitly from the serializer constructor.
For example, `TwilioFrameSerializer` has `twilio_sample_rate` and `sample_rate`:
- The `twilio_sample_rate` inidicate the sample rate that Twilio will send and receive.
- The `sample_rate` indicates the sample rate of the input transport.
So if `twilio_sample_rate` is 8000 and `sample_rate` is 16000, one we receive audio from Twilio we will resample it to 16000. Then, through the pipeline we will work with 16000. At the end, the serializer will convert 16000 to 8000 which is what Twilio is expecting.

serializers: don't update twilio/telnyx sample rates

---

CHANGELOG.md
examples/foundational/32-gemini-grounding-metadata.py
examples/news-chatbot/server/news_bot.py
examples/simple-chatbot/server/bot-gemini.py
examples/simple-chatbot/server/bot-openai.py
src/pipecat/processors/frameworks/rtvi.py
src/pipecat/services/google/__init__.py
src/pipecat/services/google/rtvi.py

This is untested. But the idea is that you would use `GoogleRTVIObserver` instead of the `RTVIObserver`.
Fixes #1165

rtvi: separate specific google RTVI into a GoogleRTVIObserver

---

examples/foundational/28c-transcription-processor-gemini.py

Making the DB option one of the TranscriptHandlers you need to opt-in to for this example. This prevents `example.db` from being creating in your directory.

Update 28c option to output to log line only by default

---

CHANGELOG.md
examples/foundational/24-stt-mute-filter.py
src/pipecat/processors/filters/stt_mute_filter.py

The `STTMuteFilter` currently takes an `STTService` parameter but only uses it to check mute state. This is unnecessary coupling since the filter can manage this state internally.
This PR:
- Makes the `stt_service` parameter optional
- Adds a deprecation warning when the parameter is provided
- Implements internal mute state tracking
- Maintains full backwards compatibility
I've tested using the 24 example that this doesn't introduce a regression.

Deprecate stt_service parameter in STTMuteFilter

---

CHANGELOG.md
src/pipecat/services/elevenlabs.py
src/pipecat/services/websocket_service.py

Fixed an issue[#1192] in 11labs where we are trying to reconnect/disconnect the websocket connection even when the connection is already closed.

fixing disconnect issue

---

README.md

I had to install a new python version and recreate my venv. I realized that `pip install -e . ` was missing. Without it, you just end up using the latest build version. This lets you use the dev version from `main`. Also, cleaned up the steps while I was there.

Add missing pip install -e . step to the README, and clarify steps

---

CHANGELOG.md
src/pipecat/transports/base_output.py

This PR fixes an issue that was causing `BotStoppedSpeakingFrame` to be generated too late. This could then cause issues unblocking `STTMuteFilter` later than desired.

BaseOutputTransport: use specific VAD stop secs for the bot

---

CHANGELOG.md
src/pipecat/services/elevenlabs.py
src/pipecat/services/websocket_service.py

The websocket async iterator doesn't raise an exception when the server disconnects cleanly. We should handle that and raise an exception so we can reconnect.

WebsocketService: handle clean server disconnection

---

CHANGELOG.md
src/pipecat/services/google/google.py

Fixed an issue where `has_regular_messages` condition was always been true in `GoogleLLMContext` due to `Part` having `function_call` & `function_response` with `None` values.

fixing google llm service error

---

src/pipecat/processors/filters/stt_mute_filter.py

Now that we also suppress `InputAudioRawFrame` it's better to have this at trace level, otherwise it's too verbose. We already have the other mute/unmute messages.

STTMuteFilter: change suppressed logging to trace

---

examples/translation-chatbot/bot.py
examples/translation-chatbot/requirements.txt

Fixes the transcripts in the translation chatbot example.

docs: fix transcripts in translation chatbot example

---

CHANGELOG.md
src/pipecat/services/ai_services.py
src/pipecat/services/elevenlabs.py
src/pipecat/services/fish.py
src/pipecat/services/rime.py

`FishAudioTTSService` doesn't send a `TTSStoppedFrame`. THis is a websocket-based service which doesn't provide information on when the requested audio is complete. For these type of services we automatically send a `TTSStoppedFrame` if we haven't received audio after a while.

FishAudioTTSService should push TTSStoppedFrame

---

src/pipecat/transports/base_input.py

These logs are very verbose. They were added to try to find an issue that resulted in being because of low CPU/memory resources, but these logs were not helpful to determine that.

BaseInputTransport: remove VAD logging

---

CHANGELOG.md
src/pipecat/services/cartesia.py
src/pipecat/services/elevenlabs.py
src/pipecat/services/playht.py
src/pipecat/services/rime.py

- `RimeHttpTTSService` needs an `aiohttp.ClientSession` to be passed to the constructor as all the other HTTP-based services.
- `RimeHttpTTSService` doesn't use a default voice ID anymore.
Fixes https://github.com/pipecat-ai/pipecat/issues/1247

HTTP TTS services stopped frame

---

CHANGELOG.md
src/pipecat/processors/aggregators/llm_response.py
src/pipecat/services/anthropic.py
src/pipecat/services/google/google.py
src/pipecat/services/grok.py
src/pipecat/services/openai.py

You can have an LLM tool with the following prompt:
```
function={
"name": "get_current_weather",
"description": "Always tell the user you will check right away before getting the current weather",
```
This might generate text tokens and function call in the same turn. Currently, we are discarding the text and only handling the function call.

AssistantContextAggregator: append aggregation and tools in the same turn

---

CHANGELOG.md
src/pipecat/transports/network/fastapi_websocket.py

Fixed an issue where `EndTaskFrame` was not triggering `on_client_disconnected` or closing the WebSocket in FastAPI.

Fixed an issue where FastAPI was not triggering on_client_disconnected.

---

CHANGELOG.md
src/pipecat/processors/aggregators/llm_response.py

It turns out that in some cases we only get interim transcriptions (e.g. someone is speaking very very softly or someone is talking in the background). In those cases we don't want to interrupt the bot because there's really nothing to interrupt the bot for.
We originally thought we should interrupt the bot right at the time we got an interim frame, but this is causing too many false positives. It's actually better to simply wait for a real transcription before interrupting (in case VAD didn't interrupt).

LLMUserContextAggregator: don't reset timer with interim transcription

---

CHANGELOG.md
src/pipecat/services/anthropic.py

This is the new state of the art model from Anthropic. It supports normal completions by default (and thinking as an option, which I'm not including due to the token use and latency).

Update AnthropicLLMService to use claude-3-7-sonnet-20250219 by default

---

CHANGELOG.md
src/pipecat/services/ai_services.py
src/pipecat/services/cartesia.py
src/pipecat/services/elevenlabs.py
src/pipecat/services/fish.py
src/pipecat/services/lmnt.py
src/pipecat/services/playht.py
src/pipecat/services/rime.py
src/pipecat/services/websocket_service.py

@markbackman We already talked about this before. People are really hitting this issue, so even if not nice we need to support all TTS services as good as we can.
I did an optimization though. If the bot is not speaking and the user talks, we don't reconnect. We only reconnect if it's a real interruption.
Fixes https://github.com/pipecat-ai/pipecat/issues/1258

services: fix some TTS websocket service interruption handling

---

CHANGELOG.md
examples/instant-voice/server/src/single_bot.py
examples/news-chatbot/server/news_bot.py
examples/simple-chatbot/server/bot-gemini.py
examples/simple-chatbot/server/bot-openai.py
examples/translation-chatbot/bot.py
src/pipecat/pipeline/task.py
tests/test_pipeline.py

This change follows the same approach as passing a `clock`. It feels better to pass observers as a `PipelineTask` parameter.

PipelineTask: pass observers in contructor parameter

---

CHANGELOG.md
src/pipecat/frames/frames.py
src/pipecat/processors/frameworks/rtvi.py

@aconchillo this is what you requested in the other PR.

Rename ServerMessageFrame to RTVIServerMessageFrame and move to rtvi.py

---

.pre-commit-config.yaml

Instead of letting the actions fail due to formatting issue, we try to prematurely fix it via pre-commit hooks in a automated manner.

using ruff automated formatting to avoid action failures.

---

CHANGELOG.md
src/pipecat/services/anthropic.py
src/pipecat/services/gemini_multimodal_live/gemini.py
src/pipecat/services/google/google.py
src/pipecat/services/grok.py
src/pipecat/services/openai.py
src/pipecat/services/openai_realtime_beta/openai.py

Allow passing user (`user_kwargs`) and assistant (`assistant_kwargs`) context aggregator parameters when using `create_context_aggregator()`. The values are passed as a mapping that will then be converted to arguments.
Currently we only have a function `create_context_aggregator()` to create both objects and we need a way to be able to pass custom arguments to both aggregators. One option is to add each argument but we will have to remember to add them every time to each of the different implementations. Also, each parameter needs to be renamed with a prefix `user_` or `assistant_`. Instead, this PR uses a couple of dictionaries `user_kwargs` and `assistant_kwargs` that are then used as keyword arguments. This is also future proof since there's no need to explicitly add every argument, of …

LLMService: add user/assistant args to create_context_aggregator()

---

src/pipecat/transports/services/helpers/daily_rest.py

This is a pre-req for supporting the ["warm transfer" scenario with pipecat flows](https://github.com/pipecat-ai/pipecat-flows/pull/102).

Add the `permissions` property to `DailyMeetingTokenProperties`

---

examples/phone-chatbot/bot_daily_gemini.py

Updates example to:
- Switch pipelines
- Use different LLMs for voicemail detection / conversation
- Use audio in for VM detection and STT for conversation

Updated example to switch pipelines per the original request

---

CHANGELOG.md
examples/chatbot-audio-recording/bot.py
src/pipecat/processors/audio/audio_buffer_processor.py

This PR adds a couple of new events `on_user_turn_audio_data` and `on_bot_turn_audio_data` to be able to grab the audio of the user and bot on each turn.

add support for user and bot turn audio

---

CHANGELOG.md
src/pipecat/pipeline/task.py
tests/test_pipeline.py

Adds `on_source_frame` and `on_sink_frame` event handlers to `PipelineTask`. Those events will be called when a frame reaches the beginning or end of the pipeline respectively.

PipelineTask: add on_frame_reached_upstream and on_frame_reached_downstream

---

examples/foundational/07u-interruptible-ultravox.py
src/pipecat/services/ultravox.py

This PR creates a Ultravox service that runs a [Ultravox model](https://huggingface.co/fixie-ai/ultravox-v0_5-llama-3_1-8b) of your choice. This replaces the STT and LLM components with the Ultravox model giving great latency results! 
In order to run Ultravox you need to use a GPU (We recommend [Cerebrium](https://www.cerebrium.ai)) 
What was tested:
- End-to-end pipeline
- Metrics implementation to track TTFB
What was not tested:
- I am unsure of how the service scales based on concurrency limitations of the Ultravox model you select

Added ultravox service

---

examples/foundational/26-gemini-multimodal-live.py

We were mistakenly sending an initial messages frame as "assistant" (which translates to "model" in our context management code) to the Gemini Multimodal Live API. The back end seems to have gotten more strict and now expects that last message to be a "user" message.

fix for 26-gemini-multimodal-live.py

---

CHANGELOG.md
src/pipecat/pipeline/task.py
tests/test_pipeline.py

Because of https://github.com/pipecat-ai/pipecat/pull/1376 event handlers will now be tasks. This means that we would create a task for every frame receive downstream or upstream. Usually, audio frames make it all the way down and we don't really want to create a task for each audio frame.
Even before, without tasks, I don't think we really wanted to call event handlers because most of the time those frames would just be ignored.
So, we now force the user to specify which frames they are interested in.

PipelineTask: only call event handlers if a filter is matched

---

CHANGELOG.md
src/pipecat/services/ai_services.py
src/pipecat/utils/text/base_text_aggregator.py
src/pipecat/utils/text/simple_text_aggregator.py
tests/test_simple_text_aggregator.py

Added new `BaseTextAggregator`. Text aggregators are used by the TTS service to aggregate LLM tokens and decide when the aggregated text should be pushed to the TTS service. It also allows for the text to be manipulated while it's being aggregated.

introduce text aggregators

---

CHANGELOG.md
examples/foundational/34-audio-recording.py

I'm including an STT processor because the need for audio_passthrough=True isn't a clear requirement. Hoping that this example helps.

Update the 34-audio-recording.py example to include an STT processor

---

CHANGELOG.md
examples/foundational/35-pattern-pair-voice-switching.py
examples/foundational/35-voice-switching.py
src/pipecat/utils/text/pattern_pair_aggregator.py
tests/test_pattern_pair_aggregator.py

Extends the BaseTextAggregator with one that's aimed at:
- Removing text from the LLM output before it is provided to the TTS service
- Includes a handler to provide the content between the pattern pair, so that the content can be used to do things, like change voices, which I show in a demo

Add PatternPairAggregator

---

src/pipecat/services/tavus.py

Tavus supports audio at 24kHz; it makes sense to have the output sample rate be customizable instead of hardcoded to 16kHz.

Tavus support for custom output rate

---

CHANGELOG.md
examples/foundational/35-pattern-pair-voice-switching.py
examples/foundational/36-user-email-gathering.py
src/pipecat/services/ai_services.py
src/pipecat/services/cartesia.py
src/pipecat/services/rime.py
src/pipecat/utils/string.py
src/pipecat/utils/text/skip_tags_aggregator.py
tests/test_skip_tags_aggregator.py
tests/test_utils_string.py

This fixes and issue where emails are currently considered an end of sentence. It also add an example that uses Rime's `spell()` function to gather and confirm emails from the user.

add skip tags aggregator to support TTS service spelling out tags

---

CHANGELOG.md
src/pipecat/services/ai_services.py

STT services based on `SegmentedSTTService` were not passing through audio even if `audio_passthrough` was True. This was preventing audio recording from working.

SegmentedSTTService: allow audio to pass-through downstream

---

CHANGELOG.md
src/pipecat/pipeline/task.py
src/pipecat/tests/utils.py
tests/test_pipeline.py

This PR adds support for detecting idle pipelines. By default, if no activity has been detected during 5 minutes, the `PipelineTask` will be automatically cancelled. It is possible to override this behavior by passing `cancel_on_idle_timeout=False`. It is also possible to change the default timeout with `idle_timeout_secs`. Finally, a `on_idle_timeout` event handler will be triggered if the idle timeout is reached (whether the pipeline task is cancelled or not).

PipelineTask: automatically cancel tasks if pipeline is idle

---

src/pipecat/services/openai.py

This PR adds the `default_headers` argument to the `OpenAILLMService`.
Having the ability to use these headers is a requirement in our integration, i tried locally and it is forwarding the headers.
Let me know if it needs anything else.

feature: add custom headers to AsyncOpenAI

---

src/pipecat/processors/aggregators/openai_llm_context.py

Only checking the length if tools is a list.
This PR fixes https://github.com/pipecat-ai/pipecat/issues/1428

Only checking the length if tools is a list.

---

CHANGELOG.md
src/pipecat/frames/frames.py
src/pipecat/processors/aggregators/llm_response.py
src/pipecat/processors/frame_processor.py
src/pipecat/services/ai_services.py
src/pipecat/services/anthropic.py
src/pipecat/services/google/google.py
src/pipecat/services/openai.py
tests/test_context_aggregators.py

This is an issue that surfaced with Flows. The problem is that `on_context_updated` is executed in the internal Pipecat input queue task and if it blocks for whatever reason, the whole pipeline will block.
This is the PR that made it block https://github.com/pipecat-ai/pipecat-flows/pull/107

LLMAssistantContextAggregator: create a task to run on_context_updated

---

CHANGELOG.md
src/pipecat/services/openai.py

This PR brings two changes: 
While the env var `OPENAI_BASE_URL` is supported, that allows more granular configuration.
There is support for `instructions` in the realtime api, but not in the TTS service.
I used the client `extra_body` to achieve that, maybe we could also accept a whole `extra_body` parameter in OpenAITTSService, but this first draft is the minimum change necessary to get the instructions.

feature/support instructions in OpenAITTSService

---

CHANGELOG.md
src/pipecat/frames/frames.py
src/pipecat/processors/aggregators/llm_response.py
src/pipecat/services/ai_services.py
src/pipecat/transports/base_input.py

This PR fixes an issue with SegmentedTTSServices. These services use VAD events to send audio to the services. The problem is that we can also generate emulated VAD events and those should be ignored.

segmented tts ignore emulated frames

---

CHANGELOG.md
src/pipecat/services/google/google.py

Fixes https://github.com/pipecat-ai/pipecat/issues/1454
We mistakenly did yielded a `TTSStoppedFrame` in both the `run_tts` `try` block and the `finally` block. Now, it's just emitted in the `finally` block.

Fix: GoogleTTSService was emitting two TTSStoppedFrames

---

src/pipecat/services/deepgram.py

Previously, DeepgramTTS service was sending a `TTSStoppedFrame` frame right after a `TTSAudioRawFrame`, which caused choppiness in the audio sent to the Tavus room. This (along with a reduction in the batch size) resolves the issue

Tavus / Deepgram TTS compatibility

---

pyproject.toml
src/pipecat/services/whisper.py

This pull request introduces support for MLX Whisper models in the `pipecat` project. The changes include adding dependencies, importing necessary modules, defining new model classes, and creating a new service class for MLX Whisper. This class provides an option for Apple Silicon M-series to utilize the Metal GPU for local inference of MLX converted Whisper models.
Key changes:
* Added `mlx-whisper~=0.4.2` to the dependencies in `pyproject.toml`.
* Included `typing_extensions` for `TYPE_CHECKING` and `override` in `src/pipecat/services/whisper.py`.
* Added conditional import for `mlx_whisper` within `TYPE_CHECKING` to handle missing module errors gracefully.
* Introduced `MLXModel` class to define various MLX Whisper model options.
* Created `WhisperSTTServiceMLX` class as a subclass of …

Added Support for MLX Whisper models on Apple M-Series

---

CHANGELOG.md
examples/foundational/07j-interruptible-gladia.py
src/pipecat/services/gladia.py
src/pipecat/services/gladia/__init__.py
src/pipecat/services/gladia/config.py
src/pipecat/services/gladia/stt.py

Also, reorganize this service into multiple files. I think this is a direction we should generally be going.
Two deprecations in this change for which I have warnings for both:
1. With the new config params, `language` is superseded by a `language_config`
2. Rather than use a nested InputParams, I'm suggesting that we align (or at least consider) moving the InputParams outside of the main class. This makes using it more expected.
e.g.
Before:
```
from pipecat.services.gladia import GladiaSTTService, LanguageConfig
stt = GladiaSTTService(
api_key=os.getenv("GLADIA_API_KEY"),
params=GladiaSTTService.InputParams(
language_config=LanguageConfig(
languages=[Language.EN],
)
),
)
```
After:
```
from pipecat.services.gladia import GladiaInputParams, GladiaSTTService, LanguageConfig
stt = …
```

Refactor GladiaSTTService to support addition params

---

examples/p2p-webrtc/video-transform/client/typescript/src/style.css
src/pipecat/transports/network/small_webrtc.py

SmallWebRTCTransport: Improvements to work with mobile
- Adding support to `yuvj420p` which is the format that we receive from mobile iOS.
- Improvements on the video transform example to work on mobile.

SmallWebRTCTransport: Improvements to work with mobile

---

CHANGELOG.md
src/pipecat/processors/transcript_processor.py
tests/test_context_aggregators.py
tests/test_transcript_processor.py

This makes sure `TranscriptionUpdateFrame` is never discarded when there's an interruption.

TranscriptProcessor: send TranscriptionUpdateFrame after interruption

---

CHANGELOG.md
src/pipecat/transports/base_output.py
src/pipecat/transports/base_transport.py

This allows modifying the default 20ms audio chunks. I've seen people having issues with websockets and 20ms. I believe we should probably also change the default for FastAPI to 40ms. For now, this gives the option to the user to change it.

BaseOutputTransport: allow setting 10ms output audio chunks

---

CHANGELOG.md
src/pipecat/transports/base_output.py

Sending frames every 20ms has a performance hit. With this change we push BotSpeakingFrame every 200ms, or at every chunk size as before if the chunk size is greater than 200ms (now that it will be configurable).

BaseOutputTransport: optimize BotSpeakingFrames

---

CHANGELOG.md
src/pipecat/transports/network/fastapi_websocket.py
src/pipecat/transports/network/websocket_client.py

This PR fixes a `FastAPIWebsocketTransport` and `WebsocketClientTransport` issue that would cause the transport to be closed prematurely, preventing the internally queued audio to be sent. The same issue could also cause an infinite loop while using an output mixer and when sending an `EndFrame`, preventing the bot to finish.
The reason is that as soon as we got an `EndFrame` in the input transport we were causing the websocket. Instead, if the pipeline also has an output transport we should wait for the output transport to finish.

transports(websocket): close connection from last transport

---

CHANGELOG.md
src/pipecat/processors/aggregators/llm_response.py

In testing the STTMuteFilter with GeminiMultimodalLiveLLMService, I found that the STTMuteFilter would not unmute after the bot stopped speaking. In tracking it down, it appears that the `LLMAssistantContextAggregator` handles the BotStoppedSpeakingFrame but does not push the frame.
This resolves the issue, but I'm not sure if the frame wasn't pushed for a reason.

LLMAssistantContextAggregator should push BotStoppedSpeakingFrames

---

examples/phone-chatbot/call_transfer.py
examples/phone-chatbot/simple_dialin.py
examples/phone-chatbot/simple_dialout.py
examples/phone-chatbot/voicemail_detection.py

Pipecat 0.62 updates the imports. It didnt break the example, but this makes the examples more in line with expected imports.

Updated imports to work with pipecat 0.62

---

CHANGELOG.md
src/pipecat/processors/consumer_processor.py
src/pipecat/processors/producer_processor.py
tests/test_producer_consumer.py

These processors can be used for advanced uses cases. One example is to send frames from one branch of a `ParallelPipeline` to another branch.

processors: add ProducerProcessor and ConsumerProcessor

---

CHANGELOG.md
examples/p2p-webrtc/video-transform/client/typescript/vite.config.js
pyproject.toml
src/pipecat/transports/network/webrtc_connection.py

Improvements for the SmallWebRTCTransport:
- Wait until the pipeline is ready before triggering the connected event
- Queuing the messages if the data channel is not ready.
- Updating aiortc to fix an issue where 'video/rtx' MIMEType retransmission incorrectly handled as a codec
- Discarding old frames to avoid initial video delays.

Improvements for the SmallWebRTCTransport

---

src/pipecat/services/cartesia/tts.py
src/pipecat/services/openai/tts.py
src/pipecat/services/tts_service.py

Most TTS services don't like messages with empty text. This change centralizes the logic in TTSService to only generate audio from text when there is text.

TTS: Skip generation when there is no text

---

src/pipecat/transports/base_output.py

In testing with GeminiMultimodalLiveLLMService, I see cases where the speech can take upwards of 0.31 to 0.32 seconds between speech. We want to avoid BotStoppedSpeakingFrame getting emitted when the bot is going to speak again right away. We also want the stopped speaking frame to come relatively soon after the bot stops speaking. For this reason, I'm nudging the value up ever so slightly.

Increase BOT_VAD_STOP_SECS for services with slower speech patterns

---

src/pipecat/services/gemini_multimodal_live/gemini.py

- Changed the default model for gemini multimodal live LLM service because the model is no longer available and a new preview model has been released with billing for live API.
- The people using the current version of pipecat 0.0.62 are facing the below error as this PR changes(#1545) has not been released yet
```
2025-04-10 11:35:13.520 | ERROR    | pipecat.services.gemini_multimodal_live.gemini:_connect:454 - GeminiMultimodalLiveLLMService#0 initialization error: server rejected WebSocket connection: HTTP 404
```
- **Impact**: This update ensures compatibility with the latest Gemini Multimodal Live LLM service, resolving the WebSocket connection errors and restoring full functionality to Pipecat users.​
- Requesting the team to release the changes as a **HOTFIX**.

feat: change default model name on live api

---

CHANGELOG.md
src/pipecat/services/cartesia/tts.py

The context now reflects:
```
{"role": "assistant", "content": "Just to confirm, is your email <sp>first.lastname@gmail.com</sp>?"}
```
Assuming the `<sp>` tags are OK in the context, then this is good to go. If not, we can figure out what to do.

Fix: Cartesia's spelling feature adds whole word to context

---

CHANGELOG.md
src/pipecat/transports/network/webrtc_connection.py

Fixed an issue in `SmallWebRTCTransport` where an error was thrown if the client did not create a video transceiver.

Fixed an issue in `SmallWebRTCTransport`

---

CHANGELOG.md
src/pipecat/services/elevenlabs/tts.py

From 11Labs docs on previous_text:
```
The text that came before the text of the current request. Can be used to improve the speech’s continuity when concatenating together multiple generations or to influence the speech’s continuity in the current generation.
```
For HTTP requests, this parameter provides continuity between HTTP responses. We're passing in previous sentences from the bot's current turn.

Add previous_text context to ElevenLabsHttpTTSService

---

CHANGELOG.md
src/pipecat/services/elevenlabs/tts.py

This adds word/timestamp pairs to the ElevenLabsHttpTTSService. As part of the change, we're using a new API. Per docs:
```
Converts text into speech using a voice of your choice and returns a stream of JSONs containing audio as a base64 encoded string together with information on when which character was spoken.
```
This requires different audio processing as well.
With this change, ElevenLabsHttpTTSService becomes a WordTTSService, as it's still HTTP based, but it now includes word / timestamp data.
I've tested the word timing using simple-chatbot and this implementation works well!

Added word/timestamp pairs to ElevenLabsHttpTTSService

---

src/pipecat/services/google/llm_vertex.py
src/pipecat/services/google/stt.py
src/pipecat/services/google/tts.py

This PR adds support for Application Default Credentials (ADC) in Google service implementations (Vertex LLM, Speech-to-Text, and Text-to-Speech). Previously, these services required explicitly providing service account credentials either as a JSON string or file path.
While this approach works, it's not ideal in situations where IAM service accounts are configured at the environment level. This change enables more secure and flexible authentication patterns, especially in production environments:
- GCP environments: Automatically uses the attached service account
- Local development: Uses credentials from `gcloud auth login`
I welcome all feedback, and look forward to contributing more to pipecat!

Enable usage of Application Default Credentials in Google services

---

CHANGELOG.md
src/pipecat/services/grok/llm.py

GrokLLMService uses grok-3-beta as default model

---

CHANGELOG.md
examples/telnyx-chatbot/README.md
examples/telnyx-chatbot/bot.py
examples/telnyx-chatbot/server.py
src/pipecat/serializers/telnyx.py
src/pipecat/serializers/twilio.py

Adding the auto hang up option to Telnyx to match the Twilio Serializer.
Also:
- Adding logic to only send the command once—both for Telnyx and Twilio
- Making the Twilio call_sid optional, as this was breaking 😞 
- Improving the telnyx-chatbot README to make it easier for anyone who hasn't worked with Telnyx before
- Updated telnyx-chatbot example to provide the required inputs

Add auto_hang_up to Telnyx serializer

---

CHANGELOG.md
src/pipecat/services/gladia/stt.py

Gladia's websocket connection drops after 30 seconds of no input. This adds a keepalive task to send blank audio every 20 seconds.

Add a keepalive task to GladiaSTTService

---

CHANGELOG.md
src/pipecat/audio/vad/vad_analyzer.py
src/pipecat/frames/frames.py
src/pipecat/transports/base_input.py

As the CHANGELOG points out, this helps to differentiate from user started/stopped speaking frames in the case where smart turn detection is used.
One thing I didn't add but considered was the speaking duration to the stopped frame. It would be easy to handle in the application code, but we could consider making things easier by adding it here. I'm indifferent.
---
Implementation-wise, I followed the same pattern we used for the smart turn analyzer frames.

Add VADUserStartedSpeakingFrame and VADUserStoppedSpeakingFrame

---

docs/api/conf.py
docs/api/requirements.txt

We had some very slow packages to build:
- moondream
- riva
- livekit
- langchain
- coreml
Instead of using the packages, we'll just mock the imports to resolve build failures and speed up docs generation time.

Additional import mocks to fix docs failure

---

CHANGELOG.md
src/pipecat/services/gemini_multimodal_live/events.py
src/pipecat/services/gemini_multimodal_live/gemini.py

Without this, the Gemini API will disconnect the session once the context limit is hit. From Google's docs:
> Session duration can be extended to unlimited by enabling session [compression](https://ai.google.dev/gemini-api/docs/live#context-window-compression). Without compression, audio-only sessions are limited to 15 minutes, and audio plus video sessions are limited to 2 minutes. Exceeding these limits without compression will terminate the connection.
Source: https://ai.google.dev/gemini-api/docs/live#maximum-session-duration

Add context_window_compression support to GeminiMultimodalLiveLLMService

---

src/pipecat/processors/frameworks/rtvi.py

This allows you to select what `RTVIObserver` will send. Some users don't want metrics for example.

RTVIObserver: add RTVIObserverParams to configure what to send

---

src/pipecat/services/rime/tts.py

**Issue**: Pipecat users are sending websocket requests to a (now) deprecated url, `users-ws.rime.ai`, which will not reflect upgrades to the Rime ws api.
Rime has migrated their Websockets api to the base url `user.rime.ai` along with all other tts endpoints. 
The [docs](https://docs.rime.ai/api-reference/endpoint/websockets) have been updated as well to reflect this.

[Rime] - Update url for Websockets API

---

src/pipecat/services/riva/tts.py

param key names were updated:
https://github.com/nvidia-riva/python-clients/commit/91138c3f66957a2c119e761294ac3e3e3423bb8e#diff-ece228577b1d233ce600a948243f90cece53e3a9b89554a0b27a48bc4d6e0fdfR45

Riva TTS: update FastPitch params

---

src/pipecat/services/rime/tts.py

Adding the following params to the RimeTTSService params, which are supported by the rime websockets api: 
* [pauseBetweenBrackets](https://docs.rime.ai/api-reference/endpoint/websockets-json#param-pause-between-brackets)
* [phonemizeBetweenBrackets](https://docs.rime.ai/api-reference/endpoint/websockets-json#param-phonemize-between-brackets)
We json serialize the bool values as the rime api currently expects `true/false`, and is case-sensitive (patch to rime ws backend incoming)

[Rime] Add new params to RimeTTSService

---

src/pipecat/transports/base_output.py

We also use the audio task to also send synchronized images with audio.

BaseOutputTransport: always initialize audio task

---

CHANGELOG.md
examples/foundational/07q-interruptible-rime-http.py
src/pipecat/services/rime/tts.py

Add "Accept: audio/wav" hard-coding for Rime's new Arcana model, and strip wav header if necessary.

support for rime arcana model

---

src/pipecat/services/ultravox/stt.py

Currently, the `.strip()` removes any spacing in the text frames, as a result, the STT service reads everything as one word.

[Fix] Ultravox frame spacing issue

---

CHANGELOG.md
src/pipecat/pipeline/task.py
src/pipecat/utils/asyncio.py

A couple of changes:
- If for some reason Pipeline task is cancelled from outside Pipecat we were not cleaning up things properly.
- Also, we use a dictionary instead of a set of tasks. For some reason we were having issues and dangling tasks were being reported after being removed from the set. Anyways, using a dictionary fixes the issue.

task manager dictionary and cleanup PipelineTask

---

CHANGELOG.md
src/pipecat/transports/services/daily.py

Added `on_active_speaker_changed` event handler to the `DailyTransport` class.
My personal use-case for this is simple; as long as we're missing out on the `user_id` for the transcription- and translation frames from the gladia service. A "guesstimate" on the person is still better then an empty string user_id.
This will allow some custom mapping of our own processing the frames. Might be of use to someone else as well.

DailyTransport: added on_active_speaker_changed event handler

---

src/pipecat/processors/frameworks/rtvi.py

This PR is a fix for issue #1734 
[In this previous PR](https://github.com/pipecat-ai/pipecat/pull/1667/files#diff-ae622e884761fa9fb9db374ec23206c76e1d2919a8eac9029becfe8893a75837L254) we introduced a breaking change for RTVI clients by changing the "args" in the message sent to "arguments".  This PR reverts back to using "args"

Revert breaking change in RTVI protocol for function calling

---

CHANGELOG.md
examples/foundational/30-observer.py
src/pipecat/observers/loggers/debug_log_observer.py
src/pipecat/observers/loggers/llm_log_observer.py
src/pipecat/observers/loggers/transcription_log_observer.py

The goal here is to add an observer class that makes it easy to filter on specific frames and optionally their source and destination. Basically, I got sick of writing a custom observer for debugging. This gives me more immediate access to seeing logs that I want by just specifying it directly in the observers arg in PipelineParams.

Add DebugLogObserver

---

src/pipecat/services/ai_services.py

fix: correct deprecation warning in ai_services module
The deprecation warning generated when importing `ai_services` appears to be incorrect.
```
DeprecationWarning: Module `pipecat.services.ai_services` is deprecated, use `pipecat.services.ai_service.[image_service,llm_service,stt_service,tts_service,vision_service]` instead.
from pipecat.services.ai_services import InterruptibleTTSService
```
This should be:
```
DeprecationWarning: Module `pipecat.services.ai_services` is deprecated, use `pipecat.services.[ai_service,image_service,llm_service,stt_service,tts_service,vision_service]` instead.
from pipecat.services.ai_services import InterruptibleTTSService
```

Wrong deprecation warning when importing ai_services.py

---

src/pipecat/services/deepgram/tts.py

Change `DeepgramTTSService` to use the `stream_raw()` function in the Deepgram Python library, so that we can stream the audio bytes.

Fix Deepgram TTS streaming

---

CHANGELOG.md
src/pipecat/frames/frames.py
src/pipecat/pipeline/parallel_pipeline.py
src/pipecat/pipeline/pipeline.py
src/pipecat/pipeline/sync_parallel_pipeline.py
src/pipecat/pipeline/task.py
src/pipecat/processors/frame_processor.py
src/pipecat/processors/frameworks/rtvi.py
src/pipecat/transports/network/webrtc_connection.py
src/pipecat/transports/services/daily.py
src/pipecat/transports/services/livekit.py

This PR introduces `FrameProcessor.setup()`. This allows setting up processors before `StartFrame` is being pushed. One of the problems we had is that we relied on `StartFrame` to initialize things, however you might want to start some tasks even before receiving `StartFrame` (e.g. to even handle `StartFrame`). So, `FrameProcessor.setup()` allows you to do that. There are things that I have moved from `StartFrame` to `FrameProcessorSetup`, for example, the clock, the system manager and the observer. Having the task manager allows you to create Pipecat controlled task even before receiving the `StartFrame`.
Also, we have all seen the annoying message:
```
XXXX not properly initialized, missing super().process_frame(frame, direction)
```
It doesn't give much information and we don't really …

introduce frame processors setup

---

src/pipecat/utils/tracing/class_decorators.py
src/pipecat/utils/tracing/conversation_context_provider.py
src/pipecat/utils/tracing/service_attributes.py
src/pipecat/utils/tracing/service_decorators.py
src/pipecat/utils/tracing/turn_context_provider.py
src/pipecat/utils/tracing/turn_trace_observer.py
test-requirements.txt

Fixing an issue I introduced by merging the OTel tracing feature.
Clarifying about the change since it came up in comments:
```
The fix to the runtime error is using string literals for the OTel types.
Adding TYPE_CHECKING helps IDEs better understand what the string literal types correspond to.
```

Fix: Resolve an issue where tracing imports were required

---

CHANGELOG.md
src/pipecat/pipeline/task.py
tests/test_pipeline.py

New pipeline task events to know when a pipeline is started, stopped, ended or cancelled. They will all be triggered when the corresponding frames reach the end of the pipeline.

PipelineTask: add new started/stopped/ended/cancelled events

---

src/pipecat/utils/tracing/turn_trace_observer.py

With this change, the span name will be either `conversation` for the top-level span and `turn` for the child span. Then, each of those spans will have an attribute:
- `conversation.id` for the conversation ID
- `turn.number` for the turn number

Keep span identifiers in attributes only

---

src/pipecat/services/mcp_service.py

fix typo in mcp service to only append tool results from tool call.
closes #1855

mcp: fix typo in tool call response

---

CHANGELOG.md
src/pipecat/pipeline/task.py
src/pipecat/pipeline/task_observer.py
tests/test_pipeline.py

This allows adding observers after task creation. This can be useful in cases where the task is passed around after being created and you still need would like to add more observers.

PipelineTask: add add_observer()

---

src/pipecat/utils/tracing/service_attributes.py
src/pipecat/utils/tracing/service_decorators.py

This change does a few things:
- Keeps the service span to just common names like `stt`, `llm`, or `tts`. This is a change from including the service name in the service type. This is to align with the change where span names don't include identifiers
- Related, change `service.name` to just `service` as there is nothing else nested
- Remove service type identifiers from from attribute names like `metrics.tts.character_count`
- Follow the OTel naming recommendations from Langfuse: https://langfuse.com/docs/opentelemetry/get-started#property-mapping. The only change I'm making is for llm tokens. This will allow them to revert these changes: https://github.com/langfuse/langfuse/pull/6903/files.

Update OTel attribute names

---

CHANGELOG.md
examples/foundational/21-tavus-layer-tavus-transport.py
examples/foundational/21a-tavus-layer-small-webrtc.py
examples/foundational/21b-tavus-layer-daily-transport.py
examples/foundational/README.md
src/pipecat/services/tavus/video.py
src/pipecat/transports/network/webrtc_connection.py
src/pipecat/transports/services/tavus.py

This PR brings some improvements to use Tavus inside Pipecat.
Refactored the `TavusVideoService`, so it acts like a proxy, sending audio to Tavus and receiving both audio and video.
This will make `TavusVideoService` usable with any Pipecat pipeline and with any transport.
Currently, the Tavus Avatar, the Pipecat Bot, and the User all join the same Tavus provided room. With this refactor, audio and video will be routed through Pipecat, this means we are going to have two Daily rooms:
- Tavus room: Tavus Avatar + Pipecat Bot
- User room: Pipecat Bot + User
Can be used with any Pipecat pipeline.
The Pipecat bot it is connecting in the same room as the Tavus Avatar and the Bot.

Tavus improvements

---

src/pipecat/utils/tracing/service_attributes.py
src/pipecat/utils/tracing/service_decorators.py

This adds tracing to the push_frame method in the LLM's _process_context. The idea is, for `LLMTextFrame`s that are pushed, aggregate the text for a given chat completion. Then, restore the original push_frame method and add the aggregated output as a span attribute.

Add LLM response tracing to OTel tracing

---

examples/foundational/41-text-only-webrtc.py
examples/foundational/41a-text-only-webrtc.py
examples/foundational/41b-text-and-audio-webrtc.py

Text only chat bot example using small webrtc transport (_not_ Daily) and RTVI.  
~TODO: add `text_enabled` to transport params to guide UI on whether or not to display chat input.~
Used a `RTVIServerMessageFrame` to update the UI.
Requires: https://github.com/pipecat-ai/small-webrtc-prebuilt/pull/9
Test with pipecat example [here](https://github.com/pipecat-ai/pipecat/pull/1804).

add text chatbot example using small webrtc transport

---

src/pipecat/services/deepgram/stt.py

I am working with Pipecat 0.0.68 and I enabled the new telemetry config. I noticed that the model is not set for Deepgram STT (see `gen_ai.request.model`):
```json
{
"gen_ai.operation.name": "stt",
"gen_ai.request.model": "",
"gen_ai.system": "deepgram",
"is_final": true,
"metrics.ttfb_ms": 0.0025191307067871094,
"settings.channels": 1,
"settings.encoding": "linear16",
"settings.interim_results": true,
"settings.language": "es-mx",
"settings.model": "nova-2",
"settings.profanity_filter": true,
"settings.punctuate": true,
"settings.sample_rate": 8000,
"settings.smart_format": true,
"settings.vad_events": false,
"transcript": "Sí, sí.",
"vad_enabled": false
}
```

fix(deepgram-stt): set model name to Deepgram STT

---

CHANGELOG.md
src/pipecat/frames/frames.py
src/pipecat/transports/base_output.py
src/pipecat/transports/services/daily.py

It is now possible to handle DTMF keypress in the output transport. For example, the DailyTransport has support for DTMF and it is now possible to send DTMF by just pushing DTMF frames.

output transport can now handle DTMF keypress

---

src/pipecat/processors/metrics/frame_processor_metrics.py
src/pipecat/utils/tracing/service_attributes.py
src/pipecat/utils/tracing/service_decorators.py

Fixes: `ttfb_ms` was providing seconds instead of milliseconds

Fix implementation of ttfb_ms metric

---

examples/foundational/04-transports-small-webrtc.py
examples/p2p-webrtc/daily-interop-bridge/server.py
examples/p2p-webrtc/video-transform/server/server.py
examples/p2p-webrtc/voice-agent/server.py
src/pipecat/examples/run.py

My local pyright wasn't happy with a call to `close()` in the small WebRTC transport example.
SmallWebRTCConnection doesn't have a `close()`. There's a `_close()` but I assume that's private due to its naming. The closest function that uses `_close()` is `disconnect()`. I assume then, that the intended resource freeing function call should be to `disconnect()`.

Fix type checker error with missing function call in the small WebRTC transport example

---

CHANGELOG.md
src/pipecat/processors/aggregators/user_response.py
src/pipecat/services/google/llm.py
src/pipecat/transports/base_output.py

Fixed an issue where OutputAudioRawFrame.transport_destination was being reset to None instead of retaining its intended value before sending the audio frame to the transports.

Fixed transport destination issue

---

src/pipecat/services/piper/tts.py

This pull request includes a small fix in the `run_tts` method in `src/pipecat/services/piper/tts.py`. The typo in the variable name `eror` was corrected to `error` to improve code readability and prevent potential confusion.

fix(piper-tts): typo

---

CHANGELOG.md
src/pipecat/services/gladia/config.py

Added the option `informal` to `TranslationConfig`  Gladia STT.
Allowing to force informal language forms when available.

Gladia informal translations

---

src/pipecat/services/cartesia/stt.py

One other observation: this service does not abide by the sample rate being set by the PipelineParams. In other services, we initialize to an Optional[int] of None and then let the StartFrame define the sample_rate. Should we not do the same here? The one caveat is that CartesiaSTTService supports 16khz only.
cc @aconchillo @filipi87

CartesiaSTTService cleanup

---

CHANGELOG.md
src/pipecat/processors/aggregators/llm_response.py

Used by Pipecat Flows. Use case is to understand when there are additional function calls pending.

Expose has_function_calls_in_progress property

---

CHANGELOG.md
src/pipecat/frames/frames.py
src/pipecat/processors/frame_processor.py

Sometimes it might be necessary to control if a frame processor is processing frame or not. Instead of calling methods directly (which is still possible) we just use frame as usual.

FrameProcessor: handle new FrameProcessorPauseFrame/FrameProcessorResumeFrame

---

src/pipecat/services/aws/stt.py

Hi,
I'm currently testing pipecat for my usecase that requires supporting Polish language transcription through Amazon  Transcribe. 
I'm Polish native, so tested it and looks like works.

Support polish language in Amazon Transcribe

---

CHANGELOG.md
scripts/daily/test_tavus_transport.py
scripts/fix-ruff.sh
src/pipecat/services/tavus/video.py
src/pipecat/transports/services/daily.py
src/pipecat/transports/services/tavus.py

This PR adds support for sending audio to Tavus using custom tracks instead of app messages.
It also includes a test script (`scripts/test_tavus_transport.py`) that mimics the behavior expected to be supported by Tavus.

Sending audio to Tavus using custom tracks

---

CHANGELOG.md
src/pipecat/services/aws/tts.py

Changes:
- add "LexiconNames" as an input param for AWS Polly tts.
Documentation reference
[AWS Managing Lexicons](https://docs.aws.amazon.com/polly/latest/dg/managing-lexicons.html)
[SynthesizeSpeech request params](https://docs.aws.amazon.com/polly/latest/dg/API_SynthesizeSpeech.html)

Support AWS Polly Lexicon Names parameter

---

src/pipecat/services/mcp_service.py

This PR improves the MCP (Model Context Protocol) client's SSE (Server-Sent Events) server connection handling by replacing the generic string parameter with a proper `SseServerParameters` class.
- **Breaking Change**: Changed `server_params` type from `Union[StdioServerParameters, str]` to `Union[StdioServerParameters, SseServerParameters]`
- Added import for `SseServerParameters` from `mcp.client.session_group`
- Updated SSE client connection to use structured parameters instead of a simple URL string
- Fixed error message to correctly reflect the expected parameter types
- Improved logging by changing info-level log to debug-level for consistency
The SSE client connection only accepted a URL string:
```python
async with self._client(self._server_params) as (read, write):
```
Now …

Fix SSE server connection handling for MCP client

---

CHANGELOG.md
src/pipecat/pipeline/base_task.py
src/pipecat/pipeline/parallel_pipeline.py
src/pipecat/pipeline/runner.py
src/pipecat/pipeline/task.py
src/pipecat/processors/consumer_processor.py
src/pipecat/processors/frame_processor.py
src/pipecat/processors/frameworks/rtvi.py
src/pipecat/services/assemblyai/stt.py
src/pipecat/services/aws/stt.py
src/pipecat/services/aws_nova_sonic/aws.py
src/pipecat/services/gemini_multimodal_live/gemini.py
src/pipecat/services/gladia/stt.py
src/pipecat/services/google/stt.py
src/pipecat/services/openai_realtime_beta/events.py
src/pipecat/services/openai_realtime_beta/openai.py
src/pipecat/services/riva/stt.py
src/pipecat/services/simli/video.py
src/pipecat/services/tavus/video.py
src/pipecat/transports/base_input.py
src/pipecat/transports/network/fastapi_websocket.py
src/pipecat/transports/network/small_webrtc.py
src/pipecat/transports/services/livekit.py
src/pipecat/utils/asyncio.py
tests/test_pipeline.py

From the CHANGELOG:
Introduce task watchdog timers. Watchdog timers are used to detect if a Pipecat task is taking longer than expected (by default 5 seconds). It is possible to change the default watchdog timer timeout by using the `watchdog_timeout` constructor argument when creating a `PipelineTask`. With watchdog timers it is also possible to log how long each processing step is taking (e.g. processing an element from a queue inside a task). This is done with the `enable_watchdog_logging` constructor argument when creating a `PipelineTask.` It is also possible to control these two values per each frame processor. That is, you can set set `enable_watchdog_logging` and `watchdog_timeout` when creating any frame processor through their constructor arguments. Finally, you can also set …

introduce watchdog timers

---

CHANGELOG.md
src/pipecat/serializers/telnyx.py

With the current code, when a user hangs up, an error occurs:
```
2025-06-24 11:15:57.588 | ERROR    | pipecat.serializers.telnyx:_hang_up_call:202 - Failed to terminate Telnyx call v3:S_AwERIkXuL9vqBSvluFUDxUdIQRk4R_gz6OPajNQNrlcX2ReJ2nzw: Status 422, Response: {
"errors": [
{
"code": "90018",
"title": "Call has already ended",
"detail": "This call is no longer active and can't receive commands."
}
]
}
```
The root cause is that the user hangs up first. This doesn't happen with Twilio, so it's unique behavior with Telnyx. Unfortunately, the call status isn't communicated over the websocket (just the mediastream status, which is different from the call status, as far as I can tell). Instead, we'll handle the 422 error and corresponding error code (#90018) and just log a debug message.

fix: Telnyx, catch error when user has hung up the call first

---

src/pipecat/pipeline/task.py

Some of the processors like `STTService` and `TTSService` don't push `StartFrame` ahead in the pipeline, unless they have connected with their service providers. This delays `StartFrame` in downstream processors. 
If we receive `HeartBeatFrame` frame before `StartFrame`, we will get `AttributeError`: `'Processor' object has no attribute '_FrameProcessor__input_queue'`. 
Idea is to start HeartBeats after StartFrame has been processed by all the Processors in the pipeline.

Start HeartBeat when all processors have processed StartFrame

---

CHANGELOG.md
src/pipecat/services/aws_nova_sonic/aws.py
src/pipecat/utils/asyncio/watchdog_async_iterator.py
src/pipecat/utils/asyncio/watchdog_coroutine.py

We can not always use `asyncio.wait_for()` as this can break internal state as it triggers an asyncio.CancelledError.

add watchdog coroutine helper

---

src/pipecat/audio/vad/silero.py

`numpy` is already imported at the module level, so the local import and setting to global is redundant. Removing it.

Remove redundant import and global in SileroOnnxModel

---

src/pipecat/services/google/llm.py

This would be useful to support private instance or gateway of the API. There are issues where Gemini API suddenly reporting user location is not supported for the API use. Although using a server in a location supported by Gemini API. And this is also useful if the user wants to use an AI Gateway such as Cloudflare AI Gateway to monitor Gemini API usage.
https://github.com/googleapis/python-genai/issues/583.
Sample usage:
```
from google.genai import types
llm = GoogleLLMService(
api_key=os.getenv("GOOGLE_API_KEY"),
system_instruction=<system_instruction>,
model="gemini-2.0-flash-lite",
params=GoogleLLMService.InputParams(
temperature="0.5",
max_tokens=300
),
http_options=types.HttpOptions(
base_url=<new_base_url>
)
)
```
Issue references:
- …

Add option to change the base URL for Google Generative AI.

---

CHANGELOG.md
src/pipecat/services/fish/tts.py

Fish Audio has changed their naming:
- `model` is now `reference_id`, so we're deprecating `model` and using `reference_id` instead
- Also, we're adding the arg called `model_id` which is the actual model and a new param to `InputParams` called `normalize`.
Replacing #2031 which started this work.

FishAudioTTSService: arg cleanup, add new InputParam and arg

---

CHANGELOG.md
src/pipecat/audio/turn/base_turn_analyzer.py
src/pipecat/audio/turn/smart_turn/base_smart_turn.py
src/pipecat/frames/frames.py
src/pipecat/processors/aggregators/llm_response.py
src/pipecat/transports/base_input.py
tests/test_context_aggregators.py

This PR fixes: #2160.
The root cause of this issue is that emulated user speech (e.g. no VAD speech detection but the arrival of a TranscriptionFrame) results in pushing an aggregation after the `aggregation_timeout`. The `aggregation_timeout` is 0.5s and the default VAD `stop_secs` is 0.8s, so this often results in a completion occurring before desired. There are two new cases to handle, both of which occur when there is VAD emulation:
1. No turn analyzer present: In this case, the `_aggregation_task_handler` has a separate timeout for the emulated speech case where the timeout is set according to the `VADParams` `stop_secs`. This ensures a common UX for cases where there's both VAD detected speech and VAD emulation.
2. Turn analyzer present: In this case, we can't simply use the …

fix: use a different aggregation timeout for emulated user speech

---

CHANGELOG.md
src/pipecat/processors/aggregators/llm_response.py

- Fixed an issue where, in some edge cases, the `EmulateUserStartedSpeakingFrame` could be created even if we didn't have a transcription.

Only create the EmulateUserStartedSpeakingFrame if we have received a transcription

---

CHANGELOG.md
src/pipecat/services/elevenlabs/tts.py

This was reported in Discord. In looking into it, the main issue was that the cumulative time was not correctly calculated. It was calculating the total time of a chunk by the start time of the last word, not the end time.
Also, there was a subtle issue with the timing on a per word basis. The timing was determined based on the space before the word, not the start of the word itself.
This PR aims to correct this issue and to simplify the algorithms to make them easier to maintain.
I've tested this with the simple-chatbot example to ensure that the word timings are correct.

fix: Improve ElevenLabsTTSService word/timestamp calcuation accuracy

---

src/pipecat/services/mcp_service.py

This PR resolves a warning to use FunctionCallParams in MCPClient when registering tools:
```
DeprecationWarning: Function calls with parameters `(function_name, tool_call_id, arguments, llm, context, result_callback)` are deprecated, use a single `FunctionCallParams` parameter instead.
```

mcp_tool_wrapper using FunctionCallParams

---

CHANGELOG.md
pyproject.toml
src/pipecat/utils/string.py
tests/test_utils_string.py

The regex based end of sentence detection is too fragile and has too many edge cases. Instead, I'm proposing that we move to using NLTK's punkt_tab sentence tokenizer along with a secondary check for punctuation.
The secondary check is required due to the LLM streaming token use case—NLTK will see an individual word, like `Hello`, and deem it as a complete sentence. Since all LLM output is streamed as tokens, this would result in TTS aggregation breaking. Instead, we're interested in NLTK's sentence detection (and edge case handling for things like acronyms, numbers, emails, etc) along with an added check that the sentence ends in some form of punctuation. Since Pipecat supports a wide range of languages, I asked Claude for some help determining end of sentence punctuation for a broader …

Update match_endofsentence to use NLTK sentence tokenizer

---

CHANGELOG.md
src/pipecat/transports/services/livekit.py

This PR fixes a bug in the LiveKit transport where the `on_audio_track_subscribed` event was never emitted when audio tracks were successfully subscribed.

fix(livekit): emit on_audio_track_subscribed event

---

CHANGELOG.md
pyproject.toml

This PR resolves dependency conflicts that were preventing `uv sync` from working and makes pipecat-ai more compatible with the broader Python ecosystem. One additional change is needed to achieve this goal: https://github.com/pipecat-ai/pipecat/pull/2256.
This will also make it easier to run the release evals, as all packages can be installed simultaneously.
- **numba**: Reducing the minimum numba dependency to 0.60.0. This still satisfies the requirement for python 3.10 and above, while also working compatibly with the `llvm` version required by the `ultravox` optional dependency.
- **aws_sdk_bedrock_runtime**: The `aws_sdk_bedrock_runtime` only supports python 3.12 and newer, so formalizing that constraint.
- **torch** and **torchaudio**: Relaxing from exact pinning (`==2.5.0`) to …

pyproject.toml dependency updates to support better cross compatibility

---

CHANGELOG.md
src/pipecat/services/elevenlabs/tts.py

Play delayed messages from `ElevenLabsTTSService` if they still belong to the current context.

Play delayed messages from `ElevenLabsTTSService` if they still belong to the current context.

---

CHANGELOG.md

A new pattern we should follow. When a release has critical issues, we should mark it as yanked.
We'll update the changelog as well with information about why the release was yanked. I've already updated PyPI for these two versions.

Add yanked notices to 0.0.74 and 0.0.75 changelogs

---

CHANGELOG.md
src/pipecat/processors/transcript_processor.py

The `isspace()` function checks for any whitespace character, not just spaces. When an LLM outputs text that contains newline characters (`\n`), this is incorrectly detected as a space, resulting in an incorrect transcript aggregation strategy.
Instead, the check is now explicitly for spaces.
Note: if newlines were output by the LLM, the TranscriptProcessor should not clean them up. The job of the TranscriptProcessor is to output the text received without modification. The `text_filters` feature of the TTSService can be used to modify the text. For example, setting `text_filters=[MarkdownTextFilter()]` will strip newline characters.

fix: Improve TranscriptProcessor detection for transcript type

---

CHANGELOG.md
src/pipecat/processors/aggregators/openai_llm_context.py

@kompfner found this in working through his context refactor. Another user reported in Discord that they see an error message like this when using Grok:
```
GrokLLMService#0::__input_frame_task_handler: unexpected exception: Error code: 400 - {'code': 'Client specified an invalid argument', 'error': 'Invalid request content: Only message of role user can have a name.'}
```
Not all services support an optional `name` field in the message. It's only used at the moment when you push an `LLMMessagesFrame`. Given it's limited use and that it's optional/not really utilized, we should remove it. This should help to remove a category of errors.

Remove message["name"] addition when pushing

---

CHANGELOG.md
src/pipecat/transports/services/helpers/daily_rest.py

Adding a parameter for enabling transcription storage for the rest api helper class. 
Reference: 
https://docs.daily.co/reference/rest-api/your-domain/config#enable_transcription_storage

Add transcription_bucket param for rest helper

---

src/pipecat/frames/frames.py
src/pipecat/services/gemini_multimodal_live/events.py
src/pipecat/services/gemini_multimodal_live/gemini.py

This pull request fixes a contextual disconnect in the Gemini Multimodal Live API integration.  
Previously, text inputs went through the **clientContent** stream, while audio and video used **realtimeInput**.  
Because the Gemini API processes these streams concurrently, their contexts are not guaranteed to interleave, which can cause text to drift out of sync with simultaneous audio/video.
The PR adds a pathway that sends text through **realtimeInput**, so text, audio, and video now share the same context stream for coherent, synchronized interactions.
---
- **RealtimeInput** model: added optional `text` field (parity with `BidiGenerateContentRealtimeInput`).
- Added **TextInputMessage** class to carry text into the `realtimeInput` stream.
- Added new branch in `process_frame` to treat …

Add text input handling to unify context for realtimeInput stream of GeminiMultimodalLiveService

---

CHANGELOG.md
src/pipecat/services/neuphonic/tts.py

Fixes https://github.com/pipecat-ai/pipecat/issues/2306

NeuphonicTTSService: change the default url value to the global endpoint

---

src/pipecat/processors/aggregators/llm_response.py

This fixes an issue reported on this discord [here](https://discord.com/channels/1239284677165056021/1398681452912181278/1400167964178911373)
**Problem:**
In `LLMUserContextAggregator`, the function `push_aggregation` was updated to handle the newly added Interruption Strategies. When using `LLMUserResponseAggregator `, it subclasses `LLMUserContextAggregator` and overrides `push_aggregation` without calling the super. this means the logic to handle Interruption Strategies isn't present.
**Solution:**
Theres a few ways to fix this, I opted for overriding `_process_aggregation` in the subclass. It looks like the logic that existed in the older `push_aggregation` got moved there and the same result is ultimately achieved.

Enable Interruption Support for LLMUserResponseAggregator

---

.github/workflows/sync-quickstart.yaml

We'll treat the quickstart example in the pipecat repo as the source of truth and will sync the files to: https://github.com/pipecat-ai/pipecat-quickstart.
The two examples will have custom READMEs which won't be synced.
Token created as Github PAT.

Add workflow to sync quickstart to pipecat-quickstart repo

---

pyproject.toml

Adding `dev` to pyproject.toml so we can replace `pip install -r dev-requirements.txt` with `pip install -e .[dev]`
or, in uv land: `uv sync --extra dev`
This is a pre-req to updating our CI with uv, which will speed up times by 3-5x.

Add dev to optional-dependencies

---

CHANGELOG.md
src/pipecat/transports/services/livekit.py

Reports in Discord of users seeing:
```
WARNING  | pipecat.services.stt_service:process_audio_frame:157 - Empty audio frame received for STT service: DeepgramSTTService#0 0
```
This was due to LiveKit pushing empty audio frames. The new warning in the STTService was flagging empty audio frames. This fix updates LiveKitInputTransport to only push non-zero AudioRawFrames.

fix: LiveKitTransport, don't push empty AudioRawFrames

---

CHANGELOG.md
src/pipecat/transports/services/tavus.py

TavusTransport is completely broken in Pipecat 0.0.77+ and fails to initialize with Pydantic validation errors.
```python
pydantic_core._pydantic_core.ValidationError: 2 validation errors for DailyCallbacks
on_transcription_stopped
Field required [type=missing, input_value={...}]
on_transcription_error
Field required [type=missing, input_value={...}]
```
- **Severity**: HIGH - Complete failure, no workaround without this fix
- **Affected Users**: ALL users trying to use Tavus avatars with Pipecat 0.0.77+
- **Regression**: Yes - worked in 0.0.76, broken since 0.0.77
PR #2292 (merged July 29, 2025) added two new required callbacks to `DailyCallbacks`:
- `on_transcription_stopped: Callable[[str, bool], Awaitable[None]]`
- `on_transcription_error: Callable[[str], Awaitable[None]]` …

fix: Add missing transcription callbacks to TavusTransport for 0.0.77 compatibility

---

CHANGELOG.md
src/pipecat/pipeline/task_observer.py
src/pipecat/services/llm_service.py

This PR fixes a performance issue where for each received frame in each observer we were inspecting the `on_push_frame` to decide if this was the old or new signature. This is only necessary once.

TaskObserver: don't inspect on_push_frame signature for every frame

---

CHANGELOG.md
src/pipecat/services/piper/tts.py

The `PiperTTSService.run_tts` method currently sends a raw string as the POST payload:
```python
async with self._session.post(self._base_url, json=text, headers=headers) as response:
```
However, according to [Piper's HTTP API documentation](https://github.com/OHF-Voice/piper1-gpl/blob/main/docs/API_HTTP.md), the expected format is a JSON object:
```json
{ "text": "..." }
```
This discrepancy causes the test `tests/test_piper_tts.py::test_run_piper_tts_success` to fail, as the service responds with an error when the payload format is incorrect.
This PR updates the request to wrap text in the required dictionary format.
* PR #2293 (merged recently) also modified this part of the code but did not fix the incorrect payload structure.
* This PR addresses the root cause of the failing test …

Fix PiperTTSService to send TTS input as JSON object

---

src/pipecat/services/gemini_multimodal_live/events.py
src/pipecat/services/gemini_multimodal_live/gemini.py

This was sending a 1007 payload error because turnComplete is only valid for clientContent. 
- Remove invalid `turnComplete` message from `_send_user_text` method
- `turnComplete` is only valid for `clientContent`, not `realtimeInput` messages
- `realtimeInput` text completion is automatically inferred by the API

Hotfix: Correct Gemini Live API class to fix 1007 payload error. 

---

examples/quickstart/bot.py
src/pipecat/runner/run.py

Two things:
1. On first run of the quickstart, there is no log feedback for upwards of 40 seconds. We have (at least) two options I can think of to provide feedback: 1) add logging the quickstart file, 2) add a preload.py script. I'm opting for the logging since there's only one file to run and the added complexity is minimal. The preload script visually is better, but it's a more complex file and an extra step. I'm opting for simplicity.
2. In the runner, I want the old message was:
```
🚀 WebRTC server starting at http://localhost:7860/client
Open this URL in your browser to connect!
```
The new message will be:
```
🚀 Bot ready!
→ Open http://localhost:7860/client in your browser
```
This is visually easier to scan and more actionable.
With these changes, a user will see:
```
🚀 Starting …
```

Improve quickstart logging, runner startup message

---

CHANGELOG.md
src/pipecat/runner/daily.py

Simplifying the daily runner util:
- Removing the url/api key arg parsing. This feature is unnecessary given the env variable support. Args are already complex, so I'm opting to not add another later.
- When no URL is provided, we'll auto-generate a room a token at join time.
- Since there is no arg parsing anymore, I'm deprecating `configure_with_args`

daily runner util: remove arg parsing, add auto room, token generation

---

README.md
env.example
examples/foundational/README.md
examples/foundational/requirements.txt

Main README:
- Removing pip, adding uv.
- Also, renaming `dot-env.template` to `env.example`.
Foundational README:
- Removing pip, adding uv.
- Removed "learning path" links as we now recommend quickstarts and this highlights the setup instructions.
- Leaving a requirements.txt with base level requirements to run all examples. Maybe we'll remove in the future.

Update the README with uv-centric steps

---

CHANGELOG.md
src/pipecat/runner/run.py

Check out the changelog for the changes.
The motivation is for the development runner to more closely mimic the Pipecat Cloud `/start` endpoint.
All of the changes are intended to reduce the amount of custom code needs to be written between a local and production deployment.

Development runner handles body information in the RTVI connect request

---

CHANGELOG.md
src/pipecat/frames/frames.py
src/pipecat/pipeline/task.py
src/pipecat/processors/frame_processor.py
src/pipecat/services/heygen/video.py

A couple of important changes:
- System frames:  System frames are now queued. Before, system frames could be generated from any task and would not guarantee any order which was causing undesired behavior. Also, it was possible to get into some rare recursion issues because of the way system frames were executed (they were executed in-place, meaning calling `push_frame()` would finish after the system frame traversed all the pipeline). This makes system frames more deterministic.
- PipelineTask: Before CancelFrames didn't need to be waited for because system frames were processed in-place and therefore calling push_frame() would finalize after it traversed all the pipeline. Now, system frames are queued so we need to wait until CancelFrame reaches the end of the pipeline.

system frames are now queued

---

CHANGELOG.md
examples/foundational/12-describe-video.py
examples/foundational/12a-describe-video-gemini-flash.py
examples/foundational/12b-describe-video-gpt-4o.py
examples/foundational/12c-describe-video-anthropic.py
examples/foundational/20a-persistent-context-openai.py
examples/foundational/20c-persistent-context-anthropic.py
src/pipecat/services/tts_service.py

With this PR we deprecate `TTSService.say()` and we force to push a `TTSSpeakFrame` instead. Calling functions directly is a discouraged pattern in Pipecat because, for example, it might cause issues with frame ordering.

deprecate TTSService.say() method

---

CHANGELOG.md
src/pipecat/pipeline/parallel_pipeline.py
src/pipecat/pipeline/pipeline.py
src/pipecat/pipeline/sync_parallel_pipeline.py
src/pipecat/pipeline/task.py
src/pipecat/processors/frame_processor.py

This PR improves some frame processors performance by introducing a direct mode. In direct mode a frame processor will process frames right away avoiding the need for internal queues and tasks. This is useful for some simple processos. For example, in processors that wrap other processors (e.g. `Pipeline`, `ParallelPipeline`), we add one processor before and one after the wrapped processors (internally, you will see them as sources and sinks). These sources and sinks don't do any special processing and they basically forward frames. So, for these simple processors we now enable the new direct mode which avoids creating any internal tasks (and queues) and therefore improves performance.

FrameProcessor: introduce direct mode

---

CHANGELOG.md
README.md
src/pipecat/processors/frame_processor.py

This PR fixes an issue that's causing system frames to not be considered higher priority. The problem is that to insert an item to the queue we were doing:
```
await self.__process_queue.put((frame, direction, callback))
```
But then, when we check to see if the inserted frame has higher priority we do:
```
async def put(self, item: Any):
if isinstance(item, SystemFrame):
await self.__system_queue.put(item)
else:
await self.__main_queue.put(item)
```
Note that `item` is a tuple, so `isinstance_item, SystemFrame)` is never satisfied.
To fix this we would just need to check the proper item in the tuple but I went a bit further and simplified the whole thing to use a PriorityQueue instead.

FrameProcessor: fix system frame higher priorty and use a PriortyQueue

---

src/pipecat/processors/frame_processor.py
src/pipecat/utils/asyncio/watchdog_priority_queue.py
src/pipecat/utils/asyncio/watchdog_queue.py
tests/test_watchdog_queue.py

We need to increment the counters before the await otherwise we could go to a different task that could add an item with the same counter.
Also, we need to handle non-frame items as well.

FrameProcessor: fix race condition on FrameProcessorQueue

---

CHANGELOG.md
src/pipecat/processors/frame_processor.py
src/pipecat/transports/base_output.py
src/pipecat/utils/asyncio/watchdog_priority_queue.py
tests/test_watchdog_queue.py

Sub-classes need to implement `put_cancel_item()` and `get_value()` methods. The reason is because we are inserting the watchdog cancel sentinel and there needs to be a way to compare it with other items. The `__lt__` method was not enough because it depends on the order of comparisson. To make it more robust sub-classes now need to indicate how to insert a watchdogcancel sentinel, following the priority scheme.

WatchdogPriorityQueue: this is now a base class

---

CHANGELOG.md
src/pipecat/services/azure/tts.py

This is related to issue #2277. 
The current implementation of AzureTTS generates SSML markup for Azure by directly embedding the LLM generated text to it. However, SSML has reserved. characters and according to Microsoft documentation (https://github.com/pipecat-ai/pipecat/compare/main...yohan-altrium:pipecat:fix/2277-azure-tts-ssml-reserved-characters?expand=1), Azure expects the & sign, and < and > signs to be escaped and replaced with entity format. (Note: Microsoft does not seem to require us to escape quotes).
This pull request fixes this issue by maintaining a list of characters to be escaped in `AzureBaseTTSService`, and escaping the text to replace those sensitive characters with the correct entity format.

Fixes 2277 - SSML reserved characters causes Azure TTS to fail

---

CHANGELOG.md
src/pipecat/pipeline/task.py

@aconchillo we talked about this the other day. I think `UserStartedSpeakingFrame`, `UserStoppedSpeakingFrame` are good signals for user activity. Did you have anything else in mind?

Add UserStarted/StoppedSpeakingFrames to idle_timeout_frames

---

CHANGELOG.md
src/pipecat/audio/utils.py
src/pipecat/pipeline/task.py
src/pipecat/processors/aggregators/llm_response.py
src/pipecat/processors/frame_processor.py
src/pipecat/processors/metrics/sentry.py
src/pipecat/services/llm_service.py
src/pipecat/services/soniox/stt.py
src/pipecat/services/tts_service.py
src/pipecat/transports/base_output.py
src/pipecat/transports/network/websocket_server.py
src/pipecat/utils/asyncio/task_manager.py

This was necessary before we started using `task.add_done_callback()`. So, it's legacy code that's not needed anymore.

FrameProcessor: wait_for_task is now deprecated

---

CHANGELOG.md
README.md
src/pipecat/pipeline/runner.py
src/pipecat/pipeline/task.py
tests/test_pipeline.py

This PR fixed an issue where PipelineRunner and PipelineTask don't handle asyncio task cancellation. We need to raise the exception from `PipelineTask` and handle it in `PipelineRunner`. This way, we can properly cancel the pipeline task.
This fixes an issue we had in release evals where if the eval takes a long time we cancel the asyncio task. This was causing all sort of problems and not allowing the following evals to execute correctly.

PipelineRunner/PipelineTask: fix asyncio task cancellation

---

CHANGELOG.md
src/pipecat/services/cartesia/tts.py

Cartesia doesn't support keep alive messages so it will just disconnect after 5 minutes. We cancel this use case by simply reconnecting. Note that this is not made generic because we don't know how the other `_receive_messages()` implementations might behave. So, this needs to be done per service.

CartesiaTTSService: reconnect on Cartesia's timeout

---

CHANGELOG.md
src/pipecat/pipeline/task.py
tests/test_pipeline.py

This PR adds a `cancel_timeout_secs` argument to `PipelineTask` which defines how long the pipeline has to complete cancellation. When `PipelineTask.cancel()` is called, a `CancelFrame` is pushed through the pipeline and must reach the end. If it does not reach the end within the specified time, a warning is shown and the wait is aborted.

PipelineTask: warn if CancelFrame doesn't reach the end

---

src/pipecat/processors/metrics/sentry.py

Adds missing `import asyncio` to `sentry.py` which is causing apps to crash. See issue.
https://github.com/pipecat-ai/pipecat/issues/2519

add missing import asyncio

---

CHANGELOG.md
src/pipecat/services/cartesia/tts.py

Latest docs reflect speed supporting only an enum:
- WSS: https://docs.cartesia.ai/2024-11-13/api-reference/tts/tts#send.Generation-Request.speed
- HTTP: https://docs.cartesia.ai/2024-11-13/api-reference/tts/bytes#request.body.speed

Cartesia: update speed InputParam

---

CHANGELOG.md
src/pipecat/pipeline/task.py

When using RTVI we were getting this error on startup:
```
RTVIProcessor#0 Trying to process TransportMessageUrgentFrame#0(message: {'label': 'rtvi-ai', 'type': 'metrics', 'data': {'ttfb': [{'processor': 'DeepgramSTTService#0', 'value': 0.0}, {'processor': 'OpenAILLMService#0', 'value': 0.0}, {'processor': 'CartesiaTTSService#0', 'value': 0.0}], 'processing': [{'processor': 'DeepgramSTTService#0', 'value': 0.0}, {'processor': 'OpenAILLMService#0', 'value': 0.0}, {'processor': 'CartesiaTTSService#0', 'value': 0.0}]}}) but StartFrame not received yet   
```
The problem is that observers listen for `on_push_frame` and this might get called before `StartFrame` reaches the RTVI processor.
The reason is that in PipelineTask we were doing:
```
queue_frame(StartFrame()) …
```

PipelineTask: wait for StartFrame to reach end of pipeline

---

CHANGELOG.md
src/pipecat/frames/frames.py
src/pipecat/processors/aggregators/dtmf_aggregator.py
src/pipecat/services/llm_service.py
src/pipecat/services/tts_service.py

This PR adds `skip_tts` field to `TextFrame`. This lets a text frame bypass TTS while still being included in the LLM context. Useful for cases like structured text that isn’t meant to be spoken but should still contribute to context.
It also adds support for switching between text-only and audio-only modes within the same pipeline. This is done by pushing `LLMConfigureOutputFrame(skip_tts=True)`. The LLM will still generate tokens and add them to the context, but they will not be sent to TTS.

TextFrame: add skip_tts field

---

CHANGELOG.md
examples/foundational/07c-interruptible-deepgram-vad.py
examples/foundational/22b-natural-conversation-proposal.py
examples/foundational/22c-natural-conversation-mixed-llms.py
src/pipecat/frames/frames.py
src/pipecat/processors/filters/stt_mute_filter.py
src/pipecat/processors/frame_processor.py
src/pipecat/services/openai_realtime_beta/openai.py
src/pipecat/transports/base_input.py
src/pipecat/transports/base_output.py

This PR removes `StopInterruptionFrame`. This was a legacy frame that was not being used really anywhere and it didn't provide any useful meaning. It was only pushed after `UserStoppedSpeakingFrame`, so developers can just use `UserStoppedSpeakingFrame`.
I don't think it make sense to deprecate it.

frames: remove StopInterruptionFrame

---

CHANGELOG.md
src/pipecat/pipeline/task.py
src/pipecat/pipeline/task_observer.py

This PR makes sure we call observers `cleanup()`, otherwise we would not cleanup observers cleanly that have network connection (e.g. Whisker).

PipelineTask: cleanup observers

---

CHANGELOG.md
examples/foundational/14k-function-calling-cerebras.py
src/pipecat/services/cerebras/llm.py

`llama-3.3-70b` is sometimes prone to looping on tool calls. This PR updates the default for Cerebras inference to `gpt-oss-120b`, which is supported in production in Cerebras' inference API and exhibits stronger performance on tool calling.

fix: update default Cerebras model to GPT-OSS-120B

---

src/pipecat/services/aws/llm.py

Fixes issue https://github.com/pipecat-ai/pipecat/issues/2558.
When using `retry_timeout_secs` and `retry_on_timeout` parameters with `AWSBedrockLLMService`, the following error occurs:
````
TypeError: object dict can't be used in 'await' expression
````
The error is caused by a double `await` on line 883 in `pipecat/services/aws/llm.py`:
```python
response = await asyncio.wait_for(
await client.converse_stream(**request_params), timeout=self._retry_timeout_secs
)
```
The issue occurs because:
1. `client.converse_stream(**request_params)` returns a coroutine
2. The inner `await client.converse_stream(**request_params)` resolves this coroutine to a dictionary response
3. `asyncio.wait_for()` then tries to await this dictionary, which is not awaitable
4. This results in the TypeError: …

fix timeout handling in AWSBedrockLLMService

---

CHANGELOG.md
src/pipecat/transports/base_output.py
src/pipecat/transports/daily/transport.py

Since Daily supports RTP events, we should use them over tones. This change restores Daily's use of the send_dtmf functionality. It preserves the audio tones for websocket services, which can only send MediaStreams.
This change allows for new transports to declare native support and override, applying their own DTMF functionality. For example, we would use Livekit's native DTMF, not tones. But, until we implement that native capability, Livekit will use Pipecat's audio tones, which serves as a fallback.

DTMF: Add support for native DTMF implementation where available

---

scripts/evals/eval.py

This improves the evals prompt by allowing the user to say things other than the answer like "Let me check on that" and only run the eval function call when the user actually answers the question.

scripts(evals): allow user to talk and only eval when needed

---

CHANGELOG.md
src/pipecat/pipeline/task.py
tests/test_pipeline.py

This simplifies pipeline tasks events with a single one: `on_pipeline_finalized`. This deprecates `on_pipeline_stopped`, `on_pipeline_ended` and `on_pipeline_cancelled`. Users can just check the frame type if they want to know why it ended.

PipelineTask: add on_pipeline_finished event

---

src/pipecat/services/mcp_service.py

Currently the MCP client is expected a `Tuple` type as `server_params`. This is wrong since the code, expects one server with a `Type` that is either `StdioServerParameters`, `SseServerParameters` or `StreamableHttpParameters`.
This will lead to Type check issues as `__init__` would expected a `Tuple` as input with all three server param types present. 
Current code:
```
def __init__(
self,
server_params: Tuple[StdioServerParameters, SseServerParameters, StreamableHttpParameters],
**kwargs,
):
"""Initialize the MCP client with server parameters.
Args:
server_params: Server connection parameters (stdio or SSE).
**kwargs: Additional arguments passed to the parent BaseObject.
"""
super().__init__(**kwargs)
self._server_params = server_params
self._session = ClientSession …
```

fix: replace `Tuple` type with `TypeAlias` for server params in MCP client

---

CHANGELOG.md
src/pipecat/frames/frames.py
src/pipecat/pipeline/service_switcher.py
tests/test_service_switcher.py

And fix an issue caught by those tests! See [commit message](https://github.com/pipecat-ai/pipecat/pull/2646/commits/a2ad71d02958caf58cfe3ba131349cee6536e8fd) for description. TL;DR: `ServiceSwitcherFrame`s were updated to be properly processed in order.
UPDATE: actually, [_another fix_](https://github.com/pipecat-ai/pipecat/pull/2646/commits/71015bc6a79ec8fc3ac6485e1ff94f69a7da0eeb): we probably generally _don't_ want `ServiceSwitcherFrame`s to be processed in order. They should probably be `SystemFrame`s.
ANOTHER UPDATE: scratch that—we're back to processing the frames in order, as `ControlFrame`s.

`ServiceSwitcher` unit tests (ended up being much more than that)

---

CHANGELOG.md
src/pipecat/processors/frame_processor.py
tests/test_frame_processor.py

This PR fixes an issue that was causing a previous `InterruptionFrame` to prevent `push_interruption_task_frame_and_wait()` to actually wait.

interruption task frame wait fixes

---

CHANGELOG.md
src/pipecat/services/google/llm_vertex.py

- Update _get_base_url method to handle 'global' location case
- Use 'aiplatform.googleapis.com' for global locations
- Use '{location}-aiplatform.googleapis.com' for regional locations
- Maintains backward compatibility with existing regional endpoints

feat: add support for global location in Vertex AI base URL

---

src/pipecat/runner/run.py

Lazy loading the `SmallWebRTCRequest` and `SmallWebRTCRequestHandler` imports in the `_setup_webrtc_routes` function, so that the `webrtc` optional dependency is only needed when using SmallWebRTCTransport.

Lazy load SmallWebRTCRequest, SmallWebRTCRequestHandler in runner

---

src/pipecat/transports/daily/transport.py

This PR adds a `DailyUpdateRemoteParticipantsFrame`, which enables use of the [`daily.update_remote_participants` function](https://reference-python.daily.co/api_reference.html#daily.CallClient.update_remote_participants) within a sequence of frames.

Add remote participant updates to DailyTransport

---

CHANGELOG.md
src/pipecat/serializers/twilio.py

Some light clean up after https://github.com/pipecat-ai/pipecat/pull/2627.
We want to fail fast, but we only want to fail when the `auto_hang_up` feature is enabled, as these settings only apply to `auto_hang_up`.
Also, adding a changelog for #2627.

Fixup for TwilioFrameSerializer

---

CHANGELOG.md
src/pipecat/audio/turn/base_turn_analyzer.py
src/pipecat/audio/turn/smart_turn/base_smart_turn.py
src/pipecat/audio/turn/smart_turn/http_smart_turn.py
src/pipecat/audio/turn/smart_turn/local_smart_turn.py
src/pipecat/audio/turn/smart_turn/local_smart_turn_v2.py
src/pipecat/audio/turn/smart_turn/local_smart_turn_v3.py

In this PR we now run the turn analyzer in a separate thread. We force that by changing `_process_speech_segment` and therefore `_predict_endpoint` from async to sync and then implementing this:
```
state, result = await loop.run_in_executor(
self._executor, self._process_speech_segment, self._audio_buffer
)
```
This way all the CPU-bound implementation don't need to worry about anything and simply perform the computation. For HTTP-based implementation having a sync function implies that they are forced to use `run_coroutine_threadsafe`, so the contract is pretty clear in both cases.
If we kept `_predict_endpoint` async it is not clear that a thread would need to be created.

turn analyzer fixes

---

CHANGELOG.md
src/pipecat/pipeline/task.py

Don't call internal `_cancel()` if we are already finished. This could cause an issue in some circumstances.

PipelineTask: avoid cancellation if application is finished

---

CHANGELOG.md
examples/foundational/16-gpu-container-local-bot.py
src/pipecat/frames/frames.py
src/pipecat/processors/frameworks/rtvi.py
src/pipecat/processors/logger.py
src/pipecat/serializers/exotel.py
src/pipecat/serializers/plivo.py
src/pipecat/serializers/protobuf.py
src/pipecat/serializers/twilio.py
src/pipecat/transports/base_output.py
src/pipecat/transports/daily/transport.py
src/pipecat/transports/livekit/transport.py
src/pipecat/transports/smallwebrtc/transport.py
src/pipecat/transports/tavus/transport.py
src/pipecat/transports/websocket/client.py
src/pipecat/transports/websocket/fastapi.py
src/pipecat/transports/websocket/server.py
tests/test_frame_processor.py

This PR introduces the following deprecations in order to unify input/output transport message frames with other frames.
- TransportMessageFrame -> OutputTransportMessageFrame
- TransportMessageUrgentFrame -> OutputTransportMessageUrgentFrame
- InputMessageUrgentFrame -> InputMessageFrame (input messages are all urgent by default)
- DailyInputTransportMessageUrgentFrame -> DailyInputTransportMessageFrame
- DailyTransportMessageFrame -> DailyOutputTransportMessageFrame
- DailyTransportMessageUrgentFrame -> DailyOutputTransportMessageUrgentFrame
- LiveKitInputTransportMessageUrgentFrame -> LiveKitInputTransportMessageFrame
- LiveKitTransportMessageFrame -> LiveKitOutputTransportMessageFrame
- LiveKitTransportMessageUrgentFrame -> LiveKitOutputTransportMessageUrgentFrame

transport message frames deprecations

---

CHANGELOG.md
examples/foundational/07c-interruptible-deepgram-flux.py
scripts/evals/run-release-evals.py
src/pipecat/services/deepgram/flux/stt.py
src/pipecat/services/stt_service.py

Integrating the new Deepgram model (Flux) with Pipecat: 
- Creating `WebsocketSTTService` base class.
- Deepgram Flux speech-to-text service implementation.
- New example using DeepgramFluxSTTService
References:
- https://developers.deepgram.com/flux-early-access

Integrating the new Deepgram model (Flux) with Pipecat

---

src/pipecat/runner/run.py

Creating the whatsapp routes inside the runner.
This will allow us to have exactly the same behavior when running a Pipecat Cloud example and a local example.
All examples that work with SmallWebRTC should also work with WhatsApp, as long as the required environment variables are provided.

Creating the whatsapp routes inside the runner.

---

COMMUNITY_INTEGRATIONS.md
CONTRIBUTING.md
THIRD_PARTY_INTEGRATIONS.md

Add a third-party integrations guide
