pipecat-ai/pipecat

- src/dailyai/services/playht_ai_service.py
- src/examples/foundational/01-say-one-thing.py
Updates PlayHT service to the new service architecture, and 01- sample uses it.
Also note that this service must be explicitly deleted so the client.close() call gets executed.
> Update playht service

- src/dailyai/services/daily_transport_service.py
@aconchillo 's suggestions to improve setting up the client, and save performance by unsubscribing from cameras.
> cleanup client properties and unsubscribe from camera

- pyproject.toml
- src/dailyai/queue_frame.py
- src/dailyai/services/base_transport_service.py
- src/dailyai/services/daily_transport_service.py
- src/examples/foundational/06-listen-and-respond.py
I'm dismantling my [mega-PR](https://github.com/daily-co/daily-ai-sdk/pull/29) into the parts we actually want.
One thing I'm concerned about with this PR: we have a `speaker_enabled` property in the base transport that enables receiving audio. VAD also needs to receive audio, and daily-python doesn't seem to like two things in different threads both trying to get audio frames. For now, I'm 'hijacking' the `speaker_enabled` property to turn on VAD, since we only use it in the whisper local transcription example. But maybe we should have a separate property to enable VAD, and you can't use both at the same time?
> Isolated changes to add VAD

- src/dailyai/services/base_transport_service.py
- src/examples/foundational/07-interruptible.py
This chunks the audio in the base transport service to make interruptions more responsive.
> Interruption improvements

- src/dailyai/pipeline/aggregators.py
- src/dailyai/pipeline/frame_processor.py
- src/dailyai/pipeline/pipeline.py
- src/dailyai/services/ai_services.py
- src/dailyai/tests/test_aggregators.py
Start documenting classes & functions.
> Docstrings

- src/examples/foundational/14-patient-intake.py
I debated whether to try and get fancy with a dict and reflection in the allowlist, but in the end I found this more readable.
> function allowlist

- pyproject.toml
Some updates to our project.toml file. The description probably needs some refinement!
> updates to pyproject.toml

- src/dailyai/services/fal_ai_services.py
I noticed @kwindla changed this in a PR; I was setting it back for local testing and mistakenly merged it.
> set FAL param correctly

- src/dailyai/services/fal_ai_services.py
> Use other model in FAL

- pyproject.toml
- src/dailyai/services/anthropic_llm_service.py
Added a new LLMAIService object to support Anthropic. This was straightforward because it follows the same `messages` layout as OpenAI.
> Anthropic LLM service

- src/dailyai/services/daily_transport_service.py
This will help the user figure out what's going on. For example in https://github.com/daily-co/daily-ai-sdk/issues/63
> daily: log transcription errors

- src/dailyai/services/azure_ai_services.py
- src/dailyai/services/elevenlabs_ai_service.py
- src/examples/starter-apps/translator.py
I wanted to add the ability to select a language with a command-line option, but I didn't want to pre-emptively break our ability to deploy these things easily.
> Live translation

- examples/foundational/02-llm-say-one-thing.py
- examples/foundational/05-sync-speech-and-image.py
- examples/foundational/05a-local-sync-speech-and-text.py
- examples/foundational/06-listen-and-respond.py
- examples/foundational/06a-image-sync.py
- examples/foundational/07-interruptible.py
- examples/foundational/10-wake-word.py
- examples/foundational/11-sound-effects.py
- examples/starter-apps/chatbot.py
- examples/starter-apps/patient-intake.py
- examples/starter-apps/storybot.py
- examples/starter-apps/translator.py
> use OPENAI_API_KEY instead of OPENAI_CHATGPT_API_KEY

- examples/foundational/02-llm-say-one-thing.py
- examples/foundational/04-utterance-and-speech.py
- examples/foundational/05-sync-speech-and-image.py
- examples/foundational/06-listen-and-respond.py
- examples/foundational/08-bots-arguing.py
- examples/foundational/10-wake-word.py
- examples/foundational/11-sound-effects.py
- examples/foundational/13a-whisper-local.py
- examples/foundational/websocket-server/sample.py
- examples/internal/11a-dial-out.py
- examples/starter-apps/chatbot.py
- examples/starter-apps/storybot.py
- examples/starter-apps/translator.py
- src/dailyai/pipeline/aggregators.py
- src/dailyai/pipeline/frame_processor.py
- src/dailyai/pipeline/frames.py
- src/dailyai/pipeline/opeanai_llm_aggregator.py
- src/dailyai/pipeline/pipeline.py
- src/dailyai/serializers/protobuf_serializer.py
- src/dailyai/services/ai_services.py
- src/dailyai/services/anthropic_llm_service.py
- src/dailyai/services/local_stt_service.py
- src/dailyai/services/openai_api_llm_service.py
- src/dailyai/transports/daily_transport.py
- tests/test_daily_transport_service.py
- tests/test_protobuf_serializer.py
We had a few Frames that were still called `...QueueFrame`; this cleans those up as well as some comments.
> Cleanup the last few badly-named Frame types

- examples/starter-apps/translator.py
A quick addition for a customer demo.
> Added app messages to translator example

- examples/foundational/03-still-frame.py
- examples/foundational/03a-image-local.py
- examples/foundational/05-sync-speech-and-image.py
- examples/foundational/05a-local-sync-speech-and-text.py
- examples/foundational/08-bots-arguing.py
- examples/starter-apps/storybot.py
- src/dailyai/services/ai_services.py
- src/dailyai/services/azure_ai_services.py
- src/dailyai/services/fal_ai_services.py
- src/dailyai/services/open_ai_services.py
> Updated Fal.ai service to take a params model and allow for model string param

- examples/moondream-chatbot/Dockerfile.intel
- examples/moondream-chatbot/README.md
- src/pipecat/services/moondream.py
Extending Moondream to support Intel GPUs as well.
- Added a new dockerfile for intel with intel gpus and drivers
- Modified the device selection function
- Updated Readme
> (feat): adding intel gpus support

- CHANGELOG.md
- pyproject.toml
- src/pipecat/services/ai_services.py
- src/pipecat/utils/audio.py
- src/pipecat/vad/vad_analyzer.py
https://github.com/csteinmetz1/pyloudnorm
> interruptions: introduce pyloudnorm to compute loudness

- CHANGELOG.md
- examples/foundational/10-wake-word.py
- examples/foundational/14-wake-phrase.py
- src/pipecat/frames/frames.py
- src/pipecat/processors/filters/frame_filter.py
- src/pipecat/processors/filters/wake_check_filter.py
- src/pipecat/processors/frame_processor.py
Would appreciate feedback on a new wake word implementation. I think this is probably useful enough to be a core class, but I'm not sure where to put it in the directory/file structure.
> Improved wake word filter

- CHANGELOG.md
- examples/foundational/07a-interruptible-anthropic.py
- examples/foundational/12c-describe-video-anthropic.py
- src/pipecat/services/anthropic.py
Similar to Google Gemini work last week.
> add new response frame types and vision support for anthropic

- CHANGELOG.md
- examples/foundational/07c-interruptible-deepgram.py
- src/pipecat/services/deepgram.py
Small fixes to Deepgram TTS service.
> moving Deepgram TTS base_url from beta to prod

- examples/foundational/07d-interruptible-cartesia.py
- macos-py3.10-requirements.txt
- pyproject.toml
- src/pipecat/services/cartesia.py
- src/pipecat/services/deepgram.py
- src/pipecat/services/elevenlabs.py
- src/pipecat/services/google.py
- added Cartesia TTS support
- additional try/except blocks in deepgram and google services
> Cartesia TTS

- CHANGELOG.md
> Added cartesia line to CHANGELOG.md

- src/pipecat/services/ai_services.py
We need this for EHR Voice Assistant that talks to "Dr. Bailey" all the time. :)
> fixed "Dr." interruption

- examples/twilio-chatbot/bot.py
- examples/twilio-chatbot/server.py
- src/pipecat/serializers/twilio.py
- src/pipecat/transports/network/fastapi_websocket.py
This is an error while handling multiple calls with sending RawAudioFrames to correct streamSid via transport.output()
> Fix twilio error

- CHANGELOG.md
- src/pipecat/frames/frames.py
- src/pipecat/pipeline/task.py
- src/pipecat/processors/frame_processor.py
- src/pipecat/services/ai_services.py
- src/pipecat/services/openai.py
- src/pipecat/transports/services/daily.py
- src/pipecat/vad/silero.py
Processing metrics indicate how much time a processor takes to generate all of its output.
> add support for processing metrics

- pyproject.toml
- src/pipecat/services/xtts.py
Resending the PR for adding the service XTTS.
Reviewed and added all suggestions.
I tested all fixes locally.
> Added service XTTS

- src/pipecat/services/ai_services.py
- tests/test_ai_services.py
* end of sentence as a regex pattern
* Detects more non-sentence ending patterns
> fix: No more falsely detect a sentence end on "U.S.A", "3:00 a.m." 

- src/pipecat/services/openai.py
Rather than expiring in 5 seconds.
> Allow openai http connections to remain open in the pool indefinitely.

- CHANGELOG.md
- src/pipecat/transports/services/daily.py
> transports(daily): wait until start|stop_transcription are finished

- CHANGELOG.md
- src/pipecat/services/elevenlabs.py
> services(elevenlabs): update default model to eleven_turbo_v2_5

- CHANGELOG.md
- src/pipecat/transports/services/daily.py
> transports(daily): added on_participant_updated event

- CHANGELOG.md
- src/pipecat/transports/services/helpers/daily_rest.py
> transports(daily): fixed create_room expirations

- CHANGELOG.md
- src/pipecat/serializers/twilio.py
- src/pipecat/services/elevenlabs.py
- src/pipecat/utils/audio.py
> twilio and elevenlabs sample rates

- examples/foundational/19a-tools-anthropic.py
- examples/foundational/19b-tools-video-anthropic.py
- src/pipecat/services/anthropic.py
> Fixup anthropic context set_messages

- src/pipecat/services/anthropic.py
My code was inserting image messages into the Anthropic context without paying enough attention to sequencing. I think that recent refactoring of the contexts/tools logic made this code path do the wrong thing more often. Often enough that it was easy to repro and fix!
> fix for out-of-order image messages in anthropic context

- src/pipecat/frames/frames.py
- src/pipecat/transports/base_input.py
- src/pipecat/vad/vad_analyzer.py
Make VADParams settable at runtime. The motivation is to make VADParams configurable for RTVI clients.
> VADParamsUpdateFrame and handling thereof

- src/pipecat/processors/frameworks/rtvi.py
- src/pipecat/transports/services/daily.py
This reverts commit 47d375309dfc72213fa5cad84e0974f223f3ae76.
> Revert "transports(daily): use aliases in DailyDialinSettings"

- src/pipecat/processors/frameworks/rtvi.py
- src/pipecat/processors/gstreamer/pipeline_source.py
- src/pipecat/transports/base_input.py
- src/pipecat/transports/base_output.py
> StartFrame should be the first frame every processor receives

- CHANGELOG.md
- src/pipecat/transports/base_transport.py
- src/pipecat/transports/services/daily.py
> transports(daily): allow setting audio output bitrate (default 96kpbs)

- src/pipecat/services/ai_services.py
- src/pipecat/services/azure.py
- src/pipecat/services/cartesia.py
- src/pipecat/services/elevenlabs.py
- src/pipecat/services/lmnt.py
- src/pipecat/services/openai.py
- src/pipecat/services/playht.py
Adds support for specifying a `sample_rate` for TTS services.
Additionally, adds support to set_voice for PlayHT.
> Add sample_rate setting to TTS services

- src/pipecat/transports/services/daily.py
Serialization issue fix for an oddly non-universal bug. (Maybe a pydantic or python version issue?)
> fixup for serialization issue

- src/pipecat/frames/frames.py
Branch from https://github.com/pipecat-ai/pipecat/pull/486.
> Add control frames for LLM config params

- src/pipecat/frames/frames.py
This is https://github.com/pipecat-ai/pipecat/pull/486 but merging to main 🤦
> Add control frames for LLM param updates

- examples/foundational/07d-interruptible-elevenlabs.py
- src/pipecat/services/elevenlabs.py
Adds voice_settings:
- stability
- similarity_boost
- style
- use_speaker_boost
Adds optimize_streaming_latency, which is deprecated, but still used by ElevenLabs in their products, including recent product launches.
> Add voice_settings and optimize_streaming_latency to ElevenLabs

- src/pipecat/services/azure.py
Adds support for a number of the [SSML properties](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-synthesis-markup-structure).
> Add Azure TTS input params

- CHANGELOG.md
- examples/foundational/05-sync-speech-and-image.py
- examples/foundational/05a-local-sync-speech-and-image.py
- src/pipecat/pipeline/sync_parallel_pipeline.py
- src/pipecat/pipeline/task.py
- src/pipecat/processors/frame_processor.py
- src/pipecat/processors/frameworks/rtvi.py
- src/pipecat/processors/gstreamer/pipeline_source.py
- src/pipecat/processors/idle_frame_processor.py
- src/pipecat/processors/user_idle_processor.py
- src/pipecat/services/ai_services.py
- src/pipecat/services/cartesia.py
- src/pipecat/services/elevenlabs.py
- src/pipecat/services/gladia.py
- src/pipecat/services/lmnt.py
- src/pipecat/transports/base_input.py
- src/pipecat/transports/base_output.py
- tests/test_langchain.py
In this commit we make all frame processors asynchronous, that is, they have an
internal queue and they push frames using a task from that queue.
> all frame processors are asynchrnous

- src/pipecat/services/ai_services.py
Small fix necessitated by fixing TTS sentence aggregation. :-)
> fix for multi-sentence tts say utterances

- src/pipecat/services/aws.py
- src/pipecat/services/elevenlabs.py
The linter (and human) missed this one.
> Fix nested strings issue

- examples/translation-chatbot/requirements.txt
aiohttp is not included but uded in code
> Update requirements.txt aiohttp missing

- examples/storytelling-chatbot/src/bot.py
- src/pipecat/processors/aggregators/openai_llm_context.py
- src/pipecat/services/ai_services.py
- src/pipecat/services/cartesia.py
- src/pipecat/services/deepgram.py
- src/pipecat/services/elevenlabs.py
- src/pipecat/services/openai.py
- src/pipecat/vad/vad_analyzer.py
Reviewed different log types and made adjustments to keep noisy or sensitive data in debug and info and error as loggable data.
> Adjust log levels for log messages

- CHANGELOG.md
- examples/foundational/07-interruptible-vad.py
- examples/foundational/07c-interruptible-deepgram.py
- examples/foundational/19-openai-realtime-beta.py
- src/pipecat/services/ai_services.py
This is useful to add an `AudioBufferProcessor` down the pipeline to record the conversation.
> allow STT services to passthrough audio frames

- src/pipecat/services/google.py
Adds usage metrics for token input and output counts.
> Add Gemini token usage metrics

- src/pipecat/services/google.py
Adding the four input params that Gemini supports:
- `temperature`
- `top_p`
- `top_k`
- `max_output_tokens`
> Add input params to Google Gemini

- examples/canonical-metrics/README.md
> docs: small fix

- src/pipecat/services/playht.py
This uses PlayHT's request_id feature. It:
- Creates a new UUID for each bot turn and keeps that ID consistent for the turn
- When the turn ends, the request_id is reset
> Add a request_id to each TTS sequence

- examples/simple-chatbot/server.py
> Load dotenv in simple chatbot server (fixes #415)

- .github/workflows/format.yaml
- pyproject.toml
Currently we're specifying config parameters inline, this PR sets them in the project config instead.
> Set Ruff config for the project

- CHANGELOG.md
- examples/foundational/22-natural-conversation.py
- src/pipecat/processors/aggregators/gated_openai_llm_context.py
- src/pipecat/processors/filters/frame_filter.py
- src/pipecat/processors/filters/null_filter.py
- src/pipecat/processors/filters/wake_notifier_filter.py
- src/pipecat/sync/base_notifier.py
- src/pipecat/sync/event_notifier.py
> add notifiers and more frame filters

- src/pipecat/transports/services/daily.py
Daily supports recording. Adding these events and callbacks help to take programmatic action once a recording is started, stopped, or errors.
> Add recording events and callbacks

- src/pipecat/processors/frameworks/rtvi.py
> rtvi: bot-ready message needs to be sent manual

- src/pipecat/transports/services/daily.py
> transports(daily): call on_transcription_message event handler

- CHANGELOG.md
Update CHANGELOG for 0.0.48. I dedicate this release to my dad!
> update CHANGELOG for 0.0.48

- src/pipecat/services/openai_realtime_beta/openai.py
> tiny PR to remove old comment lines

- README.md
The README now points to the guide in the docs.
> Update Krisp README instructions

- README.md
An aesthetic change to the README
> Add visual divider below Pipecat README image

- examples/simple-chatbot/bot.py
This example has fallen behind on recent changes. It needed:
- To trigger the speaking animations on BotStartedSpeakingFrame, BotStoppedSpeakingFrame
- push the frame with a direction in the TalkingAnimation processor
- await transport.capture_participant_transcription
> Fix simple-chatbot example

- CHANGELOG.md
> update CHANGELOG for 0.0.49

- examples/foundational/22c-natural-conversation-mixed-llms.py
This example now uses Claude Sonnet 3.5 for the statement_llm and gpt-4o for the response llm. The prompt is also improved.
Also, renamed the file to reflect that we're mixing LLMs in this approach.
> Improve the 22c foundational example

- src/pipecat/processors/frame_processor.py
> internal push frame fix

- src/pipecat/processors/frame_processor.py
This pushes an ErrorFrame in the frame processor to restart the pipeline so we don't get caught in a "stuck" state with interruptions.
Fixes issue #721.
> fix: catch and handle OpenAI errors

- src/pipecat/transports/services/daily.py
Warns the user about a possible missing room token if transcription is enabled.
> transports(daily): warn if transcription enabled but no token provided

- .gitignore
- examples/twilio-chatbot/README.md
- examples/twilio-chatbot/templates/streams.xml
- examples/twilio-chatbot/templates/streams.xml.template
Small clarifications to the README as I went through testing this example.
> Improve twilio-chatbot README

- src/pipecat/frames/frames.py
- src/pipecat/serializers/protobuf.py
> frames: fix AudioRawFrame mixin

- examples/foundational/18-gstreamer-filesrc.py
- src/pipecat/processors/gstreamer/pipeline_source.py
> gstreamer: update default sample rate to 24000

- pyproject.toml
> Upgrade Anthropic to the latest to avoid collision with aiohttp 3.11.9

- CHANGELOG.md
- src/pipecat/services/cartesia.py
- src/pipecat/services/deepgram.py
- src/pipecat/services/elevenlabs.py
- src/pipecat/services/lmnt.py
- src/pipecat/services/playht.py
Improves reconnection logging for multiple TTS services. Before, if an error occurred no reconnection was taking place.
> services: improve Cartesia, 11Labs, PlayHT and LMNT TTS reconnection

- CHANGELOG.md
- examples/foundational/07i-interruptible-xtts.py
- src/pipecat/services/xtts.py
> services(xtts): default language to Language.EN

- src/pipecat/services/cartesia.py
> cartesia: fix broken interruptions

- src/pipecat/frames/frames.py
> frames: FunctionCallResultFrame should be a DataFrame as before

- src/pipecat/processors/frameworks/rtvi.py
> rtvi: handle transport urgent frames

- src/pipecat/transports/services/daily.py
Commit [37c21426](https://github.com/pipecat-ai/pipecat/commit/37c21426bf4607b4a29e1e751018f83ed5d4fc0c) introduced a double-join bug for the Daily transport, when a `ParallelPipeline` is used.
An easy way to see the bug or test a fix is to use `examples/foundational/25-google-audio-in.py`.
This is a proposed fix. Deferring to @aconchillo as to whether this is the correct fix.
> Check to avoid double-join in ParallelPipeline case

- CHANGELOG.md
- examples/foundational/24-stt-mute-filter.py
- src/pipecat/processors/aggregators/openai_llm_context.py
- src/pipecat/processors/filters/stt_mute_filter.py
Prompted by a request from Discord. See Changelog for details.
> Add new STT mute strategy, accept a set of strategies

- docs/api/conf.py
- docs/api/requirements.txt
We want to host on Read the Docs. They need the build steps to happen in conf.py, not a separate generate script. This PR makes those changes. This works locally with sphinx, so hopefully the same is true on Read the Docs. 🤞
> Changes for Read the Docs hosting

- CHANGELOG.md
- src/pipecat/processors/filters/identity_filter.py
> processors(filters): add IdentityFilter

- src/pipecat/processors/frameworks/rtvi.py
> rtvi: update protocol version to 0.3.0

- src/pipecat/serializers/protobuf.py
This fixes https://github.com/pipecat-ai/pipecat/issues/811
> fix: make ProtobufFrameSerializer backwards compatible

- CHANGELOG.md
- examples/foundational/01c-fastpitch.py
- examples/foundational/07r-interruptible-riva-nim.py
- src/pipecat/services/riva.py
> riva: rename FastpitchTTSService to FastPitchTTSService

- examples/foundational/15a-switch-languages.py
> examples: fix 15a-switch-languages pipeline

- src/pipecat/services/openpipe.py
> services(openpipe): use OpenAILLMService to get access to aggregators

- src/pipecat/pipeline/parallel_pipeline.py
The previous fixes didn't take into account that system frames can be generated inside the internal pipelines.
> parallel_pipeline: fix system frames and parallel pipelines again

- examples/moondream-chatbot/bot.py
- examples/studypal/studypal.py
> examples: fixes for moondream-chatbot and studypal

- CHANGELOG.md
- src/pipecat/services/elevenlabs.py
- src/pipecat/services/playht.py
> tts: support more languages in playht and elevenlabs

- CHANGELOG.md
- examples/foundational/07m-interruptible-polly.py
- src/pipecat/services/aws.py
> polly: renamed AWSTTSService to PollyTTSService

- src/pipecat/services/ai_services.py
> AIService: add missing super().process_frame()

- CHANGELOG.md
- src/pipecat/services/riva.py
> riva: fix FastPitchTTSService audio stuttering

- CHANGELOG.md
- src/pipecat/services/elevenlabs.py
- Made `auto_mode` and input parameter
- Made `eleven_flash_v2_5` the default model
- Updated the language logic to permit specific models to provide a language
> Added an `auto_mode` input parameter to `ElevenLabsTTSService`

- examples/simple-chatbot/server/bot-gemini.py
- examples/simple-chatbot/server/bot-openai.py
> Add an RTVIProcessor to the simple-chatbot pipeline

- CHANGELOG.md
- src/pipecat/processors/frame_processor.py
> frame_processor: reset input queue flag with interruptions

- CHANGELOG.md
- examples/foundational/07n-interruptible-google.py
- src/pipecat/services/google.py
Journey voices don't support SSML.
> Added support for Google Journey TTS voices

- examples/deployment/modal-example/requirements.txt
Updates the dependencies for modal demo.
> docs: update dependencies for modal demo

- examples/simple-chatbot/examples/ios/SimpleChatbot.xcodeproj/project.pbxproj
- examples/simple-chatbot/examples/ios/SimpleChatbot.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- examples/simple-chatbot/examples/ios/SimpleChatbot/model/CallContainerModel.swift
See commit messages for details. This fix was already made to https://github.com/pipecat-ai/pipecat-client-ios-gemini-live-websocket-demo, when adapting the SimpleChatbot demo.
> iOS SimpleChatbot @MainActor fixes

- examples/simple-chatbot/examples/ios/README.md
> fixed 404 in SimpleChatbot iOS example README

- CHANGELOG.md
- src/pipecat/services/aws.py
https://github.com/pipecat-ai/pipecat/issues/964
> Add optional aws_session_token for PollyTTSService

- .github/workflows/android.yaml
We should only run the android workflow if there are any changes to the android client.
> github: only run android simple-chatbot worflow if android example modified

- CHANGELOG.md
- src/pipecat/pipeline/task.py
Forgot to cleanup the sink processor. Fixes #953.
> pipeline(task): cleanup Sink processor

- examples/simple-chatbot/client/ios/SimpleChatbot.xcodeproj/project.pbxproj
- examples/simple-chatbot/client/ios/SimpleChatbot.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- examples/simple-chatbot/client/ios/SimpleChatbot/model/CallContainerModel.swift
- examples/simple-chatbot/client/ios/SimpleChatbot/model/MockCallContainerModel.swift
- examples/simple-chatbot/client/ios/SimpleChatbot/views/settings/SettingsView.swift
Using PipecatClientIOS instead of RTVIClientIOS
> Using PipecatClient version 0.3.2

- examples/simple-chatbot/client/javascript/package-lock.json
- examples/simple-chatbot/client/javascript/package.json
- examples/simple-chatbot/client/javascript/src/app.js
- examples/simple-chatbot/client/react/package-lock.json
- examples/simple-chatbot/client/react/package.json
- examples/simple-chatbot/client/react/src/App.tsx
- examples/simple-chatbot/client/react/src/components/ConnectButton.tsx
- examples/simple-chatbot/client/react/src/components/DebugDisplay.tsx
- examples/simple-chatbot/client/react/src/components/StatusDisplay.tsx
- examples/simple-chatbot/client/react/src/providers/RTVIProvider.tsx
> Update simple-chatbot example to use the latest client SDKs

- src/pipecat/services/cerebras.py
- src/pipecat/services/deepseek.py
> Fix error log in DeepSeekLLMService and CerebrasLLMService

- .pre-commit-config.yaml
- README.md
- dev-requirements.txt
- pyproject.toml
- scripts/pre-commit.sh
> add pre-commit hooks

- examples/simple-chatbot/client/ios/SimpleChatbot/model/CallContainerModel.swift
- examples/simple-chatbot/client/ios/SimpleChatbot/views/settings/SettingsView.swift
This simply applies [these improvements to the Gemini Live WebSocket demo](https://github.com/pipecat-ai/pipecat-client-ios-gemini-live-websocket-demo/pull/4) to this demo as well.
> iOS SimpleChatbot assorted improvements

- src/pipecat/processors/frame_processor.py
- src/pipecat/services/cartesia.py
- src/pipecat/services/tavus.py
- src/pipecat/transports/base_input.py
> additional trace logging

- CHANGELOG.md
- examples/foundational/30-observer.py
Adding this so there's an easy to find Observer example. Also, the Observer is such a great addition!
> Add foundational example 30 to show how to use an Observer

- examples/translation-chatbot/bot.py
- examples/translation-chatbot/server.py
Updates the translator bot to do the following:
- Allow you to specify the in and out languages
- Uses TranscriptionProcessor to handle transcriptions
> demo: Update translator bot example

- examples/foundational/30-observer.py
> Add a second observer to the 30-observer.py example

- CHANGELOG.md
- src/pipecat/processors/user_idle_processor.py
> Start UserIdleProcessor on speaking frame, fix bug not pushing EndFrame

- src/pipecat/audio/utils.py
> ulaw resample update

- pyproject.toml
- src/pipecat/services/fish.py
> services(fish): FishAudioTTSService to use WebsocketService

- CHANGELOG.md
- README.md
> update CHANGELOG for 0.0.53

- CHANGELOG.md
- src/pipecat/services/elevenlabs.py
> Fixed a type error when using voice_settings in ElevenLabsHttpTTSService

- src/pipecat/processors/frameworks/rtvi.py
Ignoring transport messages that are not intended to RTVI.
Fixes https://github.com/pipecat-ai/pipecat/issues/1040
> Ignoring transport messages that are not intended to RTVI.

- src/pipecat/processors/frame_processor.py
> Fix trace log line for resume_processing_frames

- CHANGELOG.md
- src/pipecat/services/openai_realtime_beta/context.py
Resolves https://github.com/pipecat-ai/pipecat/issues/1063.
I missed adding `OpenAIRealtimeBetaLLMService` when making the change in #970.
> OpenAIRealtimeBetaLLMService: Fixed an error in function calling

- src/pipecat/services/canonical.py
I accidentally removed a much needed import in my previous PR. This PR adds it back.
> Fixing missing import

- src/pipecat/services/openai.py
Sometimes the chunk.choices is None, and I got exception like: 
```
TypeError: object of type 'NoneType' has no len()
```
> [bug]TypeError: object of type 'NoneType' has no len()

- CHANGELOG.md
- src/pipecat/processors/audio/audio_buffer_processor.py
Fixed an issue in AudioBufferProcessor where the last audio buffer was not being processed if the _user_audio_buffer was smaller than the buffer size.
> adding missing audio buffer fix

- CHANGELOG.md
- src/pipecat/transports/services/helpers/daily_rest.py
This PR introduces the following changes:
- **DailyMeetingTokenProperties and DailyMeetingTokenParams**: New Pydantic models for structured meeting token creation.
- **get_token_v2 method**: Added to `DailyTransport` for generating meeting tokens with `DailyMeetingTokenParams`.
- **enable_recording and geo parameters**: Added to `DailyRoomProperties` for better control over room recordings and geographic settings.
- **RecordingsBucketConfig**: Integrated into `DailyRoomProperties` to support uploading recordings to custom AWS S3 buckets.
These changes enhance the flexibility and functionality of the Daily integration, enabling more robust meeting token generation, recording controls, and custom storage options.
> adding models to DailyRestHelper

- examples/news-chatbot/.gitignore
- examples/news-chatbot/README.md
- examples/news-chatbot/client/javascript/README.md
- examples/news-chatbot/client/javascript/index.html
- examples/news-chatbot/client/javascript/package-lock.json
- examples/news-chatbot/client/javascript/package.json
- examples/news-chatbot/client/javascript/src/app.js
- examples/news-chatbot/client/javascript/src/style.css
- examples/news-chatbot/client/javascript/vite.config.js
- examples/news-chatbot/server/README.md
- examples/news-chatbot/server/env.example
- examples/news-chatbot/server/news_bot.py
- examples/news-chatbot/server/requirements.txt
- examples/news-chatbot/server/runner.py
- examples/news-chatbot/server/server.py
- src/pipecat/processors/frameworks/rtvi.py
- src/pipecat/services/google/frames.py
- src/pipecat/transports/services/helpers/daily_rest.py
Sending Search Response to RTVI and creating an example that renders the search response.
> Sending Search Response to RTVI

- CHANGELOG.md
> prepare CHANGELOG for 0.0.54

- CHANGELOG.md
- src/pipecat/services/openai.py
> Add organization and project level auth in OpenAILLMService

- CHANGELOG.md
- examples/twilio-chatbot/README.md
- examples/twilio-chatbot/bot.py
- examples/twilio-chatbot/client.py
- examples/twilio-chatbot/server.py
> examples: multiple twilio-chatbot improvements

- src/pipecat/audio/filters/krisp_filter.py
Fixing the issue in Krisp when trying to create more than one krispAudioProcessor.
> Fixing the issue in Krisp when trying to create more than one

- CHANGELOG.md
> update CHANGELOG for 0.0.55

- src/pipecat/processors/frame_processor.py
> FrameProcessor: add an error about missing super().process_frame(...)

- src/pipecat/transports/base_input.py
When interruptions was disabled we were not logging user started/stopped speaking.
> BaseInputTransport: show VAD results when interruptions not allowed

- CHANGELOG.md
- src/pipecat/transports/base_output.py
> BaseOutputTransport: resample incoming audio if needed

- src/pipecat/pipeline/task.py
Adding some docstrings for better auto-generated docs, specifically for PipelineParams. Updated a few other areas while I was here.
> Add docstrings for PipelineTask and related classes/functions

- CHANGELOG.md
- examples/foundational/07s-interruptible-google-audio-in.py
- examples/foundational/12a-describe-video-gemini-flash.py
- examples/foundational/14e-function-calling-gemini.py
- examples/foundational/20d-persistent-context-gemini.py
- examples/foundational/22d-natural-conversation-gemini-audio.py
- examples/foundational/25-google-audio-in.py
- src/pipecat/services/google/google.py
> Use gemini-2.0-flash-001 as the default model for GoogleLLMService

- CHANGELOG.md
- src/pipecat/tests/utils.py
> tests: remove logger from tests.utils

- CHANGELOG.md
- src/pipecat/transports/local/audio.py
- src/pipecat/transports/local/tk.py
> update CHANGELOG for 0.0.56

- src/pipecat/transports/local/audio.py
This change allows the user to configure input_device_index and output_device_index for local audio transport.
> adds configurable device ids for local audio transport

- src/pipecat/transports/services/daily.py
For better docs auto-generation.
> Add docstrings to daily.py

- CHANGELOG.md
- src/pipecat/processors/frameworks/rtvi.py
> RTVI: fix premature bot-tts-text messages

- CHANGELOG.md
- src/pipecat/services/whisper.py
> Add language support to WhisperSTTService

- src/pipecat/services/base_whisper.py
- src/pipecat/services/groq.py
- src/pipecat/services/openai.py
- src/pipecat/transcriptions/language.py
> Add language support to OpenAI and Groq hosted Whisper

- CHANGELOG.md
- src/pipecat/services/azure.py
In response to this issue: https://github.com/pipecat-ai/pipecat/issues/731.
It's a first step to gathering more information about the CancellationError, plus some other robustness clean up around the start() sequence and creating the `_speech_synthesizer`.
> Improve AzureTTSService error handling

- CHANGELOG.md
- examples/twilio-chatbot/bot.py
- examples/twilio-chatbot/client.py
- src/pipecat/processors/audio/audio_buffer_processor.py
We need two different strategies to record audio properly depending if user audio is continuous or intermittent.
Fixes #1172
> AudioBufferProcessor: handle continuous and intermittent user audio

- .github/workflows/coverage.yaml
- README.md
- dev-requirements.txt
- pyproject.toml
> github: add coverage support

- src/pipecat/services/simli.py
> simli: fix audio layout error

- src/pipecat/transports/network/websocket_server.py
- src/pipecat/transports/services/daily.py
Preventing from trying to join twice when using ParallalePipeline.
> Pipecat improvements for the instant voice demo

- src/pipecat/frames/frames.py
- src/pipecat/processors/filters/stt_mute_filter.py
- src/pipecat/services/ai_services.py
- tests/test_stt_mute_filter.py
This PR:
- Changes `STTMuteFrame` from `ControlFrame` to `SystemFrame`. We want the STTMuteFrame to not be queued.
- With changing `STTMuteFrame` to `ControlFrame`, the frame processing ordering needs to change. This PR ensures that the frames are correctly ordered.
- Confirmed ordering via new unit tests: There is a missing test for the `FUNCTION_CALL` strategy due to more test utils that need to be added. I listed that as a TODO.
I don't think any of this warrants a changelog entry. Happy to add one if it helps.
> Improve STTMuteFilter, add tests

- CHANGELOG.md
- src/pipecat/processors/frameworks/rtvi.py
- src/pipecat/transports/base_input.py
- src/pipecat/transports/base_transport.py
- src/pipecat/transports/network/fastapi_websocket.py
- src/pipecat/transports/network/websocket_server.py
- src/pipecat/transports/services/daily.py
> Instant voice demo improvements - part 02

- src/pipecat/tests/utils.py
- tests/test_user_idle_processor.py
This adds the new tests/util.py from: https://github.com/pipecat-ai/pipecat/pull/1209. And uses the SleepFrame() for timing related operations to test the UserIdleProcessor.
> Add UserIdleProcessor tests

- src/pipecat/tests/utils.py
- test-requirements.txt
- tests/test_markdown_text_filter.py
> Add MarkdownTextFilter tests

- CHANGELOG.md
- src/pipecat/services/ai_services.py
- src/pipecat/services/cartesia.py
- src/pipecat/services/rime.py
We add a new `AudioContextWordTTSService`. This is a TTS base class for TTS services that handling multiple separate audio requests.
We use the new  `AudioContextWordTTSService` in `CartesiaTTSService` which fixes audio overlapping since it's now possible to send multiple requests at once.
> audio context tts service and cartesia fixes

- tests/test_transcript_processor.py
> tests: add tests for TranscriptProcessor

- CHANGELOG.md
- examples/foundational/01a-local-audio.py
- examples/foundational/06a-image-sync.py
- examples/foundational/13a-whisper-local.py
- examples/local-input-select-stt/bot.py
- src/pipecat/processors/aggregators/llm_response.py
- src/pipecat/processors/frame_processor.py
- src/pipecat/services/ai_services.py
- src/pipecat/services/cartesia.py
- src/pipecat/services/elevenlabs.py
- src/pipecat/services/fal.py
- src/pipecat/services/fish.py
- src/pipecat/services/lmnt.py
- src/pipecat/services/playht.py
- src/pipecat/services/rime.py
- src/pipecat/transports/local/audio.py
- src/pipecat/transports/local/tk.py
- src/pipecat/utils/string.py
- tests/test_utils_string.py
> update CHANGELOG for 0.0.57

- CHANGELOG.md
- src/pipecat/services/websocket_service.py
- src/pipecat/utils/network.py
- tests/test_utils_network.py
> network: added exponential_backoff_time() function

- CHANGELOG.md
- src/pipecat/services/deepgram.py
> deepgram: use the new nova-3 model as default

- CHANGELOG.md
- src/pipecat/transports/services/daily.py
> daily: add room_url property

- CHANGELOG.md
- examples/foundational/14e-function-calling-gemini.py
- src/pipecat/services/ai_services.py
- src/pipecat/services/openai.py
Fixed an issue that `start_callback` was not invoked for some LLM services.
> Fixed an issue that `start_callback` was not invoked for some LLM services

- examples/phone-chatbot/README.md
- examples/phone-chatbot/bot_daily.py
- examples/phone-chatbot/bot_daily_gemini.py
- examples/phone-chatbot/bot_runner.py
> Updated example to use Gemini

- CHANGELOG.md
- src/pipecat/utils/string.py
- tests/test_utils_string.py
> utils: add support for ellipses in match_endofsentence()

- tests/test_utils_string.py
Adding one more ellipsis test case to match a different format that the LLM will produce.
> Add one additional ellipsis test to test_utils_string

- CHANGELOG.md
- src/pipecat/services/ai_services.py
- src/pipecat/services/anthropic.py
- src/pipecat/services/google/google.py
- src/pipecat/services/openai.py
> services(llm): add on_completion_timeout event

- CHANGELOG.md
- src/pipecat/services/google/google.py
> google: updgrade OpenAILLMContext to GoogleLLMContext

- CHANGELOG.md
- src/pipecat/pipeline/task.py
> PipelineTask: add check_dangling_tasks parameter

- examples/foundational/30-observer.py
This example needs to be updated to align with https://github.com/pipecat-ai/pipecat/pull/1282.
> Example 30: Move observers to PipelineTask

- CHANGELOG.md
- src/pipecat/__init__.py
> log pipecat version on application startup

- CHANGELOG.md
- src/pipecat/services/playht.py
This change is backwards compatible by parsing the protocol from the voice_engine, if provided.
> PlayHTHttpTTSService now takes a separate protocol input

- examples/foundational/07d-interruptible-elevenlabs-http.py
- examples/foundational/07q-interruptible-rime-http.py
- src/pipecat/services/elevenlabs.py
- src/pipecat/services/openai.py
- src/pipecat/services/playht.py
- src/pipecat/services/rime.py
- src/pipecat/services/xtts.py
- src/pipecat/transports/base_output.py
> small TTS http improvements

- CHANGELOG.md
- examples/foundational/22d-natural-conversation-gemini-audio.py
- examples/phone-chatbot/bot_daily_gemini.py
- pyproject.toml
- src/pipecat/services/google/google.py
It seems that sometimes, if we send inline audio data and no text part, everything will be fine. However, sometimes Google libraries just complain.
According to https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference#request text/inline_data/file_dat is a union. Maybe it's only true in the HTTP API.
> GoogleLLMService: always send text with audio

- pyproject.toml
> pyproject: update daily-python, aiohttp and pydantic

- CHANGELOG.md
- examples/foundational/34-audio-recording.py
- src/pipecat/processors/audio/audio_buffer_processor.py
In building out the EOD bot, I have a need for this. I would imagine separate tracks would be handy for others too.
Also, I added a foundational example (34) showing how to use the different callbacks to record merged and track audio.
I cleaned up docstrings while I was at it.
> Added on_track_audio_data callback to AudioBufferProcessor for track level recording

- CHANGELOG.md
> update CHANGELOG for 0.0.58

- examples/foundational/22d-natural-conversation-gemini-audio.py
> examples: fix for 22d-natural-conversation-gemini-audio.py

- CHANGELOG.md
- src/pipecat/frames/frames.py
- src/pipecat/processors/frameworks/rtvi.py
Here's the client-side of this work: https://github.com/pipecat-ai/pipecat-client-web/pull/95.
The goal is to make server to client messaging easier.
> Add a new generic server to client message and frame type

- examples/canonical-metrics/bot.py
- src/pipecat/services/canonical.py
Updating the canonical client so that the audio recording is optional as long as there is a transcript.
> Optional Recording

- src/pipecat/services/anthropic.py
- src/pipecat/services/aws.py
- src/pipecat/services/azure.py
- src/pipecat/services/cartesia.py
- src/pipecat/services/deepgram.py
- src/pipecat/services/elevenlabs.py
- src/pipecat/services/fish.py
- src/pipecat/services/google/google.py
- src/pipecat/services/lmnt.py
- src/pipecat/services/openai.py
- src/pipecat/services/playht.py
- src/pipecat/services/rime.py
- src/pipecat/services/riva.py
- src/pipecat/services/xtts.py
Minor logging improvements so we can tell which processor is doing what (e.g. in the case you have 3 LLMs like in the 22 examples series).
> services: minor LLM and TTS logging improvements

- CHANGELOG.md
- examples/foundational/14o-function-calling-gemini-openai-format.py
- src/pipecat/services/google/google.py
GoogleLLMOpenAIBetaService supports google gemini models with openai format
> adding GoogleLLMOpenAIBetaService

- CHANGELOG.md
- src/pipecat/processors/aggregators/llm_response.py
- tests/test_llm_response.py
We used to have this processor. It is now simpler and had an event handler. I've seen people trying to get the LLM completion before the TTS.
> add new LLMFullResponseAggregator

- examples/foundational/19a-azure-realtime-beta.py
- src/pipecat/services/openai_realtime_beta/__init__.py
- src/pipecat/services/openai_realtime_beta/azure.py
New `AzureRealtimeBetaLLMService` that subclasses `OpenAIRealtimeBetaLLMService` to adjust the `_connect()` method for Azure's WebSocket URL format.
> Support for Azure OpenAI Realtime API

- CHANGELOG.md
- src/pipecat/services/elevenlabs.py
In addition, did some cleanup by creating a common function to build the voice settings dictionary.
> Add speed as InputParam to ElevenLabs TTS services

- CHANGELOG.md
> CHANGELOG.md entry for AzureRealtimeBetaLLMService

- CHANGELOG.md
Changelog entry for: https://github.com/pipecat-ai/pipecat/pull/1353
> Changelog entry for Cartesia model update

- CHANGELOG.md
- src/pipecat/services/google/google.py
Like Journey voices, Chirp voices don't support SSML.
Issue: https://github.com/pipecat-ai/pipecat/issues/1337
> Add support for Chirp voices in GoogleTTSService

- CHANGELOG.md
- src/pipecat/services/fish.py
> Add flush_audio to FishTTSService

- CHANGELOG.md
- src/pipecat/services/lmnt.py
> Add flush_audio() to LmntTTSService

- CHANGELOG.md
- src/pipecat/services/google/google.py
Also, adds a flush_audio() method to GoogleTTSService, which is a no-op.
> Add a set_language convenience method for GoogleSTTService

- src/pipecat/services/ai_services.py
I have also reviewed all other `@abstractmethod` uses in the repo and I believe everything makes sense!
> ai_services: fix abstractmethod issues

- src/pipecat/services/neuphonic.py
Added 5 new languages to Neuphonic service. I am an engineer at Neuphonic.
Related PR for docs: https://github.com/pipecat-ai/docs/pull/155
> Added 5 new languages for Neuphonic: FR, PT, RU, ZH, HI.

- CHANGELOG.md
- src/pipecat/pipeline/runner.py
- src/pipecat/pipeline/task.py
- src/pipecat/processors/frame_processor.py
- src/pipecat/transports/network/fastapi_websocket.py
- src/pipecat/transports/network/websocket_client.py
- src/pipecat/transports/network/websocket_server.py
- src/pipecat/transports/services/daily.py
- src/pipecat/transports/services/livekit.py
- src/pipecat/utils/base_object.py
All event handlers are now executed in separate tasks in order to prevent blocking the pipeline. It is possible that event handlers take some time to execute in which case the pipeline would be blocked waiting for the event handler to complete.
> event handlers are now executed in separate tasks

- CHANGELOG.md
- examples/foundational/14j-function-calling-nim.py
- examples/foundational/35-pattern-pair-voice-switching.py
- examples/news-chatbot/server/news_bot.py
- src/pipecat/services/ai_services.py
This PR allows multiple text filters and aggregators, instead of a single one. This way we can have smaller classes that each do one thing and this makes them composable.
> TTSService: allow passing multiple text filters and aggregators

- CHANGELOG.md
- src/pipecat/processors/frameworks/rtvi.py
> Fix: RTVI message disconnect-bot now pushes EndTaskFrame

- CHANGELOG.md
- src/pipecat/pipeline/task.py
- src/pipecat/services/ai_services.py
- src/pipecat/services/cartesia.py
- src/pipecat/services/elevenlabs.py
- src/pipecat/services/fish.py
- src/pipecat/services/lmnt.py
- src/pipecat/services/neuphonic.py
- src/pipecat/services/playht.py
- src/pipecat/services/rime.py
- src/pipecat/services/websocket_service.py
Instead of reconnecting to the TTS services, this allows to fallback to a different provider (e.g. using a `ParallelPipeline`) if something goes wrong.
> WebsocketTTSService: add `on_connection_error` and `reconnect_on_error`

- CHANGELOG.md
- src/pipecat/services/gemini_multimodal_live/gemini.py
> GeminiMultimodalLiveLLMService: fix duplicated messages in context

- examples/foundational/14a-function-calling-anthropic.py
- examples/foundational/14b-function-calling-anthropic-video.py
To make sure we're testing the latest.
> Update to Claude 3.7 Sonnet latest in examples

- CHANGELOG.md
> update CHANGELOG for 0.0.59

- CHANGELOG.md
> update CHANGELOG for 0.0.60

- CHANGELOG.md
- examples/foundational/07x-interruptible-local.py
Note that this might suffer from not having echo cancellation.
> examples: add foundational 07x-interruptible-local.py

- src/pipecat/services/google/google.py
- tests/test_context_aggregators.py
In this PR we allow setting any value as a Google function call result.
> GoogleAssistantContextAggregator: allow any value as function call result

- CHANGELOG.md
- examples/foundational/13e-whisper-mlx.py
Example and CHANGELOG entry for #1383
> Example and CHANGELOG for WhisperSTTServiceMLX service

- docs/api/conf.py
- docs/api/requirements.txt
Adding Mem0 and MLX Whisper mocks for documentation auto-gen.
> Update reference docs generation for mem0 and mlx-whisper

- src/pipecat/services/ultravox/stt.py
> Fixing ruff format.

- pyproject.toml
See https://pypi.org/project/aiohttp/#history
> pyproject: downgrade to aiohttp 3.11.12

- examples/p2p-webrtc/video-transform/client/typescript/.gitignore
> Add .gitignore to p2p video-transform example

- CHANGELOG.md
- src/pipecat/services/gladia/stt.py
> Update GladiaSTTService default model

- src/pipecat/processors/user_idle_processor.py
- tests/test_user_idle_processor.py
> tests: fix test_user_idle_processor for python 3.10

- CHANGELOG.md
- src/pipecat/frames/frames.py
This will probably be superseded by #1491, but for now it should solve the issue.
> frames: make FunctionCallResultFrame a SystemFrame

- CHANGELOG.md
- src/pipecat/transports/base_transport.py
> TransportParams: set audio_out_10ms_chunks to 4

- CHANGELOG.md
> update CHANGELOG for 0.0.62

- examples/foundational/07g-interruptible-openai.py
- src/pipecat/services/openai/tts.py
These voices are not publicly supported. Also, the `-latest` model keeps reporting a 503, so I'm switching the example to just use the default.
> Add new voices to OpenAITTSService

- examples/foundational/19a-azure-realtime-beta.py
- examples/foundational/20a-persistent-context-openai.py
- examples/foundational/20b-persistent-context-openai-realtime.py
- examples/foundational/20c-persistent-context-anthropic.py
- examples/foundational/20d-persistent-context-gemini.py
- examples/foundational/26b-gemini-multimodal-live-function-calling.py
> Examples: Fix context_aggregator.assistant() pipeline position

- pyproject.toml
- src/pipecat/services/openai/tts.py
One additional voice is supported. Updating the `openai` package to get the latest voice Literals.
> Add verse voice and bump the OpenAI version

- CONTRIBUTING.md
- docs/api/index.rst
- pyproject.toml
- src/pipecat/adapters/schemas/function_schema.py
Also made some other improvements for better docs auto-generation while I was here:
- Updated CONTRIBUTING.md with docstrings preferences
- Added a linter rule to ignore `__init__` docstring requirement when a class already implements docstrings (eliminates redundant definition of params)
- Improved FunctionSchema docstrings as an example
> Docs: Update ToC With Adapters and Observers

- CHANGELOG.md
- src/pipecat/transports/network/small_webrtc.py
Fixed SmallWebRTCTransport to support dynamic chunk values.
> Fixed SmallWebRTCTransport to support dynamic chunk values.

- CHANGELOG.md
- src/pipecat/services/azure/tts.py
> Fix: Set language for Azure TTS services

- src/pipecat/services/gemini_multimodal_live/gemini.py
Fix to allow flexibly setting wss uri for Gemini Multimodal Live API
> Gemini Multimodal Live API base_url

- CHANGELOG.md
- src/pipecat/transports/network/small_webrtc.py
This is needed to support equivalent functionality in the DailyTransport. I'm opting to not include the `capture_participant_video` convenience method, as you can just set `camera_in_enabled=True,` in the transport, but we could definitely add it for parity.
(Also, some docstring linting inflates the number of changes.)
> Add image capture to SmallWebRTCTransport

- CHANGELOG.md
- src/pipecat/services/gemini_multimodal_live/gemini.py
This is now the latest base_url, per docs: https://ai.google.dev/api/live#websocket-connection
> Update GeminiMultimodalLiveLLMService base_url

- examples/p2p-webrtc/voice-agent/bot.py
- examples/p2p-webrtc/voice-agent/requirements.txt
Fixing voice agent example to work with Pipecat 0.0.62
> Fixing voice agent example

- CHANGELOG.md
- src/pipecat/services/gemini_multimodal_live/events.py
- src/pipecat/services/gemini_multimodal_live/gemini.py
- src/pipecat/transcriptions/language.py
> Add Gemini Live support for languages, native model transcriptions, media resolution, and VAD settings

- src/pipecat/transports/network/small_webrtc.py
- src/pipecat/transports/network/webrtc_connection.py
> Bot left signalling message

- CHANGELOG.md
> Update CHANGELOG for 0.0.63

- examples/simple-chatbot/client/react/src/components/DebugDisplay.tsx
This was spelled wrong so the event wouldn't come through
> docs: Fix TrackStopped typo in SimpleChatbot

- examples/p2p-webrtc/voice-agent/index.html
Fixing the voice agent example to always create the video transceiver.
> Fixing the voice agent example to always create the video transceiver.

- CHANGELOG.md
- src/pipecat/audio/mixers/soundfile_mixer.py
> SoundfileMixer: add mixing argument and require keywords

- CHANGELOG.md
- src/pipecat/services/google/llm_vertex.py
Fixed an issue where llm input parameters were not working and applied correctly in `GoogleVertexLLMService`, causing 
unexpected behavior during inference.
> Fixed params issue in Google Vertex ai

- CHANGELOG.md
- src/pipecat/services/cartesia/tts.py
- src/pipecat/services/elevenlabs/tts.py
- src/pipecat/services/fish/tts.py
- src/pipecat/services/gladia/stt.py
- src/pipecat/services/lmnt/tts.py
- src/pipecat/services/neuphonic/tts.py
- src/pipecat/services/playht/tts.py
- src/pipecat/services/rime/tts.py
- src/pipecat/services/websocket_service.py
> services: fix TTS websocket services disconnections

- examples/foundational/38-smart-turn.py
- examples/foundational/38a-local-smart-turn.py
- src/pipecat/audio/turn/base_smart_turn.py
- src/pipecat/audio/turn/base_turn_analyzer.py
- src/pipecat/transports/base_input.py
- src/pipecat/transports/base_transport.py
Add `BaseTurnAnalyzer`, also change `end_of_turn_analyzer` to `turn_analyzer` for simplicity.
> audio: add BaseTurnAnalyzer class

- examples/deployment/pipecat-cloud-daily-pstn-server/fastapi-webhook-server/server.py
- examples/deployment/pipecat-cloud-daily-pstn-server/nextjs-webhook-server/pages/api/dial.js
> Changing default codec to OPUS for telephony

- CHANGELOG.md
Mentioning the Smart Turn Detection into the changelog.
> Mentioning the Smart Turn Detection into the changelog.

- examples/foundational/07g-interruptible-openai.py
> examples: Fix 07g by changing STT model

- CHANGELOG.md
Adding a changelog entry for: https://github.com/pipecat-ai/pipecat/pull/1525
> Add CHANGELOG entry for PR 1525

- src/pipecat/services/openai/tts.py
Basic Python problem: self.sample_rate is not init and is referenced in the warning
> Fixed AttributeError: object has no attribute '_sample_rate"

- CHANGELOG.md
- src/pipecat/audio/turn/base_smart_turn.py
- src/pipecat/audio/turn/base_turn_analyzer.py
- src/pipecat/frames/frames.py
- src/pipecat/metrics/metrics.py
- src/pipecat/transports/base_input.py
> Add a SmartTurnResultFrame

- examples/phone-chatbot/env.example
- examples/phone-chatbot/requirements.txt
> typo fixes in phone-chatbot example

- examples/foundational/run.py
- examples/p2p-webrtc/daily-interop-bridge/bot.py
- examples/p2p-webrtc/daily-interop-bridge/server.py
- examples/p2p-webrtc/video-transform/server/bot.py
- examples/p2p-webrtc/video-transform/server/server.py
- examples/p2p-webrtc/voice-agent/bot.py
- examples/p2p-webrtc/voice-agent/server.py
> examples: always use loguru for logging

- CHANGELOG.md
> update CHANGELOG for 0.0.65

- CHANGELOG.md
- src/pipecat/services/elevenlabs/tts.py
ElevenLabs now supports this, so making the change.
> ElevenLabs: InputParams can be set individually

- examples/foundational/README.md
> Update foundational README with ToC

- CHANGELOG.md
- examples/foundational/39-mcp-stdio.py
- examples/foundational/39a-mcp-run-sse.py
- examples/foundational/39b-multiple-mcp.py
- pyproject.toml
- src/pipecat/services/mcp_service.py
MCP support for pipecat
Handles stdio or SSE connections to MCP server and tool calls.
Does _not_ handle resources, prompts, or sampling.
I think this is ok for MVP support.
> MCP Service

- examples/fal-smart-turn/client/package-lock.json
- examples/fal-smart-turn/client/package.json
Version 0.3.7 (previous version) had a bug that enabled the camera.
> Update daily-transport version in fal-smart-turn demo

- examples/fal-smart-turn/README.md
> Add hosted demo link to Fal smart turn README

- examples/foundational/04-transports-small-webrtc.py
- examples/foundational/39-mcp-stdio.py
- examples/foundational/39a-mcp-run-sse.py
- examples/foundational/39b-multiple-mcp.py
- examples/word-wrangler-gemini-live/server/bot.py
- examples/word-wrangler-gemini-live/server/bot_phone_local.py
- examples/word-wrangler-gemini-live/server/bot_phone_twilio.py
A few more examples to update to new transport param names. as per #1648
> Update examples with new transport param names

- CHANGELOG.md
- src/pipecat/processors/aggregators/llm_response.py
> short utterances fixes

- .gitignore
- examples/local-input-select-stt/bot.py
- examples/local-input-select-stt/requirements.txt
- examples/local-input-select-stt/select_audio_device.py
One more security update and some cleanup.
> examples: update local-input-select-stt

- CHANGELOG.md
- examples/foundational/run.py
- examples/p2p-webrtc/daily-interop-bridge/server.py
- examples/p2p-webrtc/video-transform/server/server.py
- examples/p2p-webrtc/voice-agent/server.py
- src/pipecat/transports/network/webrtc_connection.py
Updated `SmallWebRTCConnection` to support `ice_servers` with credentials.
> Updated `SmallWebRTCConnection` to support `ice_servers` with credentials.

- examples/p2p-webrtc/voice-agent/README.md
- examples/p2p-webrtc/voice-agent/index.html
Configuring the voice-agent example to use ice-servers and wait for all the ice candidates.
> Configuring the voice-agent example to wait for all the ice candidates.

- examples/deployment/modal-example/requirements.txt
Submitted #1687.
Then found out dependencies in `requirements.txt` are not up to date.
Best,
flix
> Bump modal deployment example dependencies

- src/pipecat/services/gemini_multimodal_live/gemini.py
Mistakenly removed support for this when fixing the context.
Fixes: #1712
> Restore TEXT modalities support to GeminiMultimodalLiveLLMService

- CHANGELOG.md
> Add Changelog entry for PR 1707

- CHANGELOG.md
> update CHANGELOG for pipecat 0.0.66

- examples/foundational/13c-gladia-translation.py
- examples/foundational/35-pattern-pair-voice-switching.py
> Demo fixes

- CHANGELOG.md
- src/pipecat/transports/services/daily.py
Make sure custom tracks are removed before leaving.
> DailyTransport: remove custom tracks before leaving

- examples/deployment/pipecat-cloud-example/bot.py
- examples/deployment/pipecat-cloud-example/env.example
- examples/deployment/pipecat-cloud-example/local_runner.py
- examples/deployment/pipecat-cloud-example/pcc-deploy.toml
Aligning this example with the latest PCC best practices.
> Update pipecat-cloud-example to use Krisp in PCC deployment only

- CHANGELOG.md
- src/pipecat/transports/base_input.py
- src/pipecat/transports/base_output.py
- src/pipecat/transports/local/audio.py
- src/pipecat/transports/local/tk.py
- src/pipecat/transports/network/fastapi_websocket.py
- src/pipecat/transports/network/small_webrtc.py
- src/pipecat/transports/network/websocket_client.py
- src/pipecat/transports/network/websocket_server.py
- src/pipecat/transports/services/daily.py
- src/pipecat/transports/services/livekit.py
> only send data to transports after they are really ready

- CHANGELOG.md
- src/pipecat/services/elevenlabs/tts.py
> Add enable_ssml_parsing and enable_logging to ElevenLabsTTSService

- CHANGELOG.md
- examples/foundational/07c-interruptible-deepgram-vad.py
- examples/foundational/07c-interruptible-deepgram.py
- src/pipecat/services/deepgram/tts.py
> Update Deepgram TTS default voice to Aura 2 voice

- CHANGELOG.md
- examples/foundational/30-observer.py
- src/pipecat/observers/base_observer.py
- src/pipecat/observers/loggers/llm_log_observer.py
- src/pipecat/observers/loggers/transcription_log_observer.py
- src/pipecat/pipeline/task_observer.py
- src/pipecat/processors/frame_processor.py
- src/pipecat/processors/frameworks/rtvi.py
- src/pipecat/services/google/rtvi.py
- src/pipecat/tests/utils.py
This is so we can add more things in the future and make things shorter.
> BaseObserver: add FramePushed class and deprecate multiple arguments

- CHANGELOG.md
- src/pipecat/frames/frames.py
- src/pipecat/services/llm_service.py
- src/pipecat/transports/services/daily.py
This fixes `26c-gemini-multimodal-live-video.py`. You can ask what Gemini sees in your camera or in your screen and it should work (as long as you are sharing both your camera and your screen).
> fix multiple audio video sources

- CHANGELOG.md
> update CHANGELOG for 0.0.67

- examples/patient-intake/server.py
> Add load_dotenv to patient-intake server file

- examples/moondream-chatbot/server.py
> Add load_dotenv to moondream example server

- src/pipecat/services/aws_nova_sonic/__init__.py
> Add missing `Params` export to AWS Nova Sonic module

- src/pipecat/services/elevenlabs/tts.py
moves api key to websocket header
> [elevenlabs tts ] fix api key

- CHANGELOG.md
- src/pipecat/tests/utils.py
> tests: allow passing observers to run_test()

- examples/deployment/pipecat-cloud-daily-pstn-server/README.md
- examples/deployment/pipecat-cloud-daily-pstn-server/fastapi-webhook-server/server.py
- examples/deployment/pipecat-cloud-daily-pstn-server/nextjs-webhook-server/pages/api/dial.js
Daily added receiving custom sip headers on the sip interconnect. i.e., from Twilio/Telnyx/Plivo you can send the caller's phone number
> added handling for sipHeaders

- examples/bot-ready-signalling/client/javascript/package-lock.json
- examples/bot-ready-signalling/client/javascript/package.json
- examples/deployment/modal-example/client/javascript/package-lock.json
- examples/deployment/modal-example/client/javascript/package.json
- examples/instant-voice/client/javascript/package-lock.json
- examples/instant-voice/client/javascript/package.json
- examples/news-chatbot/client/javascript/package-lock.json
- examples/news-chatbot/client/javascript/package.json
- examples/p2p-webrtc/video-transform/client/typescript/package-lock.json
- examples/p2p-webrtc/video-transform/client/typescript/package.json
- examples/simple-chatbot/client/javascript/package-lock.json
- examples/simple-chatbot/client/javascript/package.json
- examples/simple-chatbot/client/react/package-lock.json
- examples/simple-chatbot/client/react/package.json
> examples: updates for dependabot 05/14/2025

- CHANGELOG.md
- src/pipecat/utils/base_object.py
> BaseObject: don't create event handler tasks if none is registered

- examples/word-wrangler-gemini-live/server/bot.py
- examples/word-wrangler-gemini-live/server/bot_phone_local.py
> Fix: Add audio_in_enabled to Word Wrangler TransportParams

- CHANGELOG.md
- src/pipecat/frames/frames.py
- src/pipecat/processors/transcript_processor.py
- tests/test_transcript_processor.py
This allows us to identify which user said what in a multi-user scenario.
> TranscriptionMessage: add user_id field

- CHANGELOG.md
- examples/foundational/35-pattern-pair-voice-switching.py
- examples/word-wrangler-gemini-live/server/bot_phone_local.py
- examples/word-wrangler-gemini-live/server/bot_phone_twilio.py
- src/pipecat/services/tts_service.py
- src/pipecat/utils/text/base_text_aggregator.py
- src/pipecat/utils/text/base_text_filter.py
- src/pipecat/utils/text/markdown_text_filter.py
- src/pipecat/utils/text/pattern_pair_aggregator.py
- src/pipecat/utils/text/simple_text_aggregator.py
- src/pipecat/utils/text/skip_tags_aggregator.py
- tests/test_markdown_text_filter.py
- tests/test_pattern_pair_aggregator.py
- tests/test_simple_text_aggregator.py
- tests/test_skip_tags_aggregator.py
This allows users to be able to use async functions they might need (e.g. callbacks). For example, see how the switching voices examples gets simplified.
> make BaseTextAggregator and BaseTextFilter functions async

- src/pipecat/utils/text/markdown_text_filter.py
- tests/test_markdown_text_filter.py
Please see https://github.com/pipecat-ai/pipecat/issues/1798. 
TLDR: Cleaning links to they improve TTS performance
> Add link cleaning in MD text filter

- src/pipecat/observers/base_observer.py
- src/pipecat/observers/loggers/debug_log_observer.py
- src/pipecat/observers/turn_tracking_observer.py
- src/pipecat/pipeline/task_observer.py
- src/pipecat/processors/frameworks/rtvi.py
- src/pipecat/tests/utils.py
- src/pipecat/utils/tracing/turn_trace_observer.py
> BaseObserver: inherit from BaseObject so we can have events

- CHANGELOG.md
- src/pipecat/services/elevenlabs/tts.py
> Fix: ElevenLabsTTSService, change voice and model

- CHANGELOG.md
- src/pipecat/services/anthropic/llm.py
Tested function calling and latency. Both seem inline with Sonnet 3.7.
> Update default model for Anthropic to Claude Sonnet 4

- README.md
> add docs link at top of readme

- CHANGELOG.md
- src/pipecat/transports/base_output.py
> BaseOutputTransport: don't block event loop during image resize

- examples/open-telemetry/jaeger/README.md
- examples/open-telemetry/langfuse/README.md
- examples/open-telemetry/langfuse/env.example
Minor but important improvements to the env.example.
> Langfuse OTel env.example improvements

- examples/foundational/33-gemini-rag.py
- src/pipecat/services/google/llm.py
We haven't released the google-genai update yet, so no changelog entry should be required.
Also, I'm updating the 33-gemini-rag example, which used the google-generativeai package which is deprecated.
> fix: Update GoogleLLMContext to_standard_messages to be compatible with google-genai

- CHANGELOG.md
> update CHANGELOG for pipecat 0.0.68

- MANIFEST.in
This is to fix pypi upload error issues when files are > 100MB. There's no need to include tests, examples, docs or scripts in the tarball.
> add MANIFEST.in to reduce sdist tarball size

- CHANGELOG.md
- examples/twilio-chatbot/client.py
- src/pipecat/transports/network/websocket_client.py
> fix: update websocket_client to use FrameProcessorSetup.task_manager

- CHANGELOG.md
- src/pipecat/frames/frames.py
- src/pipecat/services/assemblyai/stt.py
- src/pipecat/services/aws/stt.py
- src/pipecat/services/azure/stt.py
- src/pipecat/services/deepgram/stt.py
- src/pipecat/services/fal/stt.py
- src/pipecat/services/gemini_multimodal_live/gemini.py
- src/pipecat/services/gladia/stt.py
- src/pipecat/services/google/stt.py
- src/pipecat/services/openai_realtime_beta/openai.py
- src/pipecat/services/riva/stt.py
- src/pipecat/transports/services/daily.py
Some people have requested to access STT service results in case they use custom settings. This PR adds a new `result` field with whatever comes from the STT service.
> add STT result field to TranscriptionFrame/InterimTranscriptionFrame

- CHANGELOG.md
- pyproject.toml
- src/pipecat/__init__.py
See https://uvloop.readthedocs.io/. This makes Pipecat run a bit smoother! We should test it thoroughly.
> use uvloop as the new event loop on Linux and macOS

- CHANGELOG.md
- examples/twilio-chatbot/bot.py
- src/pipecat/processors/aggregators/dtmf_aggregator.py
- tests/test_dtmf_aggregator.py
This adds a DTMFAggregator, inspired by this older PR: https://github.com/pipecat-ai/pipecat/pull/1362.
> Add DTMFAggregator

- examples/phone-chatbot/daily-pstn-advanced-voicemail-detection/env.example
- examples/phone-chatbot/daily-pstn-simple-voicemail-detection/env.example
Forgot to update the example env file for the advanced voicemail detection pipeline
> Fix example env file

- src/pipecat/transports/base_input.py
Adding the direction when pushing the BotStartedSpeaking and BotStoppedSpeaking frames.
> Adding the direction when pushing the frame.

- CHANGELOG.md
- src/pipecat/services/gemini_multimodal_live/gemini.py
> Reverting Gemini Live model back to gemini-2.0-flash-live-001

- CHANGELOG.md
- examples/foundational/04a-transports-daily.py
- src/pipecat/audio/interruptions/base_interruption_strategy.py
- src/pipecat/audio/interruptions/min_words_interruption_strategy.py
- src/pipecat/frames/frames.py
- src/pipecat/pipeline/task.py
- src/pipecat/processors/aggregators/llm_response.py
- src/pipecat/processors/frame_processor.py
- src/pipecat/transports/base_input.py
- tests/test_interruption_strategies.py
This PR allows users to write their own custom interruptions strategies.
> allow custom interruption strategies

- CHANGELOG.md
> update CHANGELOG for 0.0.69

- CHANGELOG.md
- src/pipecat/transports/services/livekit.py
> fix: transports/services/livekit.py typo

- CHANGELOG.md
- pyproject.toml
- src/pipecat/__init__.py
I've got a report that uvloop is causing issues in a system running Django, so I think it's safer to just not set it by default and let the user decide what to do.
> disable uvloop by default and just let the user set it

- CHANGELOG.md
- src/pipecat/services/assemblyai/stt.py
> AssemblyAISTTService: yield None instead of Frame()

- CHANGELOG.md
- src/pipecat/serializers/exotel.py
Adding exotel serializer
Addresses: #1965
> adding exotel serializer

- examples/foundational/22b-natural-conversation-proposal.py
This `FunctionFilter` is not used as there's nothing else in that branch.
> examples(22b): remove unnecessary parallel pipeline branch

- CHANGELOG.md
> update CHANGELOG for 0.0.70

- CHANGELOG.md
> update CHANGELOG for 0.0.71

- pyproject.toml
Bumping pipecat-ai-krisp required version
> Bumping pipecat-ai-krisp required version

- src/pipecat/examples/run.py
> examples: create transport params async

- CHANGELOG.md
- src/pipecat/services/elevenlabs/tts.py
Implementing #2009 with linting fixes and changelog addition.
> fix: ElevenLabsTTSService voice settings not being sent

- CHANGELOG.md
Adding the GladiaSTTService improvements in the changelog.
> Adding the GladiaSTTService improvements in the changelog.

- CHANGELOG.md
- src/pipecat/pipeline/task.py
- tests/test_pipeline.py
> PipelineTask: fix repeated on_idle_timeout

- CHANGELOG.md
- src/pipecat/services/aws_nova_sonic/aws.py
> AWSNovaSonicLLMService: fix function calling

- CHANGELOG.md
- src/pipecat/observers/turn_tracking_observer.py
- tests/test_turn_tracking_observer.py
> TurnTrackingObserver ends turn upon seeing EndFrame, CancelFrame

- src/pipecat/transports/services/helpers/daily_rest.py
> Add missing arg docstring in DailyRESTHelper

- src/pipecat/frames/frames.py
- src/pipecat/processors/frame_processor.py
frame.processor.name rather than frame.name
> small fix for processor pause/resume frames

- src/pipecat/services/elevenlabs/tts.py
In most cases, there will be a context_id available, so we can refresh the connection for the context_id. There's an edge case to handle, too, where an interruption occurs but no transcript is received. In this case, the context_id is None, so we just push a keepalive message without the context.
In talking with a member of the 11Labs team, they'll add a general purpose keepalive which will keep all contexts alive. That will help to simplify this case in the future.
Resolves: #2042
> Send context_id when available in ElevenLabsTTSService keepalive message

- CHANGELOG.md
- src/pipecat/frames/frames.py
- src/pipecat/pipeline/task.py
It makes more sense for heartbeat frames to be control frames. Otherwise, you can't really detect much if they are system frames.
> HeartbeatFrames are now control frames

- src/pipecat/processors/frame_processor.py
> FrameProcessor: use watchdog_timeout_secs

- CHANGELOG.md
- examples/freeze-test/freeze_test_bot.py
- src/pipecat/processors/frame_processor.py
- src/pipecat/processors/metrics/frame_processor_metrics.py
- src/pipecat/processors/metrics/sentry.py
> SentryMetrics: send metrics to sentry asynchronously

- src/pipecat/processors/aggregators/llm_response.py
Not forcing the bot resume speaking in case we receive no transcription.
> Not forcing the bot resume speaking in case we receive no transcription.

- examples/foundational/39c-mcp-run-http.py
- src/pipecat/services/mcp_service.py
> mcp_service: lint

- CHANGELOG.md
- src/pipecat/pipeline/task.py
- src/pipecat/pipeline/task_observer.py
- src/pipecat/services/elevenlabs/tts.py
- src/pipecat/services/gladia/stt.py
- src/pipecat/services/neuphonic/tts.py
- src/pipecat/services/openai_realtime_beta/frames.py
Somehow tests missed this. Sorry about that.
> just a quick hotfix for 0.0.73

- src/pipecat/examples/run.py
If the user specifies the host name `e.g. --host 192.168.1.20` we perform SDP munging where we:
- Only use SHA-256 fingerprint.
- Remove all ICE candidates except the specified host.
We could add a new argument `--sdp-host`, but for now this might be enough.
> examples: add --esp32 for SDP munging if host name specified

- src/pipecat/adapters/schemas/direct_function.py
- src/pipecat/examples/run.py
- src/pipecat/services/llm_service.py
> Clean up docstrings after DirectFunction merge

- examples/simple-chatbot/client/ios/SimpleChatbot.xcodeproj/project.pbxproj
- examples/simple-chatbot/client/ios/SimpleChatbot.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- examples/simple-chatbot/client/ios/SimpleChatbot/model/CallContainerModel.swift
Fixed an issue to disconnect the iOS chatbot demo.
> Fixed an issue to disconnect the iOS chatbot demo.

- examples/daily-multi-translation/requirements.txt
- examples/open-telemetry/jaeger/requirements.txt
- examples/open-telemetry/langfuse/requirements.txt
- examples/phone-chatbot/daily-twilio-sip-dial-in/requirements.txt
- src/pipecat/observers/loggers/debug_log_observer.py
- src/pipecat/processors/aggregators/gated.py
- src/pipecat/processors/aggregators/sentence.py
- src/pipecat/processors/aggregators/vision_image_frame.py
- src/pipecat/processors/text_transformer.py
- src/pipecat/services/gemini_multimodal_live/file_api.py
- src/pipecat/services/gemini_multimodal_live/gemini.py
- src/pipecat/utils/utils.py
Some docstring housekeeping + adding missing imports in a few examples.
Also, some cleanup on gemini live and the corresponding files API.
> Docstring cleanup, fix missing examples imports

- CONTRIBUTING.md
- docs/api/conf.py
- src/pipecat/pipeline/task.py
- src/pipecat/processors/audio/audio_buffer_processor.py
- src/pipecat/services/aws/tts.py
- src/pipecat/services/aws_nova_sonic/aws.py
- src/pipecat/services/cartesia/tts.py
- src/pipecat/services/deepgram/stt.py
- src/pipecat/services/gladia/config.py
- src/pipecat/services/gladia/stt.py
- src/pipecat/services/google/stt.py
- src/pipecat/services/llm_service.py
- src/pipecat/services/riva/stt.py
- src/pipecat/services/riva/tts.py
- src/pipecat/services/tts_service.py
- src/pipecat/transports/base_transport.py
- src/pipecat/transports/services/daily.py
> Add deprecation directives, add indexing, only autodoc members

- examples/websocket/client/README.md
> fix: remove javascript directory from the websocket README

- src/pipecat/processors/frameworks/rtvi.py
> Add docs deprecation for handle_function_call_start

- CHANGELOG.md
> docs: add changelog line for gemini files api

- CHANGELOG.md
- src/pipecat/serializers/twilio.py
> TwilioFrameSerializer: Handle user hanging up before the serializer

- CHANGELOG.md
- src/pipecat/services/cartesia/tts.py
- src/pipecat/services/elevenlabs/tts.py
- src/pipecat/services/neuphonic/tts.py
- src/pipecat/services/rime/tts.py
> TTS services: Add aggregate_sentences arg

- CHANGELOG.md
- src/pipecat/services/ollama/llm.py
Request from Discord.
@kwindla I think this is right, but I don't have an Ollama set up to test. Mind checking to make sure this works correctly?
> OLLamaLLMService: Pass kwargs

- CHANGELOG.md
- src/pipecat/processors/frameworks/rtvi.py
> Release prep for 0.0.75

- examples/deployment/pipecat-cloud-daily-pstn-server/nextjs-webhook-server/pages/api/dial.js
> fix nextjs webhook example num_endpoints null check

- .pre-commit-config.yaml
I overlooked this in the docstring changes.
> Add docstring checking to .pre-commit-config.yaml

- src/pipecat/transports/services/tavus.py
I have made a change on our side that makes the persona validation not necessary anymore. 
This PR removes the check which should improve the user experience 🙌
✅ I have run ruff.sh
> feat: Remove persona microphone check

- src/pipecat/examples/run.py
Leaving this as a reminder for myself and others. We don't auto-generate docs for this yet, but if we do, this would be documented. At a minimum, it's documented in source now.
> run.py: Add example usage to the module docstring

- .pre-commit-config.yaml
`--select` overrides the project's rules. We'll switch to `--fix` to use the pyproject.toml rules.
> Update .pre-commit-config.yaml to use pyproject.toml linting rules

- CHANGELOG.md
- pyproject.toml
Rather than pin specific versions, we should create dependency ranges. I'm not going to do that in this PR, but I'm making two updates based on community requests.
We should revisit the versions in a separate PR.
> Update numpy, transformers to support newer versions

- CHANGELOG.md
> Prepare changelog for 0.0.76 release

- CHANGELOG.md
- src/pipecat/services/lmnt/tts.py
Found this change in working on docs.
Reference: https://docs.lmnt.com/guides/models
> LmntTTSService: update the default model to blizzard

- CHANGELOG.md
- examples/foundational/38b-smart-turn-local.py
- src/pipecat/audio/turn/smart_turn/local_smart_turn_v2.py
> Add support for running `smart-turn-v2` locally with `LocalSmartTurnAnalyzerV2`

- examples/deployment/pipecat-cloud-daily-pstn-server/nextjs-webhook-server/package-lock.json
- examples/deployment/pipecat-cloud-daily-pstn-server/nextjs-webhook-server/package.json
> Fix form-data vulnerability in pipecat-cloud-daily-pstn-server

- CHANGELOG.md
- src/pipecat/services/minimax/tts.py
> fix: MiniMaxHttpTTSService pitch, add base_url arg

- CHANGELOG.md
- examples/foundational/04a-transports-daily.py
- src/pipecat/transports/services/daily.py
Added `set_log_level` to `DailyTransport`
> Added `set_log_level` to `DailyTransport`

- .gitignore
FYI:  `.python-version` is from `uv`.
> .gitignore: add plivo-chatbot streams.xml, .python-version

- CHANGELOG.md
- src/pipecat/processors/aggregators/llm_response.py
This is from #2302 with just an extra commit to fix formatting and update CHANGELOG.
> Enable Interruption Support for LLMUserResponseAggregator

- CHANGELOG.md
> Changelog update for 0.0.77

- .pre-commit-config.yaml
Aligning to dev-requirements.txt. At some point, we should automate this, or align with the dev-requirements.txt.
> Update pre-commit-config ruff version

- examples/foundational/43a-heygen-video-service.py
> me trying to get heygen working

- examples/foundational/07b-interruptible-langchain.py
- examples/foundational/13b-deepgram-transcription.py
- examples/foundational/13c-gladia-translation.py
- examples/foundational/13d-assemblyai-transcription.py
- examples/foundational/22d-natural-conversation-gemini-audio.py
I missed a few foundational examples. These should be the last of them. All updated for the new runner.
> Updating more foundational examples

- CHANGELOG.md
- src/pipecat/runner/run.py
Developer experience improvement. With a protocol included (or trailing `/`), the runner will appear to not work.
> Runner: strip protocol from proxy address

- CHANGELOG.md
- examples/foundational/27-simli-layer.py
- src/pipecat/services/simli/video.py
A few modifications needed to support the new Simli models in pipecat!
Adds client side buffering to make sure audio is being fed to Simli properly
> feat: Add Simli Trinity models support to pipecat

- CHANGELOG.md
- src/pipecat/services/aws/stt.py
> AWSTranscribeSTTService add support for new languages

- CHANGELOG.md
Moving this entry to `[Unreleased]`.
> Fix Simli changelog entry placement

- src/pipecat/services/elevenlabs/tts.py
> log: warning -> trace for elevenlabs tts unavailable context

- CHANGELOG.md
- pyproject.toml
> fix: pin numba to >=0.61.2

- README.md
Some refinement of the contributing section of the top-level README.
> Update README with local dev setup for contributors

- CHANGELOG.md
- src/pipecat/services/azure/stt.py
> Support endpoint_id for AzureSTTService

- CHANGELOG.md
- src/pipecat/services/heygen/video.py
- src/pipecat/services/tavus/video.py
Added TTFB metrics for `HeyGenVideoService` and `TavusVideoService`.
> Added TTFB metrics for `HeyGenVideoService` and `TavusVideoService`.

- CHANGELOG.md
- src/pipecat/services/heygen/client.py
Improving the latency of the `HeyGenVideoService`.
> Improving the latency of the `HeyGenVideoService`.

- CHANGELOG.md
- src/pipecat/processors/filters/stt_mute_filter.py
- tests/test_stt_mute_filter.py
Added those frame types to tests too (incl commented ones).
> Add VADUserStartSpeakingFrame VADUserStopSpeakingFrame to STTMuteFilter (fix #2412)

- CHANGELOG.md
- pyproject.toml
- src/pipecat/services/moondream/vision.py
- uv.lock
> MoondreamService: update to revision 2025-01-09

- CHANGELOG.md
> update CHANGELOG for 0.0.80

- examples/foundational/README.md
Removes duplication between the top-level README and this README.
> Improve the foundational example README

- src/pipecat/runner/run.py
We set default `handle_sigint` to False but Daily direct still needs to handle SIGINT properly.
> Runner: set handle_sigint to True for Daily direct

- CHANGELOG.md
- src/pipecat/processors/audio/audio_buffer_processor.py
This PR makes sure we reset recording (buffers and timers) when needed.
> AudioBufferProcessor: fix overlap when buffer size is set

- CHANGELOG.md
- examples/foundational/13j-azure-transcription.py
- uv.lock
> Add foundational 13j for Azure STT

- src/pipecat/services/mistral/llm.py
Resolving formatting errors. The errors prevent docs from building locally and result in incorrect formatting.
> Fix Mistral docstrings build errors

- CHANGELOG.md
- src/pipecat/observers/base_observer.py
- src/pipecat/pipeline/base_pipeline.py
- src/pipecat/pipeline/parallel_pipeline.py
- src/pipecat/pipeline/pipeline.py
- src/pipecat/pipeline/sync_parallel_pipeline.py
- src/pipecat/pipeline/task.py
- src/pipecat/pipeline/task_observer.py
- src/pipecat/processors/frame_processor.py
- src/pipecat/tests/utils.py
- tests/test_context_aggregators.py
- tests/test_dtmf_aggregator.py
- tests/test_stt_mute_filter.py
- tests/test_transcript_processor.py
This PR provides a few improvements:
- Use direct mode in both `Pipeline` and `ParallelPipeline`. Improves performance.
- Avoid creating tasks for every frame and sub-pipeline in `ParallelPipeline`. Improves performance.
- Added new `FrameProcessor` methods: `processors()` and `entry_processors()`
- `Pipeline` class now allows passing source and sink elements. This reduces code complexity in, for example, `ParallelPipeline` and allows returning the single sub-pipeline processors when calling `processors()`.
- Removes `set_parent()` and `get_parent()` they were just broken an unused.
- Adds new observer method `on_process_frame`.
More improvements to `ParallelPipeline`s coming soon.
> various frame processor updates

- src/pipecat/utils/asyncio/timeout.py
> timeout: fix wait_for2 import

- CHANGELOG.md
- src/pipecat/services/gladia/stt.py
- src/pipecat/services/speechmatics/stt.py
Improve Speechmatics exception handling.
> Speechmatics exception handling

- src/pipecat/frames/frames.py
- src/pipecat/runner/utils.py
- src/pipecat/transports/network/small_webrtc.py
- src/pipecat/transports/network/webrtc_connection.py
This PR goes hand-in-hand with https://github.com/pipecat-ai/pipecat-client-web-transports/pull/56
> Add support to smallWebRTCTransport for receiving screenshare videos

- CHANGELOG.md
> update CHANGELOG for 0.0.81

- CHANGELOG.md
- src/pipecat/services/sarvam/tts.py
- Mentioning the recent SarvamTTSService changes in the changelog.
- Removing watchdog from SarvamTTSService.
> SarvamTTSService follow up PR.

- CHANGELOG.md
- src/pipecat/adapters/base_llm_adapter.py
- src/pipecat/adapters/services/anthropic_adapter.py
- src/pipecat/adapters/services/aws_nova_sonic_adapter.py
- src/pipecat/adapters/services/bedrock_adapter.py
- src/pipecat/adapters/services/gemini_adapter.py
- src/pipecat/adapters/services/open_ai_adapter.py
- src/pipecat/adapters/services/open_ai_realtime_adapter.py
- src/pipecat/processors/aggregators/openai_llm_context.py
- src/pipecat/services/anthropic/llm.py
- src/pipecat/services/aws/llm.py
- src/pipecat/services/google/llm.py
- src/pipecat/services/openai/base_llm.py
Some implementations were returning a list and some were returning a JSON string. They should all return a list and the user would decide if it wants to transform that into JSON.
I saw this while fixing an issue in Whisker and trying out Gemini and OpenAI.
> unify get_messages_for_logging()

- src/pipecat/processors/frameworks/rtvi.py
Found this while using an example with `RTVIProcessor` and Daily Prebuilt. I called `rtvi.set_client_ready()` manually but then the following error showed up:
```
File "/home/aleix/src/pipecat-ai/pipecat/src/pipecat/processors/frameworks/rtvi.py", line 1626, in _send_bot_ready         if self._client_version[0] < 1:                                                                                             │    └ []                                                                                                                └ <pipecat.processors.frameworks.rtvi.RTVIProcessor object at 0x7a1959ddbad0>                                                                                                                                                              IndexError: list index out of …
```
> RTVIProcessor: make check sure client version is set

- src/pipecat/services/mem0/memory.py
The changes made in the PR will reduce the latency when using mem0 as well as the memory retrieval will be more enhanced due to better filtering.
> Update mem0 integration

- CHANGELOG.md
- src/pipecat/transports/network/webrtc_connection.py
- src/pipecat/transports/whatsapp/__init__.py
- src/pipecat/transports/whatsapp/api.py
- src/pipecat/transports/whatsapp/client.py
Support for the new WhatsApp Cloud API:
- Fixing to not use mid to decide if the transceiver should be sendrecv or not.
- Supporting User-initiated Calls: https://developers.facebook.com/docs/whatsapp/cloud-api/calling/user-initiated-calls
> Support for the new WhatsApp Cloud API

- examples/foundational/06a-image-sync.py
> fix: Specify frame direction in 06a push_frame

- CHANGELOG.md
- src/pipecat/pipeline/parallel_pipeline.py
- src/pipecat/services/deepgram/stt.py
> ParallePipeline: wait for CancelFrame in all branches

- CHANGELOG.md
- src/pipecat/frames/frames.py
- src/pipecat/pipeline/task.py
- src/pipecat/transports/base_input.py
In this PR we make a couple of changes:
- Push UserStartedSpeakingFrame and UserStoppedSpeaking frame upstream.
- Add a new UserSpeakingFrame, similar to BotSpeakingFrame that is pushed upstream and downstream while the user is speaking.
-
> add UserSpeakingFrame and UserStartedSpeakingFrame/UserStopeedSpeakingFrame updates

- examples/foundational/07s-interruptible-google-audio-in.py
> example 07s: minor typo updates

- examples/foundational/43a-heygen-video-service.py
Improving HeyGen example video quality.
> Improving HeyGen example video quality.

- CHANGELOG.md
> update CHANGELOG for 0.0.84

- examples/foundational/13-whisper-transcription.py
- examples/foundational/13a-whisper-local.py
- examples/foundational/13b-deepgram-transcription.py
- examples/foundational/13c-gladia-transcription.py
- examples/foundational/13c-gladia-translation.py
- examples/foundational/13d-assemblyai-transcription.py
- examples/foundational/13e-whisper-mlx.py
- examples/foundational/13f-cartesia-transcription.py
- examples/foundational/13g-sambanova-transcription.py
- examples/foundational/13h-speechmatics-transcription.py
- examples/foundational/13i-soniox-transcription.py
- examples/foundational/13j-azure-transcription.py
This solves an issue causing the pipeline to hang when running these examples.
> fix: 13 foundational examples now push frames from TranscriptionLogger

- CHANGELOG.md
- src/pipecat/services/heygen/video.py
Blocking this frame was prevent the STTMuteFilter from working.
> fix: push BotStartedSpeakingFrame in HeyGenVideoService

- src/pipecat/services/aws/llm.py
- tests/test_run_inference.py
And fix an issue caught by those tests!
> `run_inference` unit tests

- src/pipecat/adapters/base_llm_adapter.py
- src/pipecat/adapters/services/anthropic_adapter.py
- src/pipecat/adapters/services/aws_nova_sonic_adapter.py
- src/pipecat/adapters/services/bedrock_adapter.py
- src/pipecat/adapters/services/gemini_adapter.py
- src/pipecat/adapters/services/open_ai_adapter.py
- src/pipecat/adapters/services/open_ai_realtime_adapter.py
- src/pipecat/services/llm_service.py
- tests/test_get_llm_invocation_params.py
Plus a fix for a bug discovered thanks to the tests
> `LLMContext`-adapting unit tests

- CHANGELOG.md
- src/pipecat/services/asyncai/tts.py
> fix: AsyncAITTSService wasn't pushing TTSTextFrames

- README.md
> README: add whisker debugger

- CHANGELOG.md
- src/pipecat/transports/daily/transport.py
> DailyTransport: rename on_before_leave to on_before_disconnect

- CHANGELOG.md
> update CHANGELOG for 0.0.86

- src/pipecat/services/aws_nova_sonic/aws.py
> AWSNovaSonicLLMService: add missing await

- CHANGELOG.md
- src/pipecat/services/anthropic/llm.py
> Update AnthropicLLMService to use claude-sonnet-4-5-20250929

- CHANGELOG.md
- src/pipecat/processors/frameworks/rtvi.py
This PR introduces 3 new messages (disabled by default):
- User audio level
- Bot audio level
- System logs
These are useful to build terminal applications.
> RTVI updates: audio levels and system logs

- src/pipecat/processors/frameworks/rtvi.py
> RTVIParams: properly deprecate errors_enabled

- .github/workflows/publish.yaml
- .github/workflows/publish_test.yaml
- Use python 3.12
- Fix test URLs and naming
> Updates to publish workflows

- CHANGELOG.md
- src/pipecat/processors/frameworks/rtvi.py
> Transports now send InputTransportMessageFrames (not Urgent Frames)

- CHANGELOG.md
- examples/foundational/07ae-interruptible-hume.py
- src/pipecat/services/hume/tts.py
Just some house keeping after merging the new HumeTTSService.
> Tidying up the Hume example and service

- CHANGELOG.md
- src/pipecat/utils/string.py
This came up in a Discord thread:
https://discord.com/channels/1239284677165056021/1421087249654743141/1421087249654743141
Catching the error plus adding a message to help developers understand and resolve this error.
> Catch PermissionError when NLTK data can't be downloaded

- src/pipecat/transports/smallwebrtc/request_handler.py
- src/pipecat/transports/whatsapp/api.py
- src/pipecat/transports/whatsapp/client.py
Allowing to update smallwebrtc and whatsapp properties.
> Allowing to update smallwebrtc and whatsapp properties.

- CHANGELOG.md
> update CHANGELOG for 0.0.88

- examples/foundational/07ae-interruptible-hume.py
Added RTVI to the Hume example to have UI feedback for the agent
> Hume add RTVI
